### ISSUE TITLE
Mouse click on variable syntax suggestions doesn't work

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1000]
**Describe the bug**
While adding variables name in a flow and suggestion dropdown comes up in blue color. Somehow mouse click on it to select the suggestion doesn't work. Somehow users get confused with this behaviour.

**To Reproduce**
1. Create a new flow or edit any exiting flow.
2. Choose any action type.
3. In the variable section try to add a variable with provided syntax. @resutls......
4. A suggestion dropdown will open up in blue color.
5. Try to click on the blue suggestion variable name available.
6. On click the suggestion dropdown will disappear, but the name will not copy in the variable field.
7. It works fine if you hit enter.

**Screenshots**
<img width="364" alt="Screenshot 2021-02-12 at 5 35 01 PM" src="https://user-images.githubusercontent.com/16541548/107766577-ab656d00-6d59-11eb-9ee0-4ca3d4576fcd.png">

**Comment by kurund** [comment]
Currently, the floweditor package does not support mouse event for this case. We will come back to this later.

**Comment by dlobo** [comment]
Flow editor issue, wont fix for now
