### ISSUE TITLE
Saved searches - limit to statuses

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1007]
**Describe the task**
Right now whenever a new saved search gets created, it gets added to statuses shown on the chat screen.

**Expected behavior**
For now, we'll limit the statuses to All, Unread, Not replied, Optout.
Let's also check any implications of this change before passing it on to frontend

**Comment by rathorevaibhav** [comment]
@abhi1203 @Ankitkukreti can you check when is good time to work on this and add it to your to-do?

**Comment by kurund** [comment]
@abhi1203 
Currently, we are showing count only for reserved saved searches and not for the ones created by the user.

I was thinking this is inconsistent behavior. There are few limitations to show the count for user-created searches.  I would recommend not to show the user-created searches in there.

@dlobo any thoughts on this?

**Comment by abhi1203** [comment]
@kurund yes, we're not showing 'saved searches' in the chat area now. We're only showing the reserved ones which we're calling 'status'.

**Comment by kurund** [comment]
@abhi1203 Currently, we are showing other  'saved searches'. We will fix it to show only statuses.

**Comment by Ankitkukreti** [comment]
@DigneshGujarathi have a look at this option. its what you suggest earlier for the case https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=2400%3A2015. For the horizontal scroll can we implement this?

**Comment by DigneshGujarathi** [comment]
> @DigneshGujarathi have a look at this option. its what you suggest earlier for the case https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=2400%3A2015. For the horizontal scroll can we implement this?

Sure, it looks great. we will do the required changes.
