### ISSUE TITLE
Change the text from Groups to collection

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1008]
**Describe the bug**
We have modified the name from groups to collections. In the "Add to Group" action type the text still says, groups. Could you please modify this also?

**Screenshots**
<img width="646" alt="Screenshot 2021-02-16 at 12 40 34 PM" src="https://user-images.githubusercontent.com/16541548/108030249-ee268e00-7054-11eb-9546-1f96c181b548.png">

**Comment by abhi1203** [comment]
@Ankitkukreti can you also please check out all the places that groups still exists today. within the flows etc...we should change to collections
