### ISSUE TITLE
Add logging support

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1010]
**Is your feature request related to a problem? Please describe.**
Add the logging support using the below package

**Additional context**
- [x] Integration of the logflare logging.
- [ ] Add loggs for some major API calls.

**Comment by kurund** [comment]
@DigneshGujarathi 
A few places that we should log:
* Apollo errors ( currently we just console those)
* Session handling
* Connection errors (especially websocket)
