### ISSUE TITLE
Verify Gupshup setting error message seen intermittently

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1020]
**Describe the bug**
Verify Gupshup setting error message seen intermittently. During a call with ILP NGO, they showed the screenshot of the error message, they received last night. It is showing fine currently. Need to investigate why sometimes it shows this error message. 

**To Reproduce**
It is intermittent. Not able to reproduce it on production. 

**Screenshots**
<img width="243" alt="Screenshot 2021-02-17 at 1 07 31 PM" src="https://user-images.githubusercontent.com/16541548/108209556-72aa0700-7150-11eb-8142-65fe0fb4087c.png">

**Comment by DigneshGujarathi** [comment]
We have fixed this issue https://github.com/glific/glific-frontend/pull/1023
