### ISSUE TITLE
Add test cases for following items. 

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#1024]
* Ensure unread works
* Sorting and breaking flow screen
* Subscriptions and count
* Gupshup account balance
* (any other critical issues)

**Comment by DigneshGujarathi** [comment]
@pooja1425 Let's add cypress test cases for the above issues

**Comment by pooja1425** [comment]
This issue has been fixed by PR - https://github.com/glific/cypress-testing/pull/96/
