### ISSUE TITLE
Can we show the flow keywords on the flow listing screen

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#1031]
Currently finding keywords for any flows is a bit tough. 

Also, the flow keywords are unique and there is no place to see all the keywords at one place. 

I was thinking if we can show the flow keywords on the listing screen that will be helpful.

Let me know the thoughts. 

![image](https://user-images.githubusercontent.com/10670690/108344693-777bc300-7203-11eb-862c-a1d1e464dc4d.png)

**Comment by abhi1203** [comment]
Good suggestion!
![image](https://user-images.githubusercontent.com/16714604/108984383-dd5dc400-76b5-11eb-9e48-c8e67577651c.png)

Let's do this.
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/xwjQmW

**Comment by pooja1425** [comment]
> Good suggestion!
> ![image](https://user-images.githubusercontent.com/16714604/108984383-dd5dc400-76b5-11eb-9e48-c8e67577651c.png)
> 
> Let's do this.
> https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/xwjQmW

Hey @abhi1203, We don't have **Description** field in Flow. So should we add a separate column for **Keywords**?
or you can suggest a better approach.

**Comment by abhi1203** [comment]
@pooja1425 i was thinking if we could do it like the image i shared, the same style has also been implemented in the staff management screen - below the title
![image](https://user-images.githubusercontent.com/16714604/109264061-5d0c9f80-782a-11eb-954b-54d2702ce182.png)
