### ISSUE TITLE
Validation of flow

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1045]
**Is your feature request related to a problem? Please describe.**
Add validation on publishing flow to verify if there any error.
 
**Describe the solution you'd like**
Call the API to verify the flow by clicking the publish button.

**Comment by abhi1203** [comment]
Please refer here for the error popup 
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/l1RooYx
