### ISSUE TITLE
Double message shown on chat screen

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1046]
**Describe the bug**
A double message on chat was coming. After refreshing the page the double messages were gone. Once again when refreshed the page, it appears again. Able to replicate it on staging.

**Comment by mdshamoon** [comment]
We are receiving multiple subscriptions when more than one user is logged into the same account.
![image](https://user-images.githubusercontent.com/32592458/108694115-a3a98380-7524-11eb-9923-3eead8a68b77.png)

**Comment by dlobo** [comment]
Closing this issue since this has been diagnosed as a backend issue sending multiple subscriptions (actually an absinthe_phoenix issue)
