### ISSUE TITLE
No conversations?

### ISSUE THREAD

**Issue by claalmve** [glific/glific-frontend#105]
**Describe the bug**
Is it possible to have no conversations? If so, in ChatMessages, several errors arise from not having conversations to render. If not, I don't believe there's any bug here, but just wanted to double check.

**To Reproduce**
Reset DB with no data and try to open chats.

**Expected behavior**
Being able to render page with something along the lines of "No conversations yet".

**Comment by kurund** [comment]
@claalmve Yes, we can have contact with no conversations. So need to handle this use case.
