### ISSUE TITLE
Handle Message is required validation while creating the flow.

### ISSUE THREAD

**Issue by pooja1425** [glific/glific-frontend#1050]
**Describe the bug**
Can not send the empty message even if the HSM template is attached.

**To Reproduce**
1. Create flow
2. Configure it, select any action for eg. **Send the message to a contact action**
3. Keep the message empty and Add HSM template from WhatsApp.
4. Click on **OK**

**Expected behavior**
Allow to send the empty message if  template/attachment is already attached.

**Comment by pooja1425** [comment]
Flow editor PR: https://github.com/glific/floweditor/pull/15

**Comment by mdshamoon** [comment]
This is completed. Closing.
