### ISSUE TITLE
Show error when keyword is not present for a flow

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1070]
**Describe the bug**
Keyword is not mandatory when creating a new flow.
While using simulator to preview a flow, the keyword is used to trigger it, but when no keyword is present, the flow doesn't start. we need to prepare for this case with an error or some other solution.

**Comment by mdshamoon** [comment]
@abhi1203 we can go with a notification for now. Can you suggest a message for the notification like : `Sorry, the flow could not be started as no keywords are added for this flow`

**Comment by abhi1203** [comment]
Hey i think since the flow can be started still, we shouldn't show error, we could probably show a message like `no keyword found` similar to how `draft:keyword` is shown in simulator. possible
