### ISSUE TITLE
Optimize axios calls

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1079]
**Describe the task**
Currently, we have all independent Axios calls in components like login, logout, etc.

**Expected behavior**
We should create a hook/function and use that to call.

**Comment by kurund** [comment]
We have already moved common Axios call to methods in AuthService.

I have evaluated the remaining components and here are my comments:
* **Login:** It makes sense to keep Axios logic in the component
* **Logout:**  It makes sense to keep Axios logic in the component
* **ResetPasswordConfirmOTP:**  It makes sense to keep Axios logic in the component
* **ConfirmOTP:**  It makes sense to keep Axios logic in the component

So I feel we can close this issue. 

@mdshamoon thoughts?
