### ISSUE TITLE
Preview and save as draft button overlap in flow

### ISSUE THREAD

**Issue by Ankitkukreti** [glific/glific-frontend#1083]
**Describe the bug**
In flows, when preview is selected the "save as draft" and "preview" button overlap each other

**To Reproduce**
1. Go to 'flows'
2. Create a 'flow'
3. Click on 'preview'

**Expected behavior**
The buttons should not overlap and there should be 16px gap between them.

**Screenshots**
![image](https://user-images.githubusercontent.com/71115895/109277082-d57c5c00-783c-11eb-86b1-0345040638f0.png)

**Comment by mdshamoon** [comment]
@Ankitkukreti this is fixed now. Can you verify this on the staging account?

**Comment by Ankitkukreti** [comment]
@mdshamoon I checked on staging it's fixed thanks.
