### ISSUE TITLE
Cypress test cases for fixed issues & new features/tasks

### ISSUE THREAD

**Issue by pooja1425** [glific/glific-frontend#1086]
Tests to be added:
- [x] Check flow keyword is present on Flows listing page(below the name)
- [x] Check Validation of name & keywords in flow
- [x] Check help document
- [x] Update send msg occurrence after msg send it should be 1
- [ ] Add tests for **Configure flow**

**Comment by pooja1425** [comment]
There is an issue in fetching the values from flow editor actions list, so will target this later.

**Comment by DigneshGujarathi** [comment]
This issue has been fixed by https://github.com/glific/cypress-testing/pull/95
