### ISSUE TITLE
Sending HSM templates from phone when there are large number of character

### ISSUE THREAD

**Issue by Ankitkukreti** [glific/glific-frontend#1125]
**Describe the bug**
In mobile devices, when we select HSM template with large number of character. The whole HSM template text is not visible and also you are unable to side scroll to read text.

**To Reproduce**
1. login in mobile device
2. Go to chat
3. Select a contact
4. Select a HSM template with large number of character
5. See error

**Expected behavior**
We should either enable side scroll or decrease the width of text

**Screenshots**
![image](https://user-images.githubusercontent.com/71115895/109974801-f1419f80-7d1f-11eb-8a7d-21eefa1cb70e.png)

**Comment by mdshamoon** [comment]
@Ankitkukreti let's come back to this issue when we start working on mobile support. Closing this for now.
