### ISSUE TITLE
Switching from contacts to collections in mobile device

### ISSUE THREAD

**Issue by Ankitkukreti** [glific/glific-frontend#1127]
**Describe the bug**
In mobile responsive when you switch from contacts to collection, it does not show the collection chat list and takes you directly to topmost collection in the list. from there you have no option to select other collection, which makes collection non accessible in mobile devices.

**To Reproduce**
1. Login in mobile device
2. Select chat switch tab on the top left corner
3. Switch to collection

**Expected behavior**
When switching from contact list to collection, the collection list should show first.

**Comment by mdshamoon** [comment]
@Ankitkukreti let's come back to this issue when we start working on mobile support. Closing this for now.
