### ISSUE TITLE
Jump to latest

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1135]
**Describe the bug**
If you click on a jump to the latest button it should load current messages (it should have offset zero).
It has an issue when we search messages and try to load the current message by clicking the jump to latest button.

**Comment by kurund** [comment]
@DigneshGujarathi In most of the cases, it is working fine hence I have the PR. 

One scenario that needs handling is when we search and then click on the message.  It correctly takes to that message however clicking on the jump to latest does not do anything.

![Screenshot 2021-03-07 at 10 50 18 PM](https://user-images.githubusercontent.com/151481/110257948-0d4f7600-7f98-11eb-8add-1b1920f4a07e.jpg)

Note that in the above screenshot there are more messages after the '33' message.  (this might new regression after offset fixes)

**Comment by DigneshGujarathi** [comment]
> @DigneshGujarathi In most of the cases, it is working fine hence I have merged the PR.
> 
> One scenario that needs handling is when we search and then click on the message. It correctly takes to that message however clicking on the jump to latest does not do anything.
> 
> ![Screenshot 2021-03-07 at 10 50 18 PM](https://user-images.githubusercontent.com/151481/110257948-0d4f7600-7f98-11eb-8add-1b1920f4a07e.jpg)
> 
> Note that in the above screenshot there are more messages after the '33' message. (this might new regression after offset fixes)

@kurund I have added a fix for the above, can you verify & let me know if any issue.
