### ISSUE TITLE
Flow started with Optin flow for some contacts.

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1172]
**Describe the bug**
Flow started with Optin flow for some contacts.

**Changes made by weunlern:**
They changed things so that the flow with the 'newcontact' keyword does not lead to optin anymore. A few new contacts worked fine, the messages to them stopped at this point.

**Issue:**
But for some contacts, they still got the optin flow. 
Now, they changed the keyword for optin, hoping any default inner flow linking would be cut off then.

**Comment by dlobo** [comment]
I think this was a WULU issue
