### ISSUE TITLE
Usability test results with weunlearn

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1186]
**Describe the task**

- [ ] last message is not showing properly in the preview (it should `hello!Did you like the video so far?` in the preview on the right
![image](https://user-images.githubusercontent.com/16714604/111416135-5a0a1e00-8709-11eb-8b61-19512d7c9e03.png)

- [ ] open the dropdown list below the dropdown input box not on top of it
![image](https://user-images.githubusercontent.com/16714604/111416279-9ccbf600-8709-11eb-9cfc-64c13c0425b2.png)

- [ ] `go to top` for contacts should be placed below the search input field instead of at the bottom
![image](https://user-images.githubusercontent.com/16714604/111416353-c422c300-8709-11eb-9306-381fa5f9f7d1.png)

- [ ] move the dropdown button to the left of the name so that it is in the same place for all users.
![image](https://user-images.githubusercontent.com/16714604/111416424-ea486300-8709-11eb-89e7-e493eb37cdb3.png)

**Comment by Ankitkukreti** [comment]
You can have a look at the inputs for feedbacks here https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=2539%3A360
