### ISSUE TITLE
Jump to latest is always shown

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#1200]
**Describe the bug**
* If a contact has more than default listed messages, 'Jump to latest' is always shown

**To Reproduce**
1. Use scale seed data
2. Vist any contact if more than the default messages
3. See error

**Expected behaviour**
* 'Jump to latest' should be shown only when load more is triggered or when we are not showing the latest messages

**Screenshots**
![Screenshot 2021-03-19 at 1 02 49 AM](https://user-images.githubusercontent.com/151481/111717209-86c84d80-884f-11eb-8941-309399e19b82.jpg)

**Comment by DigneshGujarathi** [comment]
This issue is no longer, so closing it. If anyone detects it, please reopen it.
