### ISSUE TITLE
Trigger validation 

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1204]
**Is your feature request related to a problem? Please describe.**
Can we add validation while entering trigger start_at date to be always greater than or equal to current date

![image](https://user-images.githubusercontent.com/32592458/111778935-7067d380-88db-11eb-91b0-4fa487c26216.png)

**Comment by DigneshGujarathi** [comment]
This is has been resolved https://github.com/glific/glific-frontend/pull/1205
