### ISSUE TITLE
Designs - Login workflow

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#121]
**Describe the task**
As the FrontEnd team has started working on login functionality, we need the design inputs from the design team.

**Expected behavior**
The login workflow should cover the following pages (and designs):
1. Login page
2. Forgot password page
3. Reset password page

**Comment by kurund** [comment]
@abhi1203 We will need "Forgot password" screen. Reset and Forgot seems same.

**Comment by abhi1203** [comment]
Sure. I've added it here: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/loginregister
Let me know if this workflow is fine or we need a different approach.
