### ISSUE TITLE
Designs - Registration workflow

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#122]
**Describe the task**
As the FrontEnd team has started working on the registration workflow, we need design inputs from the Design team.

**Expected behavior**
The registration workflow will cover the following pages:
1. Registration page (fields would be name, phone, password, confirm password)
2. Verify OTP or auth code
3. Validation errors like phone number already registered, weak password, etc.

**Comment by kurund** [comment]
The design looks good. Hene, closing this.
