### ISSUE TITLE
UI update for speed sends dialog box in chat page

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#123]
**Describe the task**
We have an option to add a message as a speed send. Once clicked, a dialog box shows up that asks for the label (name) of the speed send. The message body is automatically saved as the speed send body.
Right now, we're using default Material UI dialog box to display the popup. Need design inputs to have a consistent layout like the tag dialog box.
![image](https://user-images.githubusercontent.com/12053186/86441156-64c28580-bd29-11ea-8552-b99fa9d3d50f.png)

**Expected behavior**
Designs to be added for the "Add message to speed send" dialog box.

**Comment by abhi1203** [comment]
Added here:
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/al8Por
Heading "Add message to speed sends" would be better than "Speed send message title"
