### ISSUE TITLE
Add contacts to collections UI

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1245]
**Describe the task**
1. Remove the cross icon and dropdown icon.
2. Don't load all the contacts all the time, open this input field empty so that users can only manually add few contacts at a time - since we're also relying on the automated (flow-based) method to add at bulk. this method also encourages our users to use the flow-based method. 
3. Adding the `type here...` text so that it's clear that they need to type in there.
4. for removing, they can just go into the details screen and remove contacts.
5. change the label to Search contacts.

**Comment by mdshamoon** [comment]
Closing since this is completed.
