### ISSUE TITLE
Preview of HSM messages

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1247]
**Is your feature request related to a problem? Please describe.**
There is currently no way for users to preview HSM messages.

**Describe the solution you'd like**
Add option for a user to preview HSM while creating or updating.

**Comment by Ankitkukreti** [comment]
Regarding the issue I have created the design, you can have a look here. https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=2991%3A6477

**Comment by mdshamoon** [comment]
This is completed. Closing.
