### ISSUE TITLE
Implement a localization solution for the frontend

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1248]
**Is your feature request related to a problem? Please describe.**
Glific is currently only available in English. We need it to allow other languages

**Describe the solution you'd like**
Add the option to switch the UI to Hindi.

Ref: 
* https://www.npmjs.com/package/i18n (can be skipped)
* https://www.npmjs.com/package/i18next
* https://www.npmjs.com/package/react-intl

**Comment by kurund** [comment]
@DigneshGujarathi let's chat on the package before you get going.

**Comment by kurund** [comment]
`i18next` might be a good option. Check https://www.npmtrends.com/i18n-vs-i18n-react-vs-i18next-vs-react-intl
