### ISSUE TITLE
New flow - preview not working

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1253]
**Describe the bug**
when creating a new flow - preview doesn’t work. does it always need save as draft or publish action?

**To Reproduce**
1. Go to + Create flow screen
2. Add some messages and flows
3. Click on preview
4. the simulator shows draft:<flowname> but the flow doesn't trigger

It's probably because the flow wasn't saved or published. but that shouldn't be required maybe when the flow is still WIP.

**Expected behavior**
The flow should still get triggered.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/113277223-1f55d780-92fe-11eb-9a06-39ef19ce5506.png)

**Comment by mdshamoon** [comment]
@abhi1203 This issue is fixed now. Can you verify this on your end?
