### ISSUE TITLE
search query is called several times

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1258]
**Describe the bug**
Within a few seconds, a search query is called several times. This must be avoided in order to avoid performance issues.

![Screenshot from 2021-04-01 19-39-45](https://user-images.githubusercontent.com/26589967/113563147-d2873f00-9624-11eb-995d-283d442f2be0.png)

**Comment by mdshamoon** [comment]
Closing since this has been possibly fixed.
