### ISSUE TITLE
Message input to support multiple lines

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#126]
**Describe the task**
A user can send multiple lines within a message. Right now, we cannot send more than one line in a message.

**Expected behavior**
1. When typing `Shift + Enter` from the keyboard, the message input should move the cursor to a new line without sending the message.
2. When typing only `Enter` from the keyboard, the message should be sent like it's happening now.

**References**
See WhatsApp Web to refer the functionality

**Comment by claalmve** [comment]
Use textarea.
