### ISSUE TITLE
Issue with the contact query variables

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1265]
**Describe the bug**
{
  "operationName": "contact",
  "query": "query contact($id: ID!) {\n  contact(id: $id) {\n    contact {\n      groups {\n        id\n        label\n        users {\n          name\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
  "variables": {
    "id": "saved-searches"
  }
}

**Comment by mdshamoon** [comment]
Closing since we are not getting this error anymore.
