### ISSUE TITLE
HSM Template - Pre populate "Sample Message" field with the content user is adding in "Message" field

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1280]
**Is your feature request related to a problem? Please describe.**
It is observed that there are minor differences in the message and sample messages fields content in HSM templates while submitting it. It is a bit tough for users to keep the content the same, which might be a reason for the rejection of HSM templates.
**Some examples - issues NGOs faced in the past.**
1. 
<img width="622" alt="Screenshot 2021-04-09 at 3 10 08 PM" src="https://user-images.githubusercontent.com/16541548/114163738-29a05300-9948-11eb-954b-c85f0913faa2.png">

2. 
<img width="552" alt="Screenshot 2021-04-09 at 3 15 30 PM" src="https://user-images.githubusercontent.com/16541548/114163840-43419a80-9948-11eb-8bd4-3755fa2c70a2.png">

**Describe the solution you'd like**
The suggestion is to prepopulate the content in the "Sample Message" field while the user enters the content in the "Message" field to avoid any mismatch in the content users may to by mistake while adding content again in "Sample Message" field.

**Describe alternatives you've considered**
Give a button to copy the content in the "Sample Message" field from the "Message" field once the user finishes the content addition.

**Comment by abhi1203** [comment]
@mohitsharma-22 
Pre-populating the content may lead to other errors while submitting. And copy button is the same function as Copy and Paste. Did users try that? 
Also, is it possible to get to know what kind of differences there were? 

What I could speculate doing is to highlight the differences with a marker(digital, like when you select a text).
But it would be good to explore the problem more before suggesting a solution.

Could you also please share how did the users resolve the bug finally, or they weren't able to resolve it?

**Comment by mohitsharma-22** [comment]
@abhi1203 When I checked there were differences in punctuations and special characters like "|". One was having special characters and others were not having. 
In the 2nd example, the user missed adding "Hi" at the start of the message.

To resolve this, I asked for the exact content entered in the messages and compared it manually.

Yes, We can also highlight the differences, which will prevent such issues. Also, we can guide the users to copy-paste to avoid issues and add the instructions in the documentation for users.

I will see if any such issues come again, I will try to capture the steps to recreate it.

**Comment by mdshamoon** [comment]
@abhi1203 @mohitsharma-22 this issue is the most common when we create a template. It even happens when there is a single space difference between the message and the sample message which users can't identify even after copying the message.

**Describe the solution you'd like**
Highlighting the differences can be an option since even a single extra space can make it unsupportable.
Also, we can add a note saying that- `The message and the sample message should be exactly the same, even the spaces and new lines`

Let me know your thoughts.

**Comment by mdshamoon** [comment]
We have added validation for the message and sample message to be same. It should possibly remove most of the errors faced by users.
