### ISSUE TITLE
STAFF access to the contact details

### ISSUE THREAD

**Issue by bhanusameer** [glific/glific-frontend#1281]
Need access to the STAFF to view the contact number of the user as it is an important thing for us to follow-up with them on ground after the usage.

**Comment by dlobo** [comment]
Basically, if user has role STAFF, but has is_restricted set to TRUE, we show the phone number, since the user has access to only a smaller group of contacts

**Comment by mdshamoon** [comment]
@dlobo we are not receiving phone from the backend in case the role is staff and is_restricted is set to true. 

![image](https://user-images.githubusercontent.com/32592458/114821035-95b60780-9ddd-11eb-9f48-0929cbd11f05.png)

**Comment by mdshamoon** [comment]
This is fixed. Closing.
