### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1292]
**Describe the task**

Need UI improvements in the following areas:-

- [ ] If there are no conversaions 
<img src="https://user-images.githubusercontent.com/32592458/114839463-6b6f4480-9df3-11eb-8f86-eb746265c609.png" width="400" height="300">

- [ ] Add a message saying something like `There are no items to display` If no items are present in the list
<img src="https://user-images.githubusercontent.com/32592458/114839857-e0db1500-9df3-11eb-8c51-802bdbb024a7.png" width="600" height="300">

- [ ] Fixed width for error message
- [ ] Increase distance between error message and description

![image](https://user-images.githubusercontent.com/32592458/114840455-74ace100-9df4-11eb-97c7-c004e65eda93.png)

**Comment by abhi1203** [comment]
@mdshamoon 
1. for no search result in sidebar: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/v8EDaA3
2. for no search result in the triggers screen: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/KvGmn11
3. For error message: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/1Kx3Lp5
