### ISSUE TITLE
ESlint error

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1298]
Got ESlint error while settting up front end with latest pull
here is quick link [https://stackoverflow.com/questions/46208367/how-to-remove-eslint-error-no-unresolved-from-importing-react](here)

**Comment by DigneshGujarathi** [comment]
@AkhileshNegi What was the specific error? After yarn setup / npm install, is it gone?

**Comment by mdshamoon** [comment]
@AkhileshNegi are you still facing the same error on the latest master?

**Comment by mdshamoon** [comment]
Closing the issue since it's not replicable.
