### ISSUE TITLE
Formatting support for chat message input

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#132]
**Describe the task**
* Support basic text message formatting such as bold.

**Expected behavior**
* Message sent should be displayed as per formatting on Whatsapp and chat interface

**Comment by claalmve** [comment]
Check out how WhatsApp deals with these inputs (i.e. *bold* for bold)

**Comment by claalmve** [comment]
- https://draftjs.org/docs/api-reference-content-state
- https://www.npmjs.com/package/markdown-draft-js

**Comment by claalmve** [comment]
- https://www.npmjs.com/package/marked for rendering Markdown back to HTML
