### ISSUE TITLE
Listing of all organizations

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1323]
**Is your feature request related to a problem? Please describe.**
Add a screen to monitor organizations status (Active/Inactive/Awaiting approval)

**Describe the solution you'd like**
Listing of all organizations split into 3 groups/status
* Active Organizations
* Organization awaiting approval
* Organization in-active
* For active organizations, we should have a Make Inactive button
* For in-active organizations, we should have a Make Active, and Delete Organization button. The delete organization should have a confirmation and make the user type the full name of the organization
* For organizations awaiting approval, we should add an Approve and Delete action, which marks the organization as approved and/or deletes the organization

**Comment by abhi1203** [comment]
@shreesh1993 https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/org-listing design for org listing
