### ISSUE TITLE
Add the option to upload files and send it

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#1349]
**Is your feature request related to a problem? Please describe.**
Add the option to upload files from a local machine/computer.

**Describe the solution you'd like**
Users can upload and send any type of file to a contact, including images, audio, video, and documents from their computer/mobile.
The organization must create a GCS account before they can use this feature; otherwise, it will be disabled for them.
We need to create media in GCS and use the GCS URL for sending it to contact.

To verify gcs - https://github.com/glific/glific/blob/master/api.docs/includes/_organizations.md#check-for-attachment-support-for-the-given-user

**Comment by abhi1203** [comment]
You can see it here:
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/VgA8Pq/play
I'll add an alert for upload file when GCS is not connected.
