### ISSUE TITLE
Flow editor should have easier way to horizonal/vertical scroll within board

### ISSUE THREAD

**Issue by jk979** [glific/glific-frontend#1363]
Problem: Currently the only way to navigate through the flow (especially if it's large) is to use the sidebar scrolls. And the horizontal scrollbar doesn't appear until the right sidebar is scrolled all the way down. It's hard to navigate horizontally and vertically generally. 

Solution: 
a) add hand option to allow for easier "dragging" navigation for large/complex flow boards, or 
b) always enable the horizontal scrollbar--should always be visible and/or able to horizontally scroll with shift+mouse-scroll

**Comment by mdshamoon** [comment]
@jk979 we have added a horizontal scroll on the flows screen and it will be on production in the coming release this weekend.
You can test it out on our staging site https://staging.tides.coloredcow.com and let us know if you have any feedback
 
 Staging site credentials:
 ```
 Phone number: +917834811114
Password: secret1234
```

**Comment by bandhu-tech** [comment]
Thanks! This works, click/drag function to pan the view would also be nice to have in future releases

**Comment by jk979** [comment]
Thanks! This works, click/drag function to pan the view would also be nice to have in future releases

**Comment by mdshamoon** [comment]
@jk979 Sure we will add this in our future roadmap.
