### ISSUE TITLE
After searching, clicking on the results refreshes the screen and starts showing all the chats

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#138]
**Describe the bug**
* After searching, clicking on the results refreshes the screen and starts showing all the chats

**To Reproduce**
* After searching, clicking on the results refreshes the screen and starts showing all the chats

**Expected behavior**
* It should not refresh the page.

**Comment by claalmve** [comment]
Hmm, I can't seem to reproduce this bug. Currently when I search, the correct results are rendered but the screen isn't refreshed (I'm also assuming this is for searching ChatConversations). Would it be possible for me to check out this bug with you on your end?

**Comment by claalmve** [comment]
Accounted for in #154 .
