### ISSUE TITLE
Make particular flow arrow (and children) inactive if not yet ready for deployment

### ISSUE THREAD

**Issue by jk979** [glific/glific-frontend#1382]
Problem: Developer building the flow may not have all the options ready yet for deployment (i.e. missing a URL/resource or feature not yet finalized). 

Example: 
3 options. 2 of the options are ready for deployment, 3rd option is not fully ready, but built on the flow editor. 
User in flow editor should be able to right-click the flow arrow of 3rd option and make it inactive, and it becomes red in the UI showing that it is currently inactive--but it is still there an can be activated when the endpoint feature is ready. 

This can help clarify which sub-flows are still under development while allowing for deployment of the rest of the flow. User won't have to delete the inactive flow and recreate it later when it's ready.

**Comment by mdshamoon** [comment]
@jk979 in this case what you can do is don't connect the under-development node with any other node. Just connect it when it's completed.

![image](https://user-images.githubusercontent.com/32592458/117935910-da23bd00-b321-11eb-86aa-dc906392bc6e.png)

**Comment by mdshamoon** [comment]
We will have a look at this in the future. Closing it for now.
