### ISSUE TITLE
Add favicon for the project

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#143]
**Describe the task**
* Add favicon for the project

**Expected behavior**
* Should show the new favicon

**Comment by kurund** [comment]
@abhi1203 Let us know once you add the favicon.

**Comment by abhi1203** [comment]
Sorry @kurund here it is: Just put together something for the time being.
https://drive.google.com/file/d/1MR-QITDdz4DkLBuXcQkJGqoiwKyXF9FW/view?usp=sharing

**Comment by kurund** [comment]
@abhi1203 Thanks.
