### ISSUE TITLE
Research and think of a way to unify cache for saved searches

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1441]
**Describe the task**
Currently, only the cache for `All` searches gets updated when we send or receive a message. We don't update the cache data for the rest of the saved searches like unread, not replied, etc.

<img src="https://user-images.githubusercontent.com/32592458/120754110-d4d51f00-c529-11eb-9ba0-e92bb68d0982.png" width="400px"/>

**Expected behavior**
The behavior should be the same for all saved searches.

**References**
Look into fragments in apollo client and see how it can be used for this https://www.apollographql.com/docs/react/data/fragments/

**Comment by kurund** [comment]
This is not critical and we can comeback to this sometime in the future.
