### ISSUE TITLE
Update UI for document attachment

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1457]
**Describe the task**
Document attachment does not match our overall theme and looks out of place. Update the UI for the document so it matches our theme.

**References**
- On Glific end

<img src="https://user-images.githubusercontent.com/32592458/121303443-b485d580-c918-11eb-9ed6-9ebe318b19f6.png" width="300px">

- On WhatsApp end

<img src="https://user-images.githubusercontent.com/32592458/121303749-121a2200-c919-11eb-8de4-3cb8ee047436.png" width="300px">

**Comment by abhi1203** [comment]
There's on challenge here, whatsapp doesn't allow captions with audio and document. so even though we design and show it on glific, it doesn't render properly on whatsapp. 

the message simply goes as the file name

**Comment by abhi1203** [comment]
I'm thinking of something like this. https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/dlkP9Rl
