### ISSUE TITLE
Add support for interactive messages

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1495]
**Describe the task**
Add support for interactive messages

**Comment by abhi1203** [comment]
Interactive msg listing: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/52D5w0w/play
You may follow the clicks to see the chagnes on the chat screen and floweditor screen. 
let me knowif you spot something that needs to be updated/changed.
