### ISSUE TITLE
Resizing context message

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1505]
**Expected behavior**
UI cleanups for the context message, when receiving a reply to a message

**Screenshots**
<img width="872" alt="Screenshot 2021-07-06 at 12 11 03 PM" src="https://user-images.githubusercontent.com/40158831/124554485-a5c90a80-de53-11eb-98ab-f33a93172457.png">

**Comment by mdshamoon** [comment]
Design file for context messages- sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/dlkP9Rl
