### ISSUE TITLE
Media is missing interactive message

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1538]
**Describe the bug**
The youtube video preview is missing from the interactive message

![image](https://user-images.githubusercontent.com/16714604/125919515-8215fb49-0360-4af6-a98a-a1d0bde3421b.png)

**Comment by mdshamoon** [comment]
@abhi1203 interactive messages do not support link previews since the message body is treated as a caption in this case.

**Comment by abhi1203** [comment]
@mdshamoon we need to find a way to have attachmnets for these messages then
