### ISSUE TITLE
TAP: Slow searches

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1551]
**Describe the bug**
sometimes the platform becomes very slow
ex. searching the student name and opening the chat. they have to refresh that page. total contacts 1.5k-2000

`getting more details from TAP for where exactly it happens`

**Comment by mdshamoon** [comment]
@abhi1203 any updates on this. Is TAP still facing this issue?

**Comment by kurund** [comment]
@abhi1203 closing this for now. if needed please feel free to reopen.
