### ISSUE TITLE
Chat searching, the results should filter real time

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#157]
**Is your feature request related to a problem? Please describe.**
* Usability improvement

**Describe the solution you'd like**
* For chat searching, the results should filter real time. this would remove the requirement of 'Enter' or Submit action

**Comment by claalmve** [comment]
On keyup, wait, and then hit the endpoint. Set timeout function. When the user stops for brief amount of time (0.5 seconds?), make this request.

**Comment by kurund** [comment]
Sounds good to me.

**Comment by claalmve** [comment]
https://github.com/slorber/react-async-hook#how-can-i-implement-a-debounced-search-input--autocomplete
