### ISSUE TITLE
List screens are not mobile responsive

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1581]
**Describe the bug**
List screens are not mobile responsive

**To Reproduce**
1. Go to any list screen like speed sends, flows etc.
2. Check on mobile resolution
3. You will see the UI broken on various points

**Expected behavior**
The UI should not be broken

**Screenshots**
![image](https://user-images.githubusercontent.com/32592458/128687106-37657433-676d-4d97-a894-7c53dfc4b102.png)

**Comment by kurund** [comment]
@mdshamoon 

These screens are meant to be used on a larger screen size, so it's ok to be non responsive.
