### ISSUE TITLE
Move help menu to main menu

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#1590]
* Remove floating help menu and add it after notifications menu

**Comment by kurund** [comment]
@abhi1203 I think we had discussed this earlier but got lost in translation :) Thoughts!

**Comment by abhi1203** [comment]
@kurund yes thanks for bringing it up. i saw it on one of the customers screen that it was overlapping with other menu. so thought it would be better to move it to menu options only. would be good to take it up, it's added in the design file.
