### ISSUE TITLE
Flow editor - multiple users

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1600]
1. Move the user's name to next line. 
![image](https://user-images.githubusercontent.com/16714604/129728766-6ba9aff3-47ff-49a2-8ce9-c14f79b6156f.png)
like this:
![image](https://user-images.githubusercontent.com/16714604/129729266-9ec76a41-0162-446d-8ddf-aa14e8a0f000.png)

**Comment by mdshamoon** [comment]
@AkhileshNegi can you please update this error message from the backend.
