### ISSUE TITLE
After entering some filters in advanced search, i'm unable to type anything in the input

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1608]
![image](https://user-images.githubusercontent.com/16714604/130041649-d481ceb7-c2fa-4500-bee4-c587d0f97c53.png)

![image](https://user-images.githubusercontent.com/16714604/130041681-a90570ed-9820-406d-8fbd-8f3ed709ca22.png)

**Comment by kurund** [comment]
Currently working fine. It might have got fixed at some point.
