### ISSUE TITLE
Error message of chat unavailable due to no opt-in

### ISSUE THREAD

**Issue by jk979** [glific/glific-frontend#1613]
This error message appears in Staff Management section when clicking the account whose number is associated directly with the Whatsapp business chat account.  "Chat is unavailable with this contact because they aren't opted in to your number." Expected to be able to chat with this account. Have been advised by Glific that this main account is a special account and the originator of all messages, so it should not even be displayed in Staff Management here. 

![image](https://user-images.githubusercontent.com/16037898/130360833-9070daa6-20de-4e77-8a04-2699f05b3c96.png)

Desktop Browser: Firefox v91.0

**Comment by kurund** [comment]
@abhi1203

I kind of agree that it might be better not to list NGO main contact in the staff listing. The available actions like edit and delete are not relevant too. 

Thoughts?

**Comment by abhi1203** [comment]
@kurund yeah, agreed. Would it be possible to keep it in the list for reference but remove all actions? send message, edit and delete? I don't think access level for this number will change ever right? if so then we can hide actions.
