### ISSUE TITLE
Triggers: Trigger listing

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1624]
**Is your feature request related to a problem? Please describe.**
can we  separate active trigger and inactive triggers listing similar to template screen

**Describe the solution you'd like**
A clean separate listing for triggers

**Screenshot**
<img width="1264" alt="Screenshot 2021-09-01 at 10 39 22 PM" src="https://user-images.githubusercontent.com/40158831/131714900-1a3f675f-c446-4b48-a63c-326279c35a59.png">

**Comment by kurund** [comment]
We can come back to this if it's needed in the future.
