### ISSUE TITLE
Flow Editor: language specific interactive messages

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1655]
**Describe the bug**
While converting an existing `send a message` node with at least one translation to `send an interactive message` getting white screen
**To Reproduce**
1. Go to Flows and create a new flow
2. Create a `send a message` node and enter a message
3. Click on any other language and save the translation to the same node
4. Now change `send a message` node to `send an interactive message` node
5. Click on any other language.
6. A white screen appears as shown in screenshot

**Expected behavior**
we should be able to convert any node of one type into another without errors.

**Screenshots**
<img width="1341" alt="Screenshot 2021-09-13 at 3 35 40 PM" src="https://user-images.githubusercontent.com/40158831/133065426-e29aa289-a08a-4243-933f-0e73a40d272c.png">

**Comment by mdshamoon** [comment]
This has been fixed and tested on staging.
