### ISSUE TITLE
Pause/resume flow

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1669]
**Is your feature request related to a problem? Please describe.**
[Requirement](https://docs.google.com/document/d/1Q7ozYAHl1wcVQlXcg3iZjQZPHaUQJzQCYHTLaajncrs/edit#)

**Describe the solution you'd like**
Design
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/VgA8Pq
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/Ogb9A2

![image](https://user-images.githubusercontent.com/16714604/134484833-204ab1ce-f7f0-4b3b-a1a6-cfa07656925e.png)
![image](https://user-images.githubusercontent.com/16714604/134484867-6ca51e58-50a9-4d87-91a1-f4eb2a884fed.png)

**Comment by kurund** [comment]
@abhi1203 

I feel the toggle interface with the play + pause icon is bit confusing. I am wondering if only a toggle or play+pause round icon might be better.

If you strongly think this is better we can implement the same.

**Comment by abhi1203** [comment]
@kurund I sure, we can go ahead with only toggle without the pause and play icons. II felt that might give an added visual cue but it works without also. play/pause is strongly associated with music and videos so i didn't go for that. 
If it's convenient to build, i'd be happy to see the icons in toggle - looks like a cool ui, else also it's fine

**Comment by kurund** [comment]
@abhi1203 

Sure, we will go with the proposed UI then. Thanks.

**Comment by mdshamoon** [comment]
As discussed in the standup @abhi1203 can we add an option to terminate all flows for the contact in the UI.

**Comment by abhi1203** [comment]
@mdshamoon here: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/1gnW34/play let me know if this is fine and all covered
