### ISSUE TITLE
Switching language while creating speed send adds the same data as the previous language

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1685]
**Describe the bug**
Switching language while creating speed send adds the same data as the previous language

**To Reproduce**
1. Go to create a speed send screen
2. Fill in all the details
3. Switch language
4. It still shows the previous language details in the new language

**Expected behavior**
It should not show previous language details.

**Comment by kurund** [comment]
@mdshamoon 

I feel this behaviour is not too bad as it provides the user with data that needs to be translated etc.

I am closing this and can come back if we get too many complaints from the end-users.
