### ISSUE TITLE
Can we show the @contact variable on the update contact node

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1694]
**Describe the task**
Right now, in the update contact node, users are not able to click on the suggestion dropdown (see image)
Also, can we show the contact variable at the bottom of the update contact node - like it shows for results node. This would be very helpful because users need to remember what that is right now. they can simply copy paste if this is done.

**References**
<img width="762" alt="Screenshot 2021-10-08 at 1 17 32 PM" src="https://user-images.githubusercontent.com/16714604/136548511-3a241b86-6373-40ff-89fe-159857a579fe.png">

**Comment by mdshamoon** [comment]
We don't have the functionality to select an option by clicking instead it provides an option to select by pressing tab or Enter.

@abhi1203 after our discussion I don't think we need these functionalities in floweditor, so closing this issue.
