### ISSUE TITLE
Unable to click [Ok] on wait for response modal

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1696]
**Describe the bug**
While creating a new `wait for response` node, our users were unable to click on the Ok button. the pattern was kind of as shown in the image below

choosing has any words (leave empty), enter category, enter result name and click ok.

<img width="762" alt="Screenshot 2021-10-08 at 12 24 21 PM" src="https://user-images.githubusercontent.com/16714604/136549510-a43a4ca9-e9f8-43cd-a5d2-1812c4ae36b5.png">

**Comment by mdshamoon** [comment]
Fixed in this PR https://github.com/nyaruka/floweditor/pull/1018. Need to update flow editor version
