### ISSUE TITLE
Enhancements to consulting screen

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1697]
There are a lot of usability challenges required on the consulting screen, particularly because we didn't anticipate how we'd use it. The changes required are:

- [x] 1. Show the support team's name upfront in the columns so that it's easy to differentiate hours and make sure everyone had added it (without going into the edit screen).
- [x] 2. Provide organisation filter. Right now after searching, going to detail screen and coming back, the page refreshes and organisation filter is lost.
- [ ] 3. When multiple support teams are added in one entry the total hours should get multiplied 
- [ ] 4. Need some reporting based on this as well: https://github.com/glific/glific/issues/1795

**Comment by abhi1203** [comment]
Added filter UI here: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/ELRMYQg
Requesting if Date range is possible within one input field - will save space. like this:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/16714604/154270803-fd5985a7-223d-4047-99a5-0d52aef2de66.png">

**Comment by mdshamoon** [comment]
The bizdev team will discuss and check if this needs to be done.

**Comment by mdshamoon** [comment]
We will not modify the consulting screen any further and plan on moving it out from Glific.
