### ISSUE TITLE
Sticker attachment throws error.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1707]
**Describe the bug**
On the chat screen, there is an option to send stickers as an attachment.
It throws an error when we try to do stickers attachment.
http://www.buildquickbots.com/whatsapp/stickers/SampleSticker01.webp

We also need an option to upload stickers attachment from flows

**Screenshots**
<img width="436" alt="Screenshot 2021-10-20 at 11 08 04 AM" src="https://user-images.githubusercontent.com/16541548/138034702-a6e3bfa7-a908-4cfc-b43d-69522ec3beb8.png">

<img width="641" alt="Screenshot 2021-10-20 at 11 01 54 AM" src="https://user-images.githubusercontent.com/16541548/138035009-d849655d-1bce-442f-afc2-2968838fd013.png">

**Comment by mdshamoon** [comment]
- Created an [issue](https://github.com/glific/glific/issues/1907) in the backend for the error part.
- Tracking the option to add sticker option in flow separately #1783
