### ISSUE TITLE
Release all the flows for the user whenever he logs in 

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#1708]
**Describe the task**
Currently, we are releasing the flows when users publish it or log out. Sometimes the user is getting logged out because of timeout and some weird reasons but the flows are still locked. 

**Expected behaviour**
Release all the flows whenever user logs in so that we can avoid this issue till the time we figure out the login thing.

**Comment by mdshamoon** [comment]
Closing this issue as the problem for flow locks has been resolved.
