### ISSUE TITLE
Add option to select type of attachment after uploading the URL

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1720]
**Describe the task**
Add option to select type of attachment after uploading the URL

**Comment by kurund** [comment]
@mdshamoon 

We can select type here.

![Screenshot 2022-03-26 at 9 13 43 PM](https://user-images.githubusercontent.com/151481/160257371-71065844-854d-443d-981d-5183ef4a4f70.jpg)

Am I missing something?

**Comment by mdshamoon** [comment]
@kurund there's another option to upload a URL when we have GCS activated. In that when we upload the file it does not ask the type of file to be sent.
