### ISSUE TITLE
Interactive message - Markdown in header text is not showing error message

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1725]
**Describe the bug**
Markdown is not allowed for header text in the interactive messages. But when creating an interactive message - if someone adds - this does not show up as an error, which gives the incorrect title of the interactive messages.

**To Reproduce**
1. Go to interactive messages 
2. Create a new interactive message
3. Add Markdown in the header text and other details in the interactive message
4. Save it.

**Expected behavior**
Markdown characters in header text should show an error message and should not allow users to add them.

**Screenshots**
<img width="1198" alt="Screenshot 2021-10-29 at 11 26 40 AM" src="https://user-images.githubusercontent.com/16541548/139383340-b62b4ae2-af71-4dad-b2c2-9013afe9935b.png">

<img width="1177" alt="Screenshot 2021-10-29 at 11 27 04 AM" src="https://user-images.githubusercontent.com/16541548/139383362-8dc5d321-6c7e-41d4-84ca-1e299bebd558.png">

**Comment by mdshamoon** [comment]
As discussed in the standup we are not adding any validations for markup language and instead removing the markup conversation of title from the simulator so that user's doesn't get confused by seeing different results in Simulator
