### ISSUE TITLE
Add an ability to make titles optional in interactive message

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1733]
**Is your feature request related to a problem? Please describe.**
Sometimes the message content does not support the available formatting - particularly with including titles in the message.  

**Describe the solution you'd like**
Make adding titles option since whatsapp can support that.

**Comment by mdshamoon** [comment]
@AkhileshNegi can we create a new boolean field isTitleOptional (name can be changed) that adds or removes the title based on the field value.

**Comment by abhi1203** [comment]
@mdshamoon does this work: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/ZO41R5x
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/JnWZrpG
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/eK8E4q0 (mentioning that the title will be hidden)
let me know if you see any other cases we should consider for UI

**Comment by mdshamoon** [comment]
> @mdshamoon does this work: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/ZO41R5x https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/JnWZrpG https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/eK8E4q0 (mentioning that the title will be hidden) let me know if you see any other cases we should consider for UI

I think it covers all the cases in the UI. Thanks
