### ISSUE TITLE
Add emoji support in speed send add/edit screens

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#175]
**Describe the task**
Speed sends can have emojis when they are created from a message in the Chat screen.
Emoji support is not there when we create/edit a speed separately (not from chat screen).

**Expected behavior**
The message field in speed-send add/edit pages to have emoji picker

**Comment by abhi1203** [comment]
Something like this maybe? The emoji picker can open the same way it opens on the chat screen
![image](https://user-images.githubusercontent.com/16714604/87162950-44279c00-c2e4-11ea-9499-0be580d7ddfa.png)
![image](https://user-images.githubusercontent.com/16714604/87163116-7cc77580-c2e4-11ea-90a2-9f4dd04bc516.png)
