### ISSUE TITLE
Change message for starting a flow for a collection to avoid confusion

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1750]
**Is your feature request related to a problem? Please describe.**
We have changed the functionality. Now the flow starts after a minute for the contacts in the collection and the NGO user triggers it.

**Describe the solution you'd like**
Please change the message, saying "Your flow will start at the scheduled time", to avoid confusion for users.

<img width="798" alt="Screenshot 2021-11-17 at 3 10 33 PM" src="https://user-images.githubusercontent.com/16541548/142176937-59375f2a-a27d-462b-aca0-47608e59e655.png">

**Comment by mdshamoon** [comment]
@abhi1203 need your inputs on this issue.
