### ISSUE TITLE
Previous versions of Glific Demos not playing on features page

### ISSUE THREAD

**Issue by AbhayTheEngineer** [glific/glific-frontend#1763]
**Describe the bug**
1. On clicking the demo videos at the right of the video container, the video container goes blank and there is no output upon switching the options.
2. After refreshing the page, only the video visible at the page load is playable and again the other demo videos are unplayable and the issue is recurring.

**To Reproduce**
1. Go to 'https://glific.org/features/'
2. Scroll down to 'Demo Videos'
3. See error.

**Expected behavior**
The demo videos on the right side are supposed to play in the screen view intended for the videos to play when user selects the desired video option.

**Screenshots**
Video addressing the issue has been attached for reference - https://user-images.githubusercontent.com/72443500/143676763-0b4e90b4-42d7-43fb-b271-30cde0e39550.mp4

**Desktop (please complete the following information):**
- Macbook Pro Retina
 - MacOS 12
 - Brave Browser
 - Version - V1.32.113

**Comment by mdshamoon** [comment]
@AbhayTheEngineer we have resolved the issue. Please test it on your end and let me know if it's working fine.

**Comment by AbhayTheEngineer** [comment]
@mdshamoon Tested thoroughly and it is working as intended. Thank you.
