### ISSUE TITLE
ISL requirement from Enable India

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1767]
**Is your feature request related to a problem? Please describe.**
They want another language option to mange their ISL messages. ISL messages are different from regular messages - it contains a video link and a much shorter caption.
Few more details provided by their team is here: https://docs.google.com/document/d/1Cfver5IRMZlpNr1dTbj-h3sY4hm0PwbO/edit

**Describe the solution you'd like**
To have another language option in floweditor like other languages. They will select it to enter the custom messages for people who need ISL.

**Describe alternatives you've considered**
Currently using webhook to direct the user to another flow if users select ISL language option. But that is harder to manage for messages in other flows. This can be viewed on their account also how they are managing it right now.

**Comment by pankaj-ag** [comment]
@abhi1203 can we close this ?

**Comment by abhi1203** [comment]
Yeah
