### ISSUE TITLE
Provide option to add dynamic URL in HSM buttons

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1779]
**Describe the bug**
While working with Reapbenefits, it is observed that there is no way to add a dynamic URL in Button in HSM templates. Whereas as per the discussion is standup, we can submit the same from gupshup. The request is to add the option in Glific HSM template page.

**Screenshots**
<img width="520" alt="Screenshot 2021-12-14 at 4 11 03 PM" src="https://user-images.githubusercontent.com/16541548/146127286-4729a4dd-b0e2-43d1-83f9-0e126f0f61d0.png">

**Comment by mdshamoon** [comment]
It is a backend fix. Created an [issue](https://github.com/glific/glific/issues/1908) with the requirements needed.
