### ISSUE TITLE
Show more button in contact history doesn't work

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1788]
**Describe the bug**
Show more button in contact history doesn't work. It refreshes the page and shows the same entries again.

**To Reproduce**
1. Go to contact history
2. Click on the show more button
3. It will show the new entries for a second and then load the same entries again.

**Screenshots**

<img width="517" alt="Screenshot 2021-12-20 at 12 34 46 PM" src="https://user-images.githubusercontent.com/16541548/146732590-5fc423e9-5f86-4ef5-8412-f8ab630f7c5b.png">

**Comment by mdshamoon** [comment]
This is a backend fix. We are getting different data for the same query sometimes or getting duplicate data even after updating the offset and it's happening because of that.

**Comment by mdshamoon** [comment]
@mohitsharma-22 this is fixed. Please test it on your end once and let us know if you are still facing this issue.
