### ISSUE TITLE
Wait for response issue for different languages

### ISSUE THREAD

**Issue by wevekamola** [glific/glific-frontend#1808]
**Is your feature request related to a problem? Please describe.**
There is confusion while adding the expected input from users in wait for response for different languages. The users are adding category name translation and assuming the change for expected user input. There is a lack of knowledge that by clicking on Rule Translations they can add the expected input from users in a different language.

<img width="600" alt="Screenshot 2021-12-27 at 7 41 48 PM" src="https://user-images.githubusercontent.com/29367838/147479621-31ad62b3-d7cc-4b92-be5a-ea03316e9ac6.png">

**Describe the solution you'd like**
For different languages can we show Rule Translations as highlighted tab, that way they won't update the category name translation, and can easily add the user input in the desired language.
<img width="700" alt="Screenshot 2021-12-27 at 7 36 25 PM" src="https://user-images.githubusercontent.com/29367838/147479533-ae123b37-cbbd-42fb-a86a-bafac1fec873.png">

**Comment by mohitsharma-22** [comment]
Another suggestion for *wait for response* for other languages is to have 3 columns.
English translation of the value | Value in other languages | category in other languages.
<img width="637" alt="Screenshot 2021-12-27 at 8 21 20 PM" src="https://user-images.githubusercontent.com/16541548/147483047-51e494a9-89ea-40c5-83d3-4a8a4e96214f.png">

**Comment by mdshamoon** [comment]
@abhi1203 need your inputs on this issue
