### ISSUE TITLE
Contact History: Show time of an event

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1809]
**Is your feature request related to a problem? Please describe.**
In contact history, we show only the date of a contact history event and not the time, though the events are sorted in descending order, having time corresponding to each entry would be much informative

**Describe the solution you'd like**
Show the timing of the contact history event in-between event and date

**Screenshot**
![image](https://user-images.githubusercontent.com/40158831/147723541-2a4eefff-beda-4204-b1b4-01a2d2f758d1.png)

**Comment by abhi1203** [comment]
@AkhileshNegi 
here: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/81A5a7
we'll need to increase 1 column space for the input fields above also

**Comment by kurund** [comment]
@abhi1203 

This is the only place we are using am/pm.  Also showing `9/01/2022` instead of `09/01/2022`.

Let me know your thoughts?

**Comment by abhi1203** [comment]
Hey @kurund im okay with 24hr clock also if we've used that. 12 hrs might be confusing without am/pm. and i needed more space so i shortened the date fo 9/01/22 we can use full 9/01/2022 alsoo since widening this section will give some space

**Comment by kurund** [comment]
@abhi1203 

Thank you. I have updated the date format to be consistent with other date-time interfaces.
