### ISSUE TITLE
Default Flow: disable edit option

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1810]
**Describe the bug**
When entering the start and end time of the default flow, there is an icon of the clock to enter the timing however once the time is entered it can be edited by clicking on time and manually typing the time. This allows users to enter invalid time as well which should be avoided.

**To Reproduce**
1. Go to the Organization setting
2. Select the default flow and enter start and end time
3. Click on the entered start time and edit it to invalid time e.g.` 00:00 AM`
4. Click on the Save button
5. It throws an error

**Expected behavior**
Time should only be updated by clicking on the clock icon which ensures the time entered is valid

**Screenshots**
![image](https://user-images.githubusercontent.com/40158831/147723995-add074ce-0e33-4a77-800f-fffa9558754e.png)

**Comment by abhi1203** [comment]
@mdshamoon essentially, open that time popup on clicking the entire block not just the icon.
