### ISSUE TITLE
Default Flow: UI enhancements

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1811]
**Is your feature request related to a problem? Please describe.**
In the Organization setting for default flow to set default flow to be active for 24hrs, one uses time as `12:01 AM` to `11:59 PM` which works, but can we add an option to make it all-day

**Describe the solution you'd like**
After selecting the flow as the default option we can set 2 options
**1.** `set time` and `all day` with `all day` as the default option.

**2(a)** If the user select `set time` we give the option to enter `start time` and `end time` 

**2(b)** If the user select `all day` we don't give any  option

**Screenshot**
![image](https://user-images.githubusercontent.com/40158831/147724429-64159b16-ebd1-4418-8d19-c41a23e6f252.png)

**Comment by abhi1203** [comment]
Maybe we can update it to this flow: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/v/Z4oe3J/a/R1d4R48/play/
