### ISSUE TITLE
Collections: screen refresh after delete

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1812]
**Describe the bug**
Once a collection is deleted, the message pops up that collection is deleted successfully yet the deleted collection still appears in the screen and needs to refresh the screen.

**To Reproduce**
1. Go to Collection screen
2. Create a collection
3. Search the newly created collection and click on the delete button
4. Message pops up that collection is deleted successfully yet the deleted collection appears on the screen 

**Expected behavior**
Once deleted the screen should refresh with the deleted collection not showing

**Screenshots**
![image](https://user-images.githubusercontent.com/40158831/147724903-fdfd96db-73d1-4c38-a81b-4e35971aaf68.png)

**Comment by mdshamoon** [comment]
Duplicate of #1717. @AkhileshNegi we have added a fix for this and it should be there in the latest master as well as on staging.
