### ISSUE TITLE
Messages are not loading for some contacts. even after refreshes the pages

### ISSUE THREAD

**Issue by wevekamola** [glific/glific-frontend#1816]
(https://docs.google.com/document/d/1RSd3-HkEb9F5WLq6HyWWi2_aLIujESJxc_eVJHuZ-HU/edit)

User from Mukkamar, was not having messages shown in chat screen.

User - BaskarSangita38

**Comment by wevekamola** [comment]
<img width="691" alt="Screenshot 2022-01-04 at 1 19 30 PM" src="https://user-images.githubusercontent.com/29367838/148028615-300a9636-1d8a-4265-b8fc-eb9d23b8b672.png">

<img width="702" alt="Screenshot 2022-01-04 at 1 19 20 PM" src="https://user-images.githubusercontent.com/29367838/148028642-3bf3927e-ac9c-4901-9b3c-1e047a210bc0.png">

<img width="654" alt="Screenshot 2022-01-04 at 1 18 32 PM" src="https://user-images.githubusercontent.com/29367838/148028650-1cb24494-076d-4511-9372-8b241c9a1d60.png">

**Comment by mdshamoon** [comment]
@wevekamola are you able to replicate the issues in the document on the mukkamaar system?

**Comment by mdshamoon** [comment]
Closing the issue since it's not replicable.
