### ISSUE TITLE
Flow editor - Arrow in top end hides under the node

### ISSUE THREAD

**Issue by wevekamola** [glific/glific-frontend#1817]
While on call with Mukkamar, While editing the flow, the top arrow was hidden below the node.

Tried to delete the arrow and create it again. But it again gets hidden under the node.

**Comment by mdshamoon** [comment]
@wevekamola can you share any screenshots or replication steps to debug this further.

**Comment by mdshamoon** [comment]
This may be an issue in floweditor and we have less control over that. Will come back to it if it happens again. For now closing it.
