### ISSUE TITLE
Selected language is not clear

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1822]
**Describe the bug**
On interactive msg screen it's not clear which is the selected language

**Expected behavior**
The selected language should show in darker color without underline

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/148201462-fee563f8-c771-484d-91d2-4277b376c85f.png)
should be like this
![image](https://user-images.githubusercontent.com/16714604/148211379-158a66b2-a631-4b99-80e8-69018c18f357.png)

**Comment by mdshamoon** [comment]
@abhi1203 I checked this case and someone made this interactive message in Bengali and disabled that language from organization settings. Please let me know what should be done in this case.

**Comment by abhi1203** [comment]
Okay we don't need to worry about that then. closing
