### ISSUE TITLE
HSM should be mandatory in Send Broadcast messages 

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1824]
**Is your feature request related to a problem? Please describe.**
NGO staff members cannot be in the session window all the time to receive session messages.
If a staff member is not in the session window, the flow gets to stops and doesn't execute after send sending the next message.

**Describe the solution you'd like**
Making HSM template mandatory will avoid issues related to stoping flow execution in between and causing confusion to NGO users.

**Comment by pankaj-ag** [comment]
This is not urgent. Just transferring the issue since it's related to frontend only.

**Comment by mdshamoon** [comment]
We are going with hiding the session message box and adding a message in that place to select template from WhatsApp tab
