### ISSUE TITLE
Add WA trier to Glific

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1826]
https://www.gupshup.io/docs/partner/#jump-UsefulApis-App_7CCheckMessagingTier

Add label for `High`, `Medium`, `Low`, `Flagged`, `Restricted` like its mentioned here: https://www.facebook.com/business/help/896873687365001

**Comment by kurund** [comment]
@abhi1203 

Looks like this is good to have.  Should we close this and come back when we need?

**Comment by mdshamoon** [comment]
@abhi1203 need your inputs on this issue

**Comment by abhi1203** [comment]
This is more than good to have now :) TAP faced an issue with this. but i think we need to clarify the requirements bbased on what information we're receiving from gupshup and what we can add on Glific

**Comment by kurund** [comment]
@abhi1203 

Can you please provide a mockup for this?

**Comment by mdshamoon** [comment]
@abhi1203 we get the following information from the API response 

<img width="997" alt="image" src="https://user-images.githubusercontent.com/32592458/185836732-e104bfdb-3701-4c88-af6a-a685058be0a9.png">

Let me know if we can work out something with this. Possibly show the tier on the UI and pointing to documentation that explains each tier.

**Comment by kurund** [comment]
@abhi1203 @mdshamoon 

As I understand we don't get a WA rating from API, so should we close this?

**Comment by abhi1203** [comment]
@kurund i think the idea is to only show the tier limit for the WABA

**Comment by kurund** [comment]
@abhi1203 

Ok great, I have updated the issue title. Do you want to mockup how it needs to display in the UI?

**Comment by kurund** [comment]
@abhi1203

Any update on this?

**Comment by mdshamoon** [comment]
We should have a separate organization details page where we can show this information along with :

- Orgnization name
- Organization phone
- Current tier
- Total contacts 
- Total messages sent so far
- Messages sent this month
- The stuff we store in NGO stats we should have on this screen.
