### ISSUE TITLE
Disable edit option for contact name on contact profile page

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1833]
**Describe the task**
Disable edit option for contact name on the contact profile page

**Expected behavior**
Edit option should be disabled since we don't allow the name to change.

**Comment by mohitsharma-22** [comment]
<img width="541" alt="Screenshot 2022-01-07 at 12 35 47 PM" src="https://user-images.githubusercontent.com/16541548/148505387-f508a8bb-22bc-4c7c-906b-85617c375ce9.png">

**Comment by kurund** [comment]
@mohitsharma-22 

Your screenshot indicates logged in user profile update which is different from Contact Profile. Can you please clarify?

**Comment by mohitsharma-22** [comment]
@kurund My Bad.
Below is the screenshot.
<img width="589" alt="Screenshot 2022-01-14 at 6 52 05 PM" src="https://user-images.githubusercontent.com/16541548/149522019-ac87543e-7a79-40bc-9f1e-d54102ba54c5.png">
.

**Comment by kurund** [comment]
@mohitsharma-22 

Thank you
