### ISSUE TITLE
New Contact: Setting new contact flow from organization setting

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1840]
**Is your feature request related to a problem? Please describe.**
Add ability to update new contact flow from UI with regard to new changes from the backend.
[API documentations](https://github.com/glific/glific/blob/master/api.docs/includes/_organizations.md)

**Describe the solution you'd like**
As with the new changes from the backend a separate flow-id can be set for organization for new contact as oppose to prior version where the flow with keyword as `newcontact` was set as new contact flow

**Comment by abhi1203** [comment]
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/nRoRPo4

**Comment by enigmaticmahesh** [comment]
@AkhileshNegi  Can we add a is_pinned column in the flows table as a boolean. so, we can sort it using this key. Whenever we set the new contact in the organization settings page, we can change it as is_pinned to true.

**Comment by kurund** [comment]
@abhi1203 

We thought that at some point we might want to add a `Pin` action for the listing that will allow users to `Pin` the flows. Considering this I was wondering if it makes sense to move the display of the `Pin` icon into a separate column. This will also enable users to sort by pinned flows. 

I also feel we should avoid linking the pin icons to the organization screen to prevent confusion about this functionality considering the possibility of generalizing this for other entities in the future.

Let me know your thoughts on the same.

**Comment by kurund** [comment]
Here is how it will look.
<img width="1547" alt="Screenshot 2022-07-31 at 20 52 57" src="https://user-images.githubusercontent.com/151481/182042920-7b10f38a-5e97-4ec7-9a74-5cc676a94bf9.png">

**Comment by abhi1203** [comment]
> I also feel we should avoid linking the pin icons to the organization screen to prevent confusion

@kurund what do you mean by this? 
okay, agreed with your approach for pin in a column. ill update the design and give final file.

**Comment by kurund** [comment]
@abhi1203 

> I also feel we should avoid linking the pin icons to the organization screen to prevent confusion
> 
> @kurund what do you mean by this?

I meant there won't be any linking for the pin icon.

> okay, agreed with your approach for pin in a column. ill update the design and give final file.

Thanks.

**Comment by abhi1203** [comment]
Okay @kurund 

also sharing the design update : https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/nRoRPo4

for pinning i've added another option in Edit screen `Is pinned?` https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/8EOgRR

let me know if this works.

**Comment by kurund** [comment]
Yes, thank's perfect.

I have filed a separate issue for the Edit screen: https://github.com/glific/glific-frontend/issues/2096
