### ISSUE TITLE
Interactive Message: Warning when deleting interactive message

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1873]
**Is your feature request related to a problem? Please describe.**
As interactive messages are easy to delete, unlike HSM templates when deleting an interactive message we can give a warning message if it is used in some other flow as the flow does not progress if the node having an interactive message is deleted

**Describe the solution you'd like**
An error warning before deleting the interactive message which is already used in another flow

**Comment by kurund** [comment]
@AkhileshNegi 

Do we have an API that will give the list of flows where an interactive message is used?

**Comment by mdshamoon** [comment]
@AkhileshNegi updating the floweditor for interactive message changes : https://github.com/glific/glific-frontend/issues/1929 and https://github.com/glific/glific-frontend/issues/1894

If the template is deleted then we will show the node like this
<img width="341" alt="image" src="https://user-images.githubusercontent.com/32592458/156122528-a458cf74-8076-4217-bcce-aa67c3a67c93.png">

Let me know if this can solve the current issue.

**Comment by AkhileshNegi** [comment]
I think @mdshamoon the issue is more around preventing the deletion of interactive template if its used in other flow so we can prevent errors in a published flow.
The solution you are providing is after the interactive template is deleted with no option to revert to previous state when flow was working before interactive template got deleted.
This is the good enhancement though and you can create a separate issue for same

**Comment by kurund** [comment]
We can come back to this once the API is available.
