### ISSUE TITLE
Glific is not allowing user to login on older version of browsers.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1887]
**Describe the bug**
Creating this ticket at the request of the tech team to track it. One NGO user is not able to log in with the older version of browser.

**Screenshots**

<img width="491" alt="Screenshot 2022-02-01 at 5 12 48 PM" src="https://user-images.githubusercontent.com/16541548/151981495-51058ec4-1574-40bd-892e-e39ef5d962da.png">

<img width="263" alt="Screenshot 2022-02-01 at 5 12 17 PM" src="https://user-images.githubusercontent.com/16541548/151981582-2296919a-c18b-4177-9257-1669531918a2.png">

<img width="730" alt="Screenshot 2022-02-01 at 5 09 54 PM" src="https://user-images.githubusercontent.com/16541548/151981529-9cc95b09-d283-4f0e-8bde-a3f0f5307e8b.png">

**Comment by mdshamoon** [comment]
Tested in old browsers and there is nothing we can fix here.
We can ask the NGO user to upgrade their system.
