### ISSUE TITLE
Flow: Publishing empty flow

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1889]
**Describe the bug**
When publishing an empty flow throws an error and the screen freezes.

**To Reproduce**
1. Create a new flow
2. Click on publish button 
3. Click on any option `Publish & Stay` or `Publish & go back`

**Expected behavior**
Empty flow should send a warning that flow contains no node similar to other flow validation errors without option to `Publish`

**Screenshots**
Sample screenshot of warning when publishing invalid flow
![image](https://user-images.githubusercontent.com/40158831/152101281-ad25f229-e925-4e78-a3aa-834de23e957b.png)

**Comment by mdshamoon** [comment]
As discussed we will divide the flow errors in two categories: Critical and warning

Critical: Should not be allowed to save the flow
Warning: Can publish flow but still show warnings

**Comment by kurund** [comment]
@mdshamoon @AkhileshNegi 

Tested current behaviour and it does not throw a fatal error. I feel it's good enough for now. Ideally, empty flows should not be published :)
