### ISSUE TITLE
Pricing update

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1893]
**Describe the task**
Change the pricing to:
![image](https://user-images.githubusercontent.com/16714604/152319230-f549672a-4b05-4223-95c4-ea6d356d0e17.png)
business initiated conversation link: https://developers.facebook.com/docs/whatsapp/pricing

Cost calculator to be changed to this:
![image](https://user-images.githubusercontent.com/16714604/152319206-1ffd427c-7ff8-4bda-851a-587dbe19bdaf.png)

**Comment by mdshamoon** [comment]
Moved this the tides repo https://github.com/ProjectTides/tides-web/issues/49
