### ISSUE TITLE
Glific location

### ISSUE THREAD

**Issue by amitpallath** [glific/glific-frontend#1904]
Has the support of location in the simulator of the Glific chatbot.

**Comment by mdshamoon** [comment]
Design file link: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/QbZEdj7

**Comment by abhi1203** [comment]
seems to be working fine
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/16714604/153205920-6b1066e2-eb57-4f5b-b840-cc51dc5a6a5e.png">
