### ISSUE TITLE
Floweditor: Split by expression not saving deleted conditions

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1912]
**Describe the bug**
When creating a flow with node `Split by Expression` while adding multiple conditions and then removing created one is not getting saved. 

**To Reproduce**
1. Create a flow with node `Split by Expression`
2. Add a few conditions as shown in the screenshot
3. Click on OK button
4. Edit the same node
5. Remove one of the conditions and click on `OK` button
6. The removed node reappears

**Expected behavior**
Adding and removing conditions in `Split by Expression` node should be saved once click on `OK` button

**Screenshots**
<img width="525" alt="image" src="https://user-images.githubusercontent.com/40158831/153550320-009db9e7-451a-4786-91b5-4f7d6f071da0.png">

**Comment by mdshamoon** [comment]
Its an issue with floweditor. 
Seems like they fixed it in the latest version https://github.com/nyaruka/floweditor/blob/main/CHANGELOG.md#v1170.
Need to update floweditor to fix this.
