### ISSUE TITLE
Low wallet / Rate limit errors

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1916]
**Describe the bug**
We need to show an error when conversations get suspended due to very low wallet amount and when the rate limit is reached

When the wallet balance is <$1: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/8y7W58q
When the wallet hits 0: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/MyPlnoQ
When the rate limit is reached: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/bg5AKz5

**Comment by kurund** [comment]
@AkhileshNegi @pankaj-ag 

> When the rate limit is reached: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/bg5AKz5
Can we use the existing endpoint for this?

**Comment by mdshamoon** [comment]
@pankaj-ag I don't think we get information from gupshup when the rate limit is reached. Is there any way we can get that information when the rate limit is reached.

**Comment by pankaj-ag** [comment]
@mdshamoon rate limit we need to calculate from our side but to do that we need to start storing the conversation details. 
We can hold this issue for now.

**Comment by mdshamoon** [comment]
> @mdshamoon rate limit we need to calculate from our side but to do that we need to start storing the conversation details. We can hold this issue for now.

Okay. Keeping it on hold for now.

**Comment by kurund** [comment]
@pankaj-ag  @mdshamoon 

I am closing this issue. We can add a new issue if and when a new API is implemented.
