### ISSUE TITLE
Collections: Show members in a collection

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1917]
**Is your feature request related to a problem? Please describe.**
The number of members in a collection is not visible unless one opens the collection to check. Therefore figuring out total members in a collection or if  collection is empty is difficult

**Describe the solution you'd like**
Add collection members count in the list screen

**Screenshots**
<img width="403" alt="image" src="https://user-images.githubusercontent.com/40158831/154082810-09a88962-4e96-41c5-84c3-629290d9e307.png">

**Comment by kurund** [comment]
@AkhileshNegi 

Is there an endpoint that we can use for this?

**Comment by mdshamoon** [comment]
Design file link: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/KdvdVn

**Comment by mdshamoon** [comment]
@kurund we have the field userCount in the groups API
