### ISSUE TITLE
Collections: Add a new member 

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1918]
**Is your feature request related to a problem? Please describe.**
There is no option to add a new member after opening Collection specific screen which raises the issue if someone after opening the collection find out that there are no members or there is some member

**Describe the solution you'd like**
Ability to add new members after specific collection is opened

**Screenshot**
<img width="833" alt="image" src="https://user-images.githubusercontent.com/40158831/154083155-e4279819-a626-4236-8d38-2879c0961ded.png">

**Comment by kurund** [comment]
@AkhileshNegi 

I am closing this after discussion with @mdshamoon
