### ISSUE TITLE
Incorrect message shows while starting a flow from collection

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1922]

**Comment by mohitsharma-22** [comment]
TAP reported an issue for confusion of message.

![Message](https://user-images.githubusercontent.com/16541548/154497396-d10c990a-d28f-448e-a537-e7018dd64f6e.png)

**Comment by abhi1203** [comment]
@mdshamoon what about: `Your flow will be sent in a couple of minutes.`

**Comment by mdshamoon** [comment]
Can we change this to- 
`Your flow will start in a couple of minutes.` or `Your messages will be sent in a couple of minutes.`
because flow will be sent doesn't make much sense to me. Let me know your thoughts
