### ISSUE TITLE
User does not understand what to do in case the category is not needed in wait for response

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1936]
**Describe the task**
User does not understand what to do in case the category is not needed in wait for response and the question is an open ended question. since there is an option of category the user tries to add a category.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/32592458/155129172-cf1d6c3a-9f35-4a41-9f39-ab6ac877518a.png">

**Expected behavior**
User should be aware that if no category is put then it will accept all responses. Maybe we can add some text saying:
`For getting all responses leave the categories empty`

**References**
Specify any reference material / links

**Comment by abhi1203** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/16714604/155133929-3c66bb46-35ef-4430-96a9-c3abf0fa6367.png">
We can go ahead with this UI and the following messages:
Sorry! Connection to server failed. Please refresh page to continue working.
Sorry! Unable to show live messages. Please refresh page.

**Comment by mdshamoon** [comment]
Closing since this is not needed for now.
