### ISSUE TITLE
Error while adding emojis in interactive list title

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1947]
Adding details of error received today while testing.

<img width="862" alt="Screenshot 2022-03-02 at 12 35 02 PM" src="https://user-images.githubusercontent.com/16541548/156312104-bb799116-de19-4839-b588-c7dc924375f7.png">

_Originally posted by @mohitsharma-22 in https://github.com/glific/glific/issues/2092#issuecomment-1056418335_

**Comment by kurund** [comment]
@mdshamoon 

Can you please update the issue with more info? Let's chat during our catch up.

**Comment by mdshamoon** [comment]
WhatsApp does not allow emoji's in the interactive list option title. We need to add validation for not putting emoji's in the list item title 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/32592458/158739798-1e71c2bf-06b6-4f1b-ae45-b86bce71dc44.png">

**Comment by kurund** [comment]
@mdshamoon 

It's tricky to validate emoticons, as we need to allow Unicode characters for localisation. For now, I have added helper text.

![Screenshot 2022-03-27 at 7 27 32 PM](https://user-images.githubusercontent.com/151481/160295333-1626dd66-cc77-4d57-895e-26bdc1566ef9.jpg)
