### ISSUE TITLE
Incorrect validation error for call to action phone number

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#1948]
**Describe the bug**
Incorrect validation error for call to action phone number

**To Reproduce**
1. Go to template creation screen
2. Create a call to action phone number template with only 10 digit phone number

**Expected behavior**
It should have correct validation error

**Screenshots**
<img width="588" alt="image" src="https://user-images.githubusercontent.com/32592458/156356349-fd886086-7c2b-436f-b1a6-f523a979168b.png">

**Comment by kurund** [comment]
@mdshamoon 

I feel we should allow 10 or 12 digits when the country code is entered. 

Thoughts?

**Comment by kurund** [comment]
Added check if the phone is between 10-12 digits.
