### ISSUE TITLE
Templates: UI enhancements

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1958]
**Describe the solution you'd like**
Gupshup enterprise provide a similar format to apply for templates from UI, there are a few areas we can use a similar approach as an enhancement

**Details**

1. Adding option to add variable when entering message text instead of manually entering `{{variable_no}}` add option to add a variable which will add `{{variable_no}}` in the text based on the variables already present. 
e.g. if one variable is already defined the clicking button second time will add `{{2}}` in the text
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/40158831/157644728-63889464-ebd5-416d-88bd-722c3d5c1ac8.png">

2. For sample text, add variable values which will be replaced in the original body and create sample text automatically
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/40158831/157645413-857945fe-6661-4615-ac7d-822ffce2c218.png">

3. In case of media template the sample section will have option to add sample media file as well
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/40158831/157645552-1dd08101-71bd-45c3-8c4d-a529bb3d499f.png">

**Comment by abhi1203** [comment]
@mdshamoon i'm thinking of the update this way: https://www.figma.com/file/SEWpT6NLTjwH2W6PrRdFvq/Glific%2FApp?node-id=49%3A45259&t=WD2TByQ8fd01tvUl-4

Let me know if you have any suggestions or questions.

**Comment by mdshamoon** [comment]
We should probably do this after draft-js [migration](https://github.com/glific/glific-frontend/issues/2334). Otherwise we need to change this implementation as well.

**Comment by mahajantejas** [comment]
similar issues -https://github.com/glific/glific-frontend/issues/2740

**Comment by mahajantejas** [comment]
Closing this issue, because we need updated designs for the "applying template" page. the designs to communicate easier way (similar to how it is done in gupshup) to apply for new templates.
