### ISSUE TITLE
Error while filling out the organisation registration form

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1970]
**Describe the bug**
Users are getting an error while submitting the form. But the system is recording their entry.

**To Reproduce**
While on the call, the user simply filled out the form by copy pasting the details. When they tried to submit they got an error as shown in the snapshot but on the backend the entry was captured.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/159237482-dc7a2a8f-b3d9-43e2-aa2e-bfb908053d9e.png)

**Comment by mdshamoon** [comment]
Tried to replicate on local but not able to replicate.
There may be issues with v2 of Google captcha. Will update it to v3

**Comment by abhi1203** [comment]
@mdshamoon someone again reported that it's not working. Please look into this on priority.

**Comment by mdshamoon** [comment]
@abhi1203 we have deployed a fix. Let us know if you are still facing this issue.
