### ISSUE TITLE
Back ground of images are turning black when sent from Glific

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2021]
<img width="407" alt="Screenshot 2022-04-12 at 4 14 51 PM" src="https://user-images.githubusercontent.com/16541548/162943534-8b579d4e-1502-48be-a681-0c29fa38a424.png">

<img width="441" alt="Screenshot 2022-04-12 at 4 14 43 PM" src="https://user-images.githubusercontent.com/16541548/162943546-c3c82dbf-205e-4553-a045-d39e46fc8471.png">

It is not changing when the image is sent directly. or forwarded directly from WhatsApp.
<img width="417" alt="Screenshot 2022-04-12 at 4 15 06 PM" src="https://user-images.githubusercontent.com/16541548/162943568-17aac609-7dbe-429b-a787-d05afca92ee5.png">

**Comment by mdshamoon** [comment]
@mohitsharma-22 since these are transparent png images it is automatically converted by WhatsApp as black background. We can't do anything in this case.

Possible solutions could be:
- Add white background to image
- Convert the png image to jpg which does not support transparency
