### ISSUE TITLE
NGO Dashboard

### ISSUE THREAD

**Issue by Ranjana-G** [glific/glific-frontend#2032]
On the daily status page - we should add a graph that shows daily new opt-ins. ( Takeaway from talk with Robert yesterday) 

It will be useful to track new acquisitions at an NGO level. So we know if conversations are largely happening with existing contact or whether the NGO is actively extending its reach

**Comment by Ranjana-G** [comment]
If I am given access - I can take a shot at building the query myself ! :)

**Comment by mdshamoon** [comment]
@Ranjana-G I have added the daily optin and optout section in the daily status page. Let me know if it works for you
