### ISSUE TITLE
Screen freezes while seeing revision history

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2057]
**Describe the bug**
When seeing the revision history, the screen freezes and i can't scroll to see the nodes below

**To Reproduce**
1. Click on revision history button
2. Select one time stamp

**Expected behavior**
IT should allow me to scroll to see other nodes

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16714604/167393747-a16a0e24-5efc-4f84-9304-0db4582064bb.png">

**Comment by mdshamoon** [comment]
Checked this on RapidPro. It has the same behaviour. Creating an issue in floweditor if they can have a look.

**Comment by mdshamoon** [comment]
Will reopen in case they check on this issue.
