### ISSUE TITLE
Contact list in message are not in chronological order

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2059]
<img width="527" alt="Screenshot_2022-05-12_at_12 25 15_AM" src="https://user-images.githubusercontent.com/16541548/168011547-5661bc05-7ba8-4d81-b73d-793964c6b931.png">

<img width="521" alt="Screenshot_2022-05-12_at_12 22 52_AM" src="https://user-images.githubusercontent.com/16541548/168011563-259b15f7-ff3a-4d0c-aa43-f4f8987e24bf.png">

<img width="756" alt="Contacts-results" src="https://user-images.githubusercontent.com/16541548/168011569-63f6a987-cd81-4c6a-9253-d2d51805466e.png">

**Comment by mdshamoon** [comment]
Based on my findings the issue happens when you search for a contact. Click on it and then move back to `All` tabs. Now when you load more the searched elements get stuck at the bottom. Will fix this soon.
