### ISSUE TITLE
Session window learn more link is broken

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2074]
The link is given in the tooltip box "Learn more about session window here" is broken http://gilfic.org/session-window/

![Image](https://user-images.githubusercontent.com/16541548/173519325-b4215eba-3058-4a94-bc86-cb9a3fa52c94.png)

**Comment by mdshamoon** [comment]
@mohitsharma-22 I am not able to replicate the issue. Can you please check if it is still not working for you?
