### ISSUE TITLE
DavaVidya - DialogFlow report request - need to close this week [URGENT]

### ISSUE THREAD

**Issue by Ranjana-G** [glific/glific-frontend#2095]
Shamoon, 

After our 22nd July meeting I tested the DanaVidya Bot  with labels added . Here is the report. 

https://docs.google.com/spreadsheets/d/1mOuzc_-qrQ8YxUBQUbzv7x35kCnAp3dJ9xTVF_utAIY/edit#gid=0

1) The add label right after split by intent shows the "raw" , "hard to read intent" coming from DialogFlow. It is associated with the Question in the report. 
2) The label in send message following split by intent  is categorized as per the intent node into more readable words that I have used. It is associated with the Answer in the report. 

It would be so great if there could be a single report that has 3 column in every row 
1) Question 
2) Answer 
3) Readable Intent. 

Hope that's clear else we can get on a call today. I am hoping for a solution by EOD tomorrow - 28th so we can close Danavidya this week ! 

P.S. Davavidya URL - https://danavidya.tides.coloredcow.com/; Flow name "FAQs"

**Comment by mdshamoon** [comment]
@Ranjana-G this is done right. Should we close this issue?

**Comment by Ranjana-G** [comment]
@mdshamoon  But this issue is not fixed. Even if not for Dana-vidya we should fix this so that we can promote the FAQs feature more aggressively. It is really a very cost effective way of getting started for many NGOs.  what does @abhi1203 think as product manager ?

**Comment by abhi1203** [comment]
Agreed, if it's done for DV. Video volunteers also asked for it and we built it for them. it makes sense to move it to DataStudio template report.

**Comment by mdshamoon** [comment]
Closing this as this issue is mentioned on discord. Will reopen once we start working on it.
