### ISSUE TITLE
Mobile enhancements | Babynama

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2100]
**Describe the bug**

- [ ] Didn’t know how to open other chats (clicking on the top right chat button). we need to find a more intuitive way like open all the chat list upfront after that staff can select to go into individual chat
<img width="367" alt="image" src="https://user-images.githubusercontent.com/16714604/182869682-964c2be6-ed25-42d3-a744-ba0d208c8cc9.png">

- [ ] New chat opens on its own on the chat view and removes the previous chat while the user is typing
- [ ] Make all the chats the default view
- [ ] recheck Not replied and Unread list of contacts. for babynama, not replied was also showing unread chats.
- [ ] Issue while typing. Users might end up clicking on mic or other icons because the icons are too close to each other.
<img width="369" alt="image" src="https://user-images.githubusercontent.com/16714604/182870834-fad01ad6-78aa-436b-9548-d43cd2ca715b.png">

- [ ] Unable to enter a line break on mobile browser. With enter button the message gets sent.
- [ ] Login again and again. Need more than 30mins. On mobile it gets really difficult and needs longer time.
- [ ] Chat not opening on clicking the name after search
<img width="386" alt="image" src="https://user-images.githubusercontent.com/16714604/182871009-3e614de4-cbdd-41ff-a46f-de6d1435a9d4.png">

- [ ] For contacts for whom 24 hours window closed - don’t allow typing the text.
- [ ] Complete message not getting sent. Note how the user types mno at the end but didn't get sent.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/16714604/182871154-64ddaf4e-9d3e-4cce-857b-8ab691cadf40.png">

[Document](https://docs.google.com/document/d/1ArCTIW97fa-sE-ZvguhmhhDrYBg5IqCQJceW3FRXSQs/edit)

**Comment by mdshamoon** [comment]
On small screens it overlaps
<img width="651" alt="image" src="https://user-images.githubusercontent.com/32592458/223347614-e77eacee-1c7b-4ee1-be12-603e47527c76.png">

Jump to latest moves down on smaller screens
<img width="540" alt="image" src="https://user-images.githubusercontent.com/32592458/223347803-01691b3d-fd03-4c05-80ea-a912379e016f.png">
