### ISSUE TITLE
Add an ability to use speed sends and templates for replying to the conversation

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#211]
**Is your feature request related to a problem? Please describe.**
* User should be able to select speed sends or templates while reply to the conversation.

**Describe the solution you'd like**
* Add button on top of chat input for selecting "Speed sends" and "Templates"
* User can click on any of the options i.e "Speed sends" or "Templates". After clicking user should be able to filter the message by entering keywords in the chat input.
* This will display the results matching entered criteria and the user can click on the result that will set the chat input area with the selected message.

**Additional context**
* UI Design: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/4J0jPZ

**Comment by claalmve** [comment]
- Test cases
