### ISSUE TITLE
Fix issue with staff member having no roles

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2113]
**Describe the task**
Add a check that should allow to open the page even if the user has no role

To replicate try to edit the staff named NGO admin and it will give an error.

**Expected behavior**
There should be no error

**References**
![image](https://user-images.githubusercontent.com/32592458/184877454-fb1b0b87-e774-41cb-a189-3ee6db4a2558.png)

**Comment by mdshamoon** [comment]
Additonal issue when you add a collection for a staff member it removes their role.

**Comment by kurund** [comment]
> Another issue related to this is when you add a collection for a staff member it removes their role.

I am not able to replicate this.
