### ISSUE TITLE
Branding - Change whatsapp chatbot profile image from coloredcow logo to glific logo

### ISSUE THREAD

**Issue by Ranjana-G** [glific/glific-frontend#2123]
**Describe the task**
Change chatbot whatsapp profile image from coloredcow logo to glific logo
That way out chatbot shows up in the users whatsapp contact list as belonging to Glific. 

Slab documentation states this needs to be done in the Gupshup account for which I have no access. Hoping Abhishek can take it up.

**References**
[Specify any reference material / links
](https://glific.slab.com/public/posts/05-update-my-profile-picture-of-bot-922awlv8)

**Comment by pankaj-ag** [comment]
Done, but i can't change display name from ColoredCow because we got this app approved using ColoredCow facebook page.

**Comment by abhi1203** [comment]
Done, but i can't change display name from ColoredCow because we got this app approved using ColoredCow facebook page.

**Comment by pankaj-ag** [comment]
@Ranjana-G we are closing this issue. Please reopen if you have anything on that pending.
