### ISSUE TITLE
Dashboard Template 4.0 improvement requests

### ISSUE THREAD

**Issue by Ranjana-G** [glific/glific-frontend#2129]
This these are minor issues in the template I am opening a single bug for all. These were requested by Deshpande Foundation.
1. In the user in flows page - Can the user name be shown in the table for incomplete complete and expired flows  - ecan it be done via drilling down into the number in last column ? 
2. There is a report "Contacts asked for an activity (based on flow labels)" - can we base it on registration so it is relatable to all NGOs.

**Comment by mdshamoon** [comment]
Closing this as this issue is mentioned on discord. Will reopen once we start working on it.
