### ISSUE TITLE
Staff should not be able to see collections that are not assigned to it

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2150]
**Describe the task**
Right now if we assign a role as staff to a user it shows all the collections to that user. It should show only assigned collections to the staff member.

**Expected behavior**
A staff member should be shown only the collections assigned to them.

**Comment by kurund** [comment]
@mdshamoon 

Can you please recheck this.

**Comment by mdshamoon** [comment]
I tested it out and it seems to be working fine. Closing the issue.
