### ISSUE TITLE
Give an option to a glific user to bulk update contacts

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2155]
**Describe the task**
Based on this [issue](https://github.com/glific/glific/issues/2452) we need to create a UI for the glific user to update contacts

**Comment by abhi1203** [comment]
Here are the two screens required for this:

https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/m143mqz

https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/DPj3yqq

let me know if there are any questions
