### ISSUE TITLE
Profiles: Add support to delete Profile

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2157]
**Is your feature request related to a problem? Please describe.**
Currently in contact profile we only have option to remove a contact which deletes contact along with profiles. For organizations using multiple profiles there should be an option to delete a profile a profile as well

<img width="946" alt="image" src="https://user-images.githubusercontent.com/40158831/191902877-c9deb70e-a92e-4d16-bae3-a5c7e7b0a44c.png">

**Additional Context**
There is already an API in backend for deleting profile. Check it out [here](https://github.com/glific/glific/blob/master/api.docs/includes/_profiles.md#delete-a-profile)

**Comment by abhi1203** [comment]
I'm thinking we can just delete the currently selected user and we can show a confirmation modal to show the user they are going to be deleting:

https://www.figma.com/file/SEWpT6NLTjwH2W6PrRdFvq/Glific%2FApp?node-id=3%3A42359&t=ErTqGU2EBZRfZwox-4
