### ISSUE TITLE
Not able to add emoji's in whatsapp editor

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#216]
**Describe the bug**
* We should be able to include emoji's in the message. However, due to the new editor, it is not working.

**To Reproduce**
* Click on emoji picker and select an emoji. It should be added in the input. 
* Also emoji picker should be closed once it added.

**Expected behavior**
* We should be able to add emoji's and formatted text.

**Comment by claalmve** [comment]
- [] Include emojis

**Comment by claalmve** [comment]
https://github.com/draft-js-plugins/draft-js-plugins

**Comment by kurund** [comment]
Working as expected.
