### ISSUE TITLE
Fix dialog box UI issue

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2164]
**Describe the task**
The error description should be center aligned and have a fixed width
<img width="493" alt="Screenshot 2022-09-30 at 1 27 53 PM" src="https://user-images.githubusercontent.com/32592458/193221320-15bb105c-222b-4f5e-a222-2d7ca9267ce8.png">

**Comment by saminarp** [comment]
Hello @mdshamoon  I would like to work on this issue as part of `hacktoberfest`, I was able to run it locally using the scripts in `package.json` and finally `serve -s build/`. I would like to know how can I reproduce the screen you have shared above.

**Comment by mdshamoon** [comment]
@saminarp This issue will need a key to replicate. I can DM you the key on discord if interested. We also have some good first issues that you can pick. Please join our [discord](https://discord.gg/qqhVSrc5) channel if you want to contribute more and we can discuss further.

Sharing the steps to replicate on local:

1. Login with default credentials
2. Visit https://glific.test:3000/settings/bigquery

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/32592458/194247368-1f185826-52a4-489d-83cf-8faebdfcb1ff.png">

3. Add the key with insufficient permission
4. See error
