### ISSUE TITLE
Provide link from flows screen to edit interactive messages

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2168]
**Describe the task**
Right now while going through the flows, editing an interactive messages is a multi-step process. 

**Expected behavior**
It would be easier if we provided a quick link from the flows to edit interactive message screen.

Once we're ready to pick this up, I can add designs for this

**Comment by abhi1203** [comment]
we can do the same thing for HSM messages also?

**Comment by mdshamoon** [comment]
@abhi1203 you can't edit a template. Why would you need that?

**Comment by abhi1203** [comment]
Yea true. Maybe to debug like something is not working.
Maybe not the strongest case but can apply if someone needs it at any time and it's not a lot of work for us.

**Comment by kurund** [comment]
I am closing this as per the above conversation.
