### ISSUE TITLE
Change the HSM update button text

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2177]
Since users were facing a hicccup in finding the button `GET HSM UPDATES`. we can try changing the text to 
`SYNC HSM` 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/16714604/194499068-e5bc4fa5-c17c-4d97-be22-77d8aa4ed62a.png">

**Comment by batunpc** [comment]
Hello @mdshamoon I am investigating this :-)
