### ISSUE TITLE
Few updates for the settings screen

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2178]
1. Options on the settings page are increasing. Going into the page and trying to find a setting might get more time consuming as we add sheet integration and other options. For that, it might be good to provide a faster access to the options:

This list can show up on hovering over the settings icon similar to how it happens for the contact management icon. Clicking on the setting icon will still take users to the page with all the blocks.
<img width="533" alt="image" src="https://user-images.githubusercontent.com/16714604/194508269-6f12297b-bed0-49e3-84f5-85e1baf77563.png">

2. Make the entire block along with the text inside clickable instead of just the edit icon 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/16714604/194512041-a2a7e2ce-a7bb-4cf3-aeb3-bf476a802773.png">

**Comment by mdshamoon** [comment]
@abhi1203 

1. Making the settings icon both clickable and hover could create confusion when selecting. Let's keep it in a single state in my opinion. Making it in hover state would not allow us to show all option hence we should keep it clickable only.

2. Should we remove the edit icon if we are making the entire section clickable

**Comment by abhi1203** [comment]
@mdshamoon sure i'm okay with your opinions on 1. however we could make that list scrollable after hover - should we do that?

for 2. i think let it be - it's not harming any functionality or usability
