### ISSUE TITLE
Feedback on the conversation level report

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2179]
**Describe the bug**
There are minor errors on the report listed below:

1. It should be `Number of conversations` please check spelling
<img width="409" alt="image" src="https://user-images.githubusercontent.com/16714604/195047289-9964bf17-acd8-4c39-952f-7b31ab5b38d0.png">

2. Change to `Number of template messages sent:`, `Total messages sent:`, `Total messages received:`
<img width="461" alt="image" src="https://user-images.githubusercontent.com/16714604/195047335-0a606e94-6d5e-4df3-a68b-87430405953f.png">

3. the fonts don't scale evenly on the entire screen
<img width="979" alt="image" src="https://user-images.githubusercontent.com/16714604/195047581-9f9d4fe9-2bb0-4a40-a35b-6d397dea3954.png">

4. Change Total cost heading to `Conversation cost`
<img width="642" alt="image" src="https://user-images.githubusercontent.com/16714604/195047727-36d8ea7e-766c-4440-a7b9-261d808bb6d4.png">

5. Add currency here like $0.0066/BIC
<img width="360" alt="image" src="https://user-images.githubusercontent.com/16714604/195047869-7e6a35c9-8b49-4603-a138-226e8b84619b.png">

6. Can we keep the costs in Rupees or let users change between USD and Rupees?

7. We don't have a separate template message cost, it's just BIC or UIC cost. 
<img width="856" alt="image" src="https://user-images.githubusercontent.com/16714604/195048068-ed11a8f0-c2b0-426e-9e94-45a26c2ed87a.png">

8. Change this to `Outgoing session messages` and `Incoming session messages`
<img width="805" alt="image" src="https://user-images.githubusercontent.com/16714604/195048266-3048fe44-4648-4a62-8890-2e4d2a7c544f.png">

9. Change `Free First 1,000 conversations used per month` to `Free first 1,000 conversations per month`

10. Interchange the positioning of these blocks
<img width="918" alt="image" src="https://user-images.githubusercontent.com/16714604/195049029-7af0661c-7a2a-42ae-957a-c069e78b8460.png">

**Comment by AkhileshNegi** [comment]
@abhi1203 We have separate template message costs. Please refer this
https://www.gupshup.io/channels/self-serve/whatsapp/pricing
Also, you can check in Gupshup Partners portal for the total cost
For point 3, can you elaborate on scaling evenly
For point 4, It's is conversation + message cost
For point 6, All balance is shown in dollars per message cost and also wallet balance. Also, should we need to add the standard dollar to the rupee rate then

**Comment by abhi1203** [comment]
Yea, 
3. see the font size of dropdown and `number of conversations` it's too small compared to other. i will provide design guidelines later for this.
4. yea. messages is a part of it.
5. umm.. good question. Since the rate is fluctuating quite a bit i don't think we can keep it standard. will need it to be as per the current exchange and how gupshup charges

**Comment by mdshamoon** [comment]
@abhi1203 is this done or do we need anything on this?

**Comment by abhi1203** [comment]
I think it's clear now from my perspective.
for 5. it might be worth showing the current conversion rate and the cost as per current rate?
