### ISSUE TITLE
Add footer option in a quick reply interactive message

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2190]
**Describe the task**
Add footer option in a quick reply interactive message to allow users to set a small note at the end of the interactive message.
https://discord.com/channels/717975833226248303/780402199679336469/1030379312261648445

**Expected behavior**
We should be able to set a footer at the end of the interactive message which will appear in grey on WhatsApp
<img width="290" alt="image" src="https://user-images.githubusercontent.com/32592458/195791672-bec4749a-336a-487e-b400-8fb3fc103d1d.png">

**References**
[Specify any reference material / links](https://docs.gupshup.io/reference/msg#interactive---quick-reply-message)

**Comment by abhi1203** [comment]
@mdshamoon this is how im thinking of it.
https://www.figma.com/file/SEWpT6NLTjwH2W6PrRdFvq/Glific%2FApp?node-id=0%3A6397&t=WD2TByQ8fd01tvUl-4
