### ISSUE TITLE
DG Telangana Report issues

### ISSUE THREAD

**Issue by wevekamola** [glific/glific-frontend#2201]
- [x] In the **Overall** section please add, Farmers Completed Advisory. The number can be fetched from a collection **Telangana Farmers Completed Advisory**
     <img width="348" alt="Screenshot 2022-10-06 at 12 40 08 PM" src="https://user-images.githubusercontent.com/29367838/194248015-949e86f4-bf22-440c-a6d6-0949bdc02d0f.png">

- [x] In the **Flows** section the data seems to be incorrect, please check the query and validate the data as well.
        1. Currently the Total number of farmers is 22 but in both the graphs Active users in flows and completed flows are more than this.
        <img width="600" alt="Screenshot 2022-10-06 at 12 29 21 PM" src="https://user-images.githubusercontent.com/29367838/194248436-21eed757-19fe-4891-b697-2af695c0db03.png">
       <img width="600" alt="Screenshot 2022-10-06 at 12 29 08 PM" src="https://user-images.githubusercontent.com/29367838/194249119-069e5ac7-e322-429e-94fd-25957f742045.png">

- [x] In the **User Distribution** section the Madal graph is not showing any data, but in the contact field, the data is present.
    <img width="600" alt="Screenshot 2022-10-06 at 12 31 06 PM" src="https://user-images.githubusercontent.com/29367838/194249571-96b8d902-1cec-4232-a369-60ca93d01a2c.png">

- [x] In the **Messages** section the Chilli image data is not showing correct data, Please check the query.
   <img width="600" alt="Screenshot 2022-10-06 at 12 31 46 PM" src="https://user-images.githubusercontent.com/29367838/194249911-f07a2472-9df7-4296-a5a1-abf4da9d2082.png">

- [x] In the **Messages** section for the Adoption data response, please create a bar graph, in a pie chart large data will not be visualized correctly.
  <img width="600" alt="Screenshot 2022-10-06 at 12 32 02 PM" src="https://user-images.githubusercontent.com/29367838/194250369-d9e0a33a-6c52-4498-828d-ad8737d1c9ee.png">

- [x] In the **Crop Stage Distribution** we need to fetch data from the collection **Telangana Farmers has Advisory**, For example,  it's showing no crop stage data for a contact Mohan because the farmer has stopped the advisory.

<img width="500" alt="Screenshot 2022-10-06 at 12 37 07 PM" src="https://user-images.githubusercontent.com/29367838/194252410-84a4e069-5dbf-46ca-979d-2b46396243c7.png">

<img width="400" alt="Screenshot 2022-10-06 at 12 35 41 PM" src="https://user-images.githubusercontent.com/29367838/194252471-e6dec597-046b-4d1e-b20e-73c0665dfe85.png">

Also please fix the **Mandal** data as well and also add the **Crop Age** data

**Comment by mdshamoon** [comment]
Closing this issue since all are fixed.
