### ISSUE TITLE
Add news, announcements, and other information section on the login screen

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2202]
**Is your feature request related to a problem? Please describe.**
We need the ability to share new information to our NGO partners. One of the touchpoints is when the are about to login to Glific. 

**Describe the solution you'd like**
It would be great to have a section on the login screen which can allow Glific admin to customise and share relevant information to the Glific NGOs
We will start with showing the referral campaign which can would be shareable on social media and whatsapp.

**Comment by mdshamoon** [comment]
Design file link: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/v/GbzEVw/p/45649014-4047-403E-8216-5F8252362334/canvas?posX=-4575.65771484375&posY=-4254.92724609375&zoom=0.6005512475967407

**Comment by abhi1203** [comment]
1. please remove the backgrounnd from the `Gift card` and joy of giving text
<img width="313" alt="image" src="https://user-images.githubusercontent.com/16714604/199677390-4309d992-0a83-4ed2-8e3f-4d4cee7ed25b.png">

2. please check all the vertical spacing also like above Share now 

3. Check the total width of the promotions block
4. change the joy of giving font
5. red color of new nd dot are not the same. please keep the color of dot same as the text
6. we need to change the whtasapp message: keep it "Hey! Here's a gift card for 1 month free subscription of Glific. Use this link to redeem the gift: https://wa.me/+917302307943?text=JoyOfGiving"
7. Mailoption didn't work

**Comment by mdshamoon** [comment]
@abhi1203 
1. I have picked this as an image as it is from the sketch file. If possible can you share the image for this. Its really difficult to export from Sketch for me.
2. Updated the vertical spacing
3. Total width is the same as given in the designs: 290px
4. We don't want to add another font file in the frontend just for this text. Can we please switch this to heebo
5. Updated
6. Updated
7. Can you please try once again for this. It will open the mail application on your laptop. If not working I can check with you.
