### ISSUE TITLE
Organization List: Extension code not showing correctly

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2214]
**Describe the bug**
While updating the extension code for an organization it shows same code for two organization

**To Reproduce**
1. Go to organizations screen
2. Click on search bar and type `an`. This will give a list of organization with matching string `an`
3. Click on extension icon of listed organizations
4. It shows same code for all organizations

**Expected behavior**
Extension code should be shown for organization to which it is added

**Comment by mdshamoon** [comment]
@kurund steps to replicate on local

- Make changes to the user table in database: change the role to `glific_admin`
- In roles table change the label from Admin to Glific_admin.
- Click on staff icon and select organisation option.
- To add an organisation:
  - Go the backend repo and run the `iex -S mix` command and run this function to add a new organization `Glific.Seeds.Seeder.seed([tenant: "New tenant"])`
- Go to organizations screen
- Click on extension icon of the first organization. Add some data in the form and save that.
- Next click on extensions icon for the second organization. It shows the same data
