### ISSUE TITLE
Simulator clearnups

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2225]
**Describe the bug**
There are many formatting issues with the simulator which causes confusion with the users how the message wil be sent.
Listing them below:

1. the button text shows along with the actual button. we should remove the square brackets part from the message body.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/16714604/201030953-5f7eb028-c900-4861-ae18-c40a4fbb3f9a.png">
2. #2224 
3. #2223

**Comment by abhi1203** [comment]
3. After an HSM message gets rejected, the simulator stops showing the attached image (note the image is attached below): 
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/16714604/201032871-ffb347c4-bf78-470b-9a23-7510d79705b0.png">

**Comment by abhi1203** [comment]
you'll see others in edit mode
for 4: https://afeqc.tides.coloredcow.com/template/11775/edit

**Comment by abhi1203** [comment]
5. People are trying to add formatting in the buttons we need to show alert that special characters are not allowed ![image](https://user-images.githubusercontent.com/16714604/202630152-54636c35-70b1-4a4f-99e7-4520e0569a7a.png)

**Comment by mdshamoon** [comment]
@kurund steps to replicate first issue on local:
- Go to the new template creation form
- Fill the given inputs with buttons and an image.
- When we add an image the caption adds the button content as well.
