### ISSUE TITLE
Informative icon doesn't work while creating the flows

### ISSUE THREAD

**Issue by wevekamola** [glific/glific-frontend#2231]
**Describe the bug**
These 3 informative icon doesn't work while creating the flows

<img width="701" alt="Screenshot 2022-11-17 at 2 53 39 PM" src="https://user-images.githubusercontent.com/29367838/202407625-0106c2a6-e7f2-4ebb-abdf-6c4ed8cfb080.png">

**Comment by mdshamoon** [comment]
#2215 is the same issue where tooltips are not working in checkboxes. Keeping only one issue for tracking. Closing this
