### ISSUE TITLE
Messages auto refresh is not working. Page need to refresh manually to see the updated messages

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2233]
![Image](https://user-images.githubusercontent.com/16541548/203018543-3ae558f5-ada2-4d3d-8092-1d4dc93e32c0.png)

**Comment by kurund** [comment]
@mohitsharma-22 

Seems to be working fine for me. Can you please provide steps to replicate the same?

**Comment by kurund** [comment]
@mohitsharma-22 

Closing this as it's working as expected, please feel free to reopen if face this again or have details to replicate the same.
