### ISSUE TITLE
Send updates feature for consulting projects

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2234]
**Is your feature request related to a problem? Please describe.**
Sending updates to clients for consulting projects requires some manual effort every week in calculating the hours we added in the previous week and collecting the updates which we already record in the system on consulting screen. 

The main challenge is calculating the hours from last week. 

**Describe the solution you'd like**
We could have a button on the consulting screens `Send updates` which the team can go in on Monday and trigger. It will simply collate the hours and updates in a template format and send to the client.

For this, we would need the following:
1. enter client email id and all the people the mail should be sent to
2. add a button `send updates`
3. popup to preview email and make any edits before sending

**Comment by mdshamoon** [comment]
The bizdev team will discuss and update on if this needs to be done.

**Comment by mdshamoon** [comment]
We will not modify the consulting screen any further and plan on moving it out from Glific.
