### ISSUE TITLE
Floating load more conversation button

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2242]
**Describe the bug**
The load more conversation is floating something on the screen. it is generally placed at the top of the conversation window.

I noted it in Quest Alliance account. And is probably happening where the chat history is really long. Not really sure how to replicate this. 

https://user-images.githubusercontent.com/16714604/203727018-6b5c0d56-80ea-4e24-aaea-7b787dd6ba80.mov

**Comment by mdshamoon** [comment]
@abhi1203 can you add the screen size and the system details that you are using and the steps that you took.
It would be really difficult to check this without these details

**Comment by mdshamoon** [comment]
Tried to replicate but its working fine for me. Will reopen this issue in case it happens again.
