### ISSUE TITLE
Removing contacts from collect in bulk

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2264]
From Bhumi's request, we need to think how to enable users to do this. A few options i can think of:

1. to keep the status of collections as per the sheet uploaded by the staff - contacts will only be present in the collections that get uploaded in manage contacts.
2. provide a UI option with checkboxes and search on the collection screen to select and take bulk actions on contacts.

**Comment by mdshamoon** [comment]
We should extend this and think about bulk functionalities for flows, templates and other list screens.
