### ISSUE TITLE
Add organisation name on top of login Page

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2271]
The request came from today's discussion in stand-up. NGO users sometimes forget the login URL and keep trying to log in on the incorrect URL. 
Like, in this case, a user from IndusAction was trying to login in CC account.

![Image](https://user-images.githubusercontent.com/16541548/206362156-415eae98-5d04-4c4b-bf57-3b90c244ed05.png)

**Comment by mdshamoon** [comment]
Based on the discussion we are going to move forward with this. We will need an API from the backend to get the organization name. Creating an issue in the backend
