### ISSUE TITLE
Update Glific contract based on discussion during team meet.

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2275]
some pointers were:

- Update the payment cycle. all projects to have phase wise billing based on % completion of the project or % time elapsed out of the contract period. so the invoice will be raised based on time or deliverables completed.
- At the start of the project about 90% of the project should be clear
- contracts will be terminated after reaching the last date and ngos are expected to pay for the project.
- projects will not be shelved once started unless there's a dire need.

**Comment by mdshamoon** [comment]
@mohitsharma-22 closing this since its complete.
