### ISSUE TITLE
Preview not working 

### ISSUE THREAD

**Issue by snehatrivedi11** [glific/glific-frontend#2296]
I was testing Glific bot, tried the 'preview' feature to see the chat flow. Clicked 'preview' multiple times and it isn't working. l even refreshed the page, reopened the flow, still did not work. Pls check the screenshot.
<img width="294" alt="Screenshot 2023-01-08 at 1 55 35 PM" src="https://user-images.githubusercontent.com/119290547/211187114-f74d5af8-8001-43ef-9550-1ad522410247.png">

**Comment by mdshamoon** [comment]
![image](https://user-images.githubusercontent.com/32592458/211201776-b26ad92d-cf9e-4963-982c-bc711f6e9ac4.png)

@snehatrivedi11 I checked the issue and it seems that the first node is a wait for response node in the flow. 
The starting node should be always placed at the top of the flow for it to work.

So the flow was starting but it was waiting for response from the simulator.
