### ISSUE TITLE
Search contacts with in collection.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2376]
The request came from Bhumi NGO where they need to search and remove contacts from the collection. The names are not easy to identify, as the contact's WhatsApp names are different.

The request is to add a feature to search contacts by their phone number in a collection.

<img width="937" alt="Screenshot 2022-10-04 at 10 15 49 AM" src="https://user-images.githubusercontent.com/16541548/193736407-442632ca-e176-45c5-8f7a-028d9c4419b2.png">

<img width="819" alt="Screenshot 2022-10-04 at 10 16 55 AM" src="https://user-images.githubusercontent.com/16541548/193736496-8b160c50-0115-43ca-99a7-abaebd75ec88.png">

**Comment by pankaj-ag** [comment]
This is fixed from the backend and added a PR https://github.com/glific/glific-frontend/pull/2375. 

Let me know if that makes sense otherwise feel free to close that and create a new PR.
