### ISSUE TITLE
Ticketing System: Add new node

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2386]
**Is your feature request related to a problem? Please describe.**
As we are adding ticketing system support in Glific mentioned in this [issue](https://github.com/glific/glific/issues/2761) we'll be needing support to flow editor node for creating a new ticket from the frontend

**Additional links:**
- Backend issue for new [node](https://github.com/glific/glific/issues/2763)

**Comment by shashwatm1111** [comment]
@AkhileshNegi I would like to work upon this issue , please assign me this
