### ISSUE TITLE
Add Help link on each screen with specific feature document

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2390]
**Is your feature request related to a problem? Please describe.**
One of the discussion point in this month review meeting is how to improve the support experience
One pointer was make it more automated , The documentation should be more easily reachable to NGOs before they hit Discord for help.

**Describe the solution you'd like**
The idea is to place a link "Help" at each screen of Glific, which should point to a specific document of that feature.

Sharing the list of mapping of features/screens with the documentation.
https://docs.google.com/spreadsheets/d/1vxY39qJd2tWx18VBP89bXrhxX_TnIdk1mUOMg5SSHU0/edit#gid=0

**Comment by mdshamoon** [comment]
This is added in the new Glific UI #2488
