### ISSUE TITLE
Update the Glific Pricing Page

### ISSUE THREAD

**Issue by nairabhishek73** [glific/glific-frontend#2394]
**Describe the task**
A clear and concise description of the task
The Glific pricing page needs to be updated as per Whatsapp's latest pricing policy which will come into action on the 1st of June. 

**Expected behavior**
Pricing calculator needs to be updated. 
Types of conversations pricing to reflect as per the new categories; marketing, authentication, utility, service.
Text around free conversations will need to change (first 1000 free are only UIC)

**References**
https://developers.facebook.com/docs/whatsapp/updates-to-pricing?content_id=uJjguX9eQoiaTb4
https://glific.org/pricing/

**Comment by nairabhishek73** [comment]
@mohitgusain @mdshamoon

**Comment by mdshamoon** [comment]
This is done. Closing.
