### ISSUE TITLE
Simulator: Messages text align

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2395]
**Describe the bug**
When using the simulator the message sent from simulator align appears to be center aligned, it should be left aligned

**To Reproduce**
1. Go to the chat screen
2. Send a message from the simulator

**Screenshots**
<img width="659" alt="Screenshot 2023-05-22 at 10 54 15 AM" src="https://github.com/glific/glific-frontend/assets/40158831/f9397725-66c6-41c8-84ab-23ae9da8672c">

**Comment by aashi-ihsaa** [comment]
hello, please assign me this issue for c4gt. I want to work on this.

**Comment by mdshamoon** [comment]
Sure @aashi-ihsaa. Make sure you have setup the backend.

**Comment by aashi-ihsaa** [comment]
sure, will resolve this asap.
