### ISSUE TITLE
Simulator not working properly

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific-frontend#2409]
**Describe the bug**
Simulator doesn't work properly sometimes- It triggers some old flow or do not respond when checked.

**To Reproduce**
Attaching the flow link/ screenshot from one of the flows I was trying to testing on the simulator recently
Flow link- https://tap.tides.coloredcow.com/flow/configure/75a033c1-6a5d-4128-9581-69d290508c33

**Expected behavior**

**Screenshots**
<img width="1219" alt="image" src="https://github.com/glific/glific-frontend/assets/122982753/1758a285-be3e-4ea8-87ed-bbfa81684c2c">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KrishnaDwibhashi2** [comment]
other issues observed-
- Flow not starting (old flow still going on/ new flow not starting)
- Keyword is sent, but can’t be seen on UI. But if we cancel & reopen simulator, then keyword is shown & flow gets continued
- Input is taken incorrectly

**Comment by kurund** [comment]
@KrishnaDwibhashi2 

We have updated the packages which might have fixed this issue.  Package upgrade is not yet deployed on prod. I would suggest we should monitor this for a few weeks once it's deployed.

**Comment by kurund** [comment]
> other issues observed-
> 
> * Flow not starting (old flow still going on/ new flow not starting)
> * Keyword is sent, but can’t be seen on UI. But if we cancel & reopen simulator, then keyword is shown & flow gets continued
> * Input is taken incorrectly

It would be good to verify this too after the upgrade and if issue persist file separate issues with the steps to replicate the same.

Thanks.

**Comment by KrishnaDwibhashi2** [comment]
Thanks kurund. Sure- let us know once deployed

cc- @mahajantejas

**Comment by kurund** [comment]
@KrishnaDwibhashi2 

We have deployed the release on prod.

**Comment by kurund** [comment]
@KrishnaDwibhashi2 

I am closing this. Let's file a new issue if there is any further feedback.
