### ISSUE TITLE
Google sheet not available/ populated for reading in flow editor, when both "Read & Write" option is checked when added

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific-frontend#2410]
**Describe the bug**
If both Read & Write options are checked when a google sheet is added, it is not being available in the dropdown (of flow editor) while trying to Read.

**To Reproduce**
1. Add a google sheet and check both Read & Write option
2. Go to the flow editor and select Link google sheets
3. Select Action as Read
4. Check the options coming in the Sheet dropdown

**Expected behavior**
The sheet added (which has Read & Write options checked) should be auto-populated here

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mdshamoon** [comment]
This is fixed. Closing.
