### ISSUE TITLE
Feature: Delete contact field with contact data

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2413]
Description: Provide NGOs with the ability to remove contact fields that are no longer in use, along with the data that is stored against that field for each contact in the system

Pre-read:
[About Contact fields(variables)](https://glific.github.io/docs/docs/Product%20Features/Flows/Flow%20Actions/Split%20By/Contact%20Field/)
[Screen for contact field management](https://glific.github.io/docs/docs/Flows/Flow%20Variables/List%20of%20custom%20contact%20variables%20created%20in%20flows)
glific/glific-frontend#2412 

Sub-issues:

- [ ] Update UI for Contact Field Management: Create an option to allow user to delete contact field along with data 
  **Tasks:**
  - Update the UI layout for contact field management with delete data option.
  - Integrate the UI with the backend API.
  - Implement "Delete Field Only" Option

- [x] glific/glific#2847

**Comment by Darshan2003** [comment]
Working link for [Screen for contact field management](https://glific.github.io/docs/docs/Product%20Features/Flows/Flow%20Variables/List%20of%20Custom%20Contact%20Variables%20created%20in%20Flows)
