### ISSUE TITLE
Loading Screen: Glific Tips

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2421]
### Description
There are some platform tips we want to bring to the attention of NGO partners and after the initial discussion, we came up with the idea of adding these tips to the loading screen across the platform.
E.g. When an NGO logs in instead of showing a blank screen while data is loading we can show a platform tip

Tips can be picked from this [document](https://docs.google.com/document/d/1Bs1sCehQCKGe9fmuJAxmW6gZLqgTn2uUitreo8dJ0aU/edit?usp=sharing)

### Goals
Add tips on loading screenss

### Project Name
Glific

###  Organization Name
Project Tech4Dev

### Domain
Social Sector

### Complexity
Easy

### Tech Skills Needed
Typescript, React

### Name of Mentors
@mdshamoon 

### Category
Feature

### Product Set-Up
https://github.com/glific/

### Acceptance Criteria
PR merged into the main branch

**Comment by turingAlan** [comment]
Hi @AkhileshNegi I would like to work on this issue.

**Comment by masterismail** [comment]
hey @nishant25062002 are you still working on this issue ?

**Comment by mdshamoon** [comment]
Hey @masterismail this issue is completed. Let me know if you are interested in working on other issues in the repo. I can give a quick walkthrough and explain the issue. You can also join our discord channel https://discord.gg/rcBxTA4wnf to easily connect with the team.

**Comment by mdshamoon** [comment]
@masterismail can you join the discord channel? We can have a quick call and discuss.

**Comment by ishaaaa8** [comment]
@mdshamoon  @AkhileshNegi , I'm interested in contributing to this issue. Could you please grant me permission to work on it? Thanks!

**Comment by Viswaraje** [comment]
I am a full stack enthusiast and would love to work on the issues in the repository.Please assign me the issues.
