### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2439]
**Describe the task**
<img width="950" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/e2c0bf4a-0569-4109-aa5c-8110aa16c3d6">

**Comment by nishant25062002** [comment]
Hey @mdshamoon,

In this case, we can truncate the text "Hospitality & HR workshop Interest_May 2023-24" to a maximum of 20-30 characters and add an ellipsis ("...") at the end. We can also add a tooltip or hover effect to display the full name on the hover. Additionally, for mobile devices, we can reduce the font size.

Can I start working on it?

**Comment by mdshamoon** [comment]
Closing as we are taking this up in the new Glific UI.
