### ISSUE TITLE
Scrollbars should look the same across all OS and browsers

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2447]
**Describe the task**
In windows the scrollbars looks a bit weird. We should have it consistent across all browsers and OS

**Comment by EshaBachuwar** [comment]
can you describe it properly how the scrollbar should be

**Comment by EshaBachuwar** [comment]
> **Describe the task** In windows the scrollbars looks a bit weird. We should have it consistent across all browsers and OS

Can you describe it properly how the scrollbar should be

**Comment by mdshamoon** [comment]
Closins since we are taking this up in the new Glific UI.
