### ISSUE TITLE
Automatic translations of flows

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2456]
**Describe the task**

Based on this [issue](https://github.com/glific/glific/issues/2818)

Initial thoughts:
First I think we should probably enable the flow-editor's functionality for translations.
Then we should think about import and export translations

**Comment by mdshamoon** [comment]
@aravind-glific please add your thoughts on the implementation for this and if we can coordinate with the design team for this

**Comment by radhikaT4D** [comment]
taking this off dev priorities since Tejas is working on auto translation feature and will review with dev team soon.
