### ISSUE TITLE
Removing existing Tags from each instance

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific-frontend#2466]
**Describe the task**
All the created tags are displayed across all instances. It is important to keep only tags created by an org in their tags dropdown. Remove the irrelevant tags (tags not created by a given org) from their instance

**Expected behavior**
Only tags created by one org needs to be shown in their tags dropdown

**References**
KEF have reported this issue. Even though 'Manage tags' will be present on new design, it'll be ideal to atleast have this issue sorted for KEF before the new version is deployed.

**Comment by mdshamoon** [comment]
This is done by @AkhileshNegi. Closing.
