### ISSUE TITLE
Explicitly display mandatory & non-mandatory fields 

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific-frontend#2483]
**Describe the task**
Some of the fields like 'Tags' are not mandatory, but NGOs might mistake them as mandatory & hence start creating Tags for each flow, defeating its purpose & accurate categorization. To tackle this, there is a need to explicitly let the NGOs know that some fields are mandatory, while some are not. In case of Tags, displaying them as optional is essential. 

**Expected behavior**
A clear and concise description of what needs to be done.

**References**
Specify any reference material / links

**Comment by kurund** [comment]
We have explicit added help text that will help in this.
