### ISSUE TITLE
Audit item 14 (Sub Resource Integrity (SRI) check not implemented)

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2555]
<img width="670" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/7902d91f-44f8-4339-be80-7cfc211b146b">

<img width="743" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/39637578-d9fd-4864-9b0c-441fd4c9be68">

**Comment by kurund** [comment]
This is fixed in https://github.com/glific/glific-frontend/pull/2569
