### ISSUE TITLE
Additonal things needed from the design team

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2568]
**Describe the task**
Additonal things needed from the design team

<img width="1306" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/0323009b-f15d-4acd-834c-7c0e352e03c3">

This interaction is not given in the desings. What happens when I click on the bottom user icon
<img width="348" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/50a866b0-5e08-4511-960c-515a168f17c4">

- Multiple profile considerations in the contact profile

- Details for all pages when hover after the title

**Comment by aravind-glific** [comment]
Audit issues :
- Last login time
- Active sessions - IP Address or just number of devices logged in

**Comment by mdshamoon** [comment]
@aravind-glific details for all pages when hovered is remaining. Rest is done

**Comment by mdshamoon** [comment]
One part is left which is mentioned in this issue https://github.com/glific/glific-frontend/issues/2654
