### ISSUE TITLE
Images are not showing in Glific Chat screen

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2575]
**Describe the bug**
Reported by KEF. The images are not showing on the Glific Chat screen. It is showing fine on WhatsApp. Replicate it on CC.tides

**To Reproduce**
1. Send an image attachment to Glific from WhatsApp
2. Login Glific
3. Chat screen shows an error in the image uploaded

**Screenshots**
<img width="1033" alt="Screenshot 2023-09-29 at 10 13 59 AM" src="https://github.com/glific/glific-frontend/assets/16541548/bc16535a-2b04-4122-a741-70f04394a5a7">

**Comment by mdshamoon** [comment]
This is fixed and deployed.
