### ISSUE TITLE
Audit item 18 (implement the last login time after login)

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2578]
**Describe the task**
We need to show the last login time based on the recommendation from the audit. 
We are getting the data in the login API: /api/v1/session

in this format
<img width="885" alt="image" src="https://github.com/glific/glific-frontend/assets/32592458/25e80fc8-bbfe-4634-bceb-716b3240ef0a">

Design reference file:
https://www.figma.com/proto/hvzGlCIQBSwHQ70bsW5m9Z/Web-app?page-id=2%3A2649&type=design&node-id=2696-1031&viewport=-9149%2C-36598%2C0.74&t=ZuhDQKuUrl79FVGU-1&scaling=min-zoom

**Comment by kurund** [comment]
@mdshamoon 

> /api/v1/session/renew

We also need the above API to return `last_login_time`.

**Comment by kurund** [comment]
We decided to handle the `last_login_time` in the frontend.
