### ISSUE TITLE
Emails: Setting low balance threshold

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2612]
**Is your feature request related to a problem? Please describe.**
We have added support in the backend to set low balance threshold i.e. the balance when NGO receive the email of wallet balance being low in their Gupshup account. This can differ from organization to organization depending on the scale and frequency of messaging.

**Describe the solution you'd like**
Add UI for updating low balance threshold for an organization

**Comment by mdshamoon** [comment]
@AkhileshNegi do we have an API for this.
