### ISSUE TITLE
Flows: Warning with category

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2625]
**Is your feature request related to a problem? Please describe.**
From backend this is completed
https://github.com/glific/glific/issues/3035

**Designs**
The designs are already ready, please find them on the link below :
https://www.figma.com/proto/hvzGlCIQBSwHQ70bsW5m9Z/Web-app?page-id=2%3A2649&type=design&node-id=2119-2279&viewport=-12277%2C-39559%2C0.97&t=DL6S4OwXq9auSQmW-1&scaling=min-zoom

**Comment by mdshamoon** [comment]
As discussed previously the floweditor already had support for showing issues. So we won't be updating the interface and instead use the floweditor inbuilt schema to show errors

https://github.com/glific/glific-frontend/issues/2630

**Comment by mahajantejas** [comment]
Prod needs to categorize the warnings for the designs to be implemented.
