### ISSUE TITLE
Automated Flow Tester : Auto-populate 'Wait for Response' after Interactive Messages

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific-frontend#2632]
Auto populate data from previous node in 'Wait for Response' node : ‘Wait for Response’ node doesn’t have any data auto populated when the node is created. Auto-populating data from a previous interactive message, list of options given would be helpful in speeding up flow creation process.

**Comment by AkhileshNegi** [comment]
@mdshamoon if you can take first stab on it and let us know what is needed from backend that would be great
