### ISSUE TITLE
Ticketing System : Bulk closure of tickets in the Glific interface

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific-frontend#2665]
- No option in the interface to close/ assign/ reopen multiple tickets together at once, having one would save time & effort for NGOs to handle tickets
- Requested by TAP (bulk closure), Nayi Disha (bulk actions in general)

**Comment by AmishaBisht** [comment]
@mdshamoon this is completed from the backend.

**Comment by mdshamoon** [comment]
This is completed. Closing.
