### ISSUE TITLE
Ticketing System : Navigate to the exact point in flow were ticket was created

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific-frontend#2666]
- Currently on clicking on chat icon in the Ticket listing page, the chat gets opened, but it will be hard to navigate to the exact point were the conversation regarding the ticket creation happened
- Navigating to the point in chat were the ticket gets generated by default will be much more user friendly to deal with for NGOs who have lot of other conversations happening parallely
- Expect this to be a bottle neck for NGOs who plan to use ticketing system extensively
- Requested by Nayi Disha, suggested internally as well

**Comment by mdshamoon** [comment]
This is completed. Closing
