### ISSUE TITLE
HSM templates: UI for variable not getting updated

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific-frontend#2672]
**Describe the bug**
UI for variable is not getting updated (i.e save getting removed) for other languages (except default language), when an HSM message (with variable) is added in a flow for multiple languages

**To Reproduce**
1. Create a template message with variable in 2 languages (Same element name)
2. Add it in default language and update variable
3. Click on other language and update variable.
4. Sometimes the variable takes time to get updated on UI (After refresh sometimes)
5. After few minutes, even if the UI gets updated with variable in other languages, the variable field gets empty (i.e save gets removed)

**Expected behavior**
Either we should not ask for variable in other languages (and consider default language's variable for all) or the added one should get updated & saved.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mahajantejas** [comment]
Closing this issue, as we will create another issue which articulates the same problem statement
