### ISSUE TITLE
Show action UUID instead of Node UUID for a particular node in the flow

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2679]
**Describe the task**
Show action UUID instead of Node UUID for a particular node in the flow

**Comment by AkhileshNegi** [comment]
we need to show both action UUID and Node UUID as in few reports node UUID is used

**Comment by aravind-glific** [comment]
@mdshamoon I've taken it up with Think201, I think we could possibly come up with better looking iterations.

**Comment by mdshamoon** [comment]
As discussed with the product team we are not adding action uuid's. Closing this issue
