### ISSUE TITLE
Interactive Templates: Send location not working in simulator

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2708]
**Describe the bug**
While testing flow containing location interactive message in the simulator.

**To Reproduce**
1. Go to Flows screen
2. Select flow containing location interactive message
3. Click on **PREVIEW** button to test flow
4. The flow starts, Click on **Send location** 
5. Flow does not move forward

**Expected behavior**
Flow should either go to `Has location` path 

**Screenshots**
![bug](https://github.com/glific/glific-frontend/assets/40158831/3801a7b0-6f0e-44e6-aee6-02798f9ccc4c)

**Comment by akanshaaa19** [comment]
this is not replicable.
