### ISSUE TITLE
Check for typos in variables within the 'Send Message' node

### ISSUE THREAD

**Issue by AmishaBisht** [glific/glific-frontend#2712]
**Describe the issue**

extention of this [issue](https://github.com/glific/glific-frontend/issues/2645)

In the "Send Message" node, if we use a variable and there's a mistake or typo in the variable name (like using "results" instead of "result"), it should show a warning.

As shown in the screenshot below, I used the incorrect spelling of "results," and despite that, I was able to publish it without receiving any warnings
<img width="800" alt="Screenshot 2024-01-29 at 7 21 47 PM" src="https://github.com/glific/glific-frontend/assets/90472056/d86b8a8c-62b7-4fa9-9cdc-e7b3a9b38d8d">

**Comment by mdshamoon** [comment]
We have added validation for the results and contact variables, to show warning if they are not valid.

In the case for results and contact it is pretty intuitative and shown as a dropdown that I don't think people are making mistakes (Atleast I have not seen in any support issue or in consulting). I don't think a validation for this would be necessary.
