### ISSUE TITLE
New UI: Organisation Settings

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2715]
**Describe the bug**
In the old UI Organisation and Flows were pinned at the top as those were important, now everything is the alphabetical order

**To Reproduce**
1. Go to Settings

**Screenshots**
<img width="1512" alt="image" src="https://github.com/glific/glific-frontend/assets/40158831/988bb01a-afc8-4700-86fb-348b749e9ae0">

**Comment by mdshamoon** [comment]
This is fixed. Closing.
