### ISSUE TITLE
New UI: Collections screen

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2718]
**Describe the bug**
The "Number of Contacts" column will be quite narrow since it primarily contains two things: the contact count and the word "contacts," like "20 contacts." However, the column is unnecessarily wide. On the other hand, the "Collection Name" might have a longer text but have a smaller width, causing the text to wrap to the next line.

**Expected behavior**
Change padding for collection name and Number of contacts.
Maybe add the description of the collection on the same screen as well if we have space

**Screenshots**
<img width="1502" alt="Screenshot 2024-01-30 at 10 33 29 AM" src="https://github.com/glific/glific-frontend/assets/40158831/81d03d2e-d40c-4c17-98cd-1ea11c28ab29">

**Comment by mdshamoon** [comment]
This is fixed. Closing
