### ISSUE TITLE
Flow Editor: Saving Deleted node translation

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2723]
**Describe the bug**
Flow is saving translation from deleted node too. Which results in giving translation missing warning even if there is not a single node with translation.
Ideally, a missing translation warning is given when there is at least one translation

**Screenshots**
![flow editor](https://github.com/glific/glific-frontend/assets/40158831/41a29876-c2fc-4cca-957d-f69df1d42547)

**Comment by mdshamoon** [comment]
Created an issue for this in floweditor repo https://github.com/nyaruka/floweditor/issues/1216

**Comment by mahajantejas** [comment]
This is completed and handled in backend. We will see if flow editor has added support for handling in front end. Once done, we will remove from backend to handle this case

**Comment by mahajantejas** [comment]
Prioritise with the auto transalte v2 issues
