### ISSUE TITLE
New UI: Login UI bug

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2728]
**Describe the bug**
Usually after a fresh build or when the old token has expired the re-login screen is not center-aligned

**Screenshots**
<img width="1512" alt="image" src="https://github.com/glific/glific-frontend/assets/40158831/923b9b81-ef2f-4c0a-ae7b-228cb1039288">

**Expected behavior**
The login button should be in the middle similar to rest of the text

**Comment by MayaSatishRao** [comment]
@AkhileshNegi I want to work on this issue. Can you assign this issue to me?

**Comment by mdshamoon** [comment]
Hey @MayaSatishRao this issue is already done. Do you want to work on other issues? You can join our discord channel and we can discuss there https://discord.gg/gHmJsWWxXV

This is completed. Closing.
