### ISSUE TITLE
New UI: Collections Screen

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2729]
**Describe the bug**
Description of the collection is breaking

**To Reproduce**
1. Go to https://staging.tides.coloredcow.com/collection

**Screenshots**
<img width="1282" alt="image" src="https://github.com/glific/glific-frontend/assets/40158831/ff2bd275-10bf-47e1-b7e7-95ff74e5b3a9">

**Comment by mdshamoon** [comment]
This is fixed. Closing.
