### ISSUE TITLE
Unread conversation in saved search do not appear

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#273]
When a new message is there, it's highlighted as unread.
![image](https://user-images.githubusercontent.com/12053186/89048575-a3218380-d36d-11ea-9bf8-deb6271620f7.png)

However, in the saved search, it does not appear.
![image](https://user-images.githubusercontent.com/12053186/89048595-a9176480-d36d-11ea-9afe-56b1182ac31c.png)

**Comment by kurund** [comment]
@rathorevaibhav  https://github.com/glific/glific-frontend/pull/279 might have fixed this issue.

**Comment by rathorevaibhav** [comment]
This is working fine. Note: update the backend repo.
