### ISSUE TITLE
New UI: Template name

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2755]
**Describe the bug**
In the old UI template name was bold, followed by template content. Is it intentional in new UI

**Screenshots**

Old UI:

<img width="1511" alt="image" src="https://github.com/glific/glific-frontend/assets/40158831/52f21cd2-ee8d-4e09-bdfc-e43ff070db65">

New UI:

<img width="1506" alt="image" src="https://github.com/glific/glific-frontend/assets/40158831/6ef34478-94dc-4519-93de-1298cde60252">

**Comment by AkhileshNegi** [comment]
Similarly old UI was cleaner for adding attachment. Also instead of
`Add attachments to message` should it be `Add attachment to message`
singular since, only one attachment can be added per message

 **Old UI:**
<img width="1496" alt="image" src="https://github.com/glific/glific-frontend/assets/40158831/0e524608-0564-4e6d-8cc7-99509ad892ee">
**New UI:**
<img width="1107" alt="image" src="https://github.com/glific/glific-frontend/assets/40158831/f20b2f49-c672-4d4b-be41-822042f73df7">

**Comment by mdshamoon** [comment]
This is fixed. Closing
