### ISSUE TITLE
Chat Screen: Refreshing Quick Option

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2759]
**Describe the bug**
When a contact is out of the session window we can only send a template and when the contact is in the session window, we can send a template, interactive template, and quick send.
On receiving a new message from contact it is not refreshed and we need to reload the page to see those options

**Expected behavior**
Quick chat options should be shown on receiving message from contact

**Screenshots**
![session_bug](https://github.com/glific/glific-frontend/assets/40158831/dea27b5e-319e-4a97-b356-29088a4e4d68)

**Comment by mdshamoon** [comment]
Fixed in the next branch.
