### ISSUE TITLE
Glitch with searching for chats

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#287]
**Describe the bug**
On selecting one of the collection options, search stops triggering.

**To Reproduce**
1. Click on any of the collections - 'all' or any other
2. Enter any search keyword say 'greeting'
3. Results don't load

**Expected behavior**
The results should still load as it happens when the user first lands on the screen and enters keyword

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/89107562-83628c00-d44f-11ea-80b8-3ea777955003.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kurund** [comment]
@abhi1203 Filtering withing saved search is currently not supported.
