### ISSUE TITLE
WA Groups: Adding and removing multiple groups to collection is difficult

### ISSUE THREAD

**Issue by mahajantejas** [glific/glific-frontend#2870]
**Is your feature request related to a problem? Please describe.**
After creating the group collection, NGOs need to add the groups to the created collection. 
The number of groups that need to be added can range upto 100 or more. 
The present UX is not the most intuitive for adding a large number of groups to a collection because of the following reasons. 

1. The search bar and the selection window is too small, and when adding a large number of groups, the window can feel cramped.
<img width="1319" alt="Screenshot 2024-04-19 at 3 08 55 PM" src="https://github.com/glific/glific-frontend/assets/141305477/41c1b715-c42c-4658-8c9f-174f9f991a29">

2. upon typing to search a group name the search results are also showing results where the string does not appear at all 

<img width="440" alt="Screenshot 2024-04-19 at 3 10 28 PM" src="https://github.com/glific/glific-frontend/assets/141305477/8b035463-6a25-466e-aa29-0e144b23ce0f">

2. upon selecting a option after typing the search, the search is undone and the search has to be typed again. (the NGOs have created group names with diligent nomenclature, ex - ClassName_SchoolName_Board_Area. So ideally, this should enable them to quickly search and add groups to a collection belonging to similar area or class

**Describe the solution you'd like**
1. Increase the size of the window, for adding of group, which will make it less cramped. by providing the option inside the group collection management tab, which lists the groups inside the collection
2. Provide option to "Select All" based on the search query. 
5. Provide a way to delete multiple groups- can be done similar to "Select All" or "select multiple" based on search query inside the group collection management page

**Describe alternatives you've considered**
1. Using google sheets to upload multiple groups to a collection (similar to updating contact fields in glific) 

**Additional context**
Avanti Fellows has to add upto 200 groups to collection. And will have to create some more dynamic collections for broadcasting which will range in 10s-50s. As the creation of collections is not a one time process, this needs to be simplified.

**Comment by kurund** [comment]
We could potentially change the width of the modal window.
