### ISSUE TITLE
Glific Onboarding form enhancements

### ISSUE THREAD

**Issue by SangeetaMishr** [glific/glific-frontend#2875]
**Describe the task**
While setting up new org, making them fill the Glific Form, many times we observed that the Orgs are getting confused and filling their own number rather filling the BOT number

**Expected behavior**
Can we have a (i) as we have for URL short code to make Orgs aware that the BOT number has to be entered or a short line under that box whereOrgs are filling the number ( Please enter the BOT number)
Right now also the tides.colouredcow is mentioned under the short code URL can we remove this to glific.com

**References**
<img width="1451" alt="image" src="https://github.com/glific/glific-frontend/assets/143380171/004972e0-a265-4918-b1a8-48ff109eea5a">
<img width="299" alt="image" src="https://github.com/glific/glific-frontend/assets/143380171/b7b37bb4-cda0-419d-b244-293a8253bbd6">

**Comment by mahajantejas** [comment]
Closing this as this will be taken care in the new onbarding workflow (TnC feature)
