### ISSUE TITLE
HSM templates: Show the category and quality rating of template on the list page

### ISSUE THREAD

**Issue by mahajantejas** [glific/glific-frontend#2889]
**Describe the bug**
The category of the template approved is not displayed on the list page.
The category is not visible even inside the "edit template" page after the template is approved. 

The category of the approved template is important for the NGO to see, as it directly affects the cost of usage.

**To Reproduce**
1. Go to 'templates' in 'Quick tools'
2. Observe that the list page shows "title", "body", "status", and "actions"
3. Go to "edit" template
4. See inside the template page that the category field does not display the category name

**Expected behavior**
Show the category of the template on the list page. Show the quality rating of the HSM template as it is visible on the gupshup platform, and qualty rating directly affects the delivery rates of the tempaltes. 

**Screenshots**

<img width="1277" alt="Screenshot 2024-05-14 at 2 58 35 PM" src="https://github.com/glific/glific-frontend/assets/141305477/32ad46e6-3cec-43ed-bb99-685a67e5b87c">

screenshot of the list page

<img width="1470" alt="Screenshot 2024-05-14 at 3 02 50 PM" src="https://github.com/glific/glific-frontend/assets/141305477/b0a2823e-0a4e-4558-ab78-2a4bb35924c1">

screenshot of the approved template. observe category field which does not show the category of the message

<img width="226" alt="Screenshot 2024-05-17 at 3 46 57 PM" src="https://github.com/glific/glific-frontend/assets/141305477/85b02587-70ef-4a01-8e64-c5bd506e5921">

Exmaple image from gupshup platform showing the quality rating

**Additional Context**
Issue raised based on request from KEF

**Comment by akanshaaa19** [comment]
here are the [designs](http://lnkiy.in/HSMtemplate)

**Comment by AmishaBisht** [comment]
@mahajantejas currently, the category we are getting from the backend is the updated one, meaning the category that meta has changed the template into the final one. Therefore, we can directly show that category on the frontend. However, some templates whose category meta changed also have the old category (the category with which the orgs applied). So, do we want to show the old category or store the old category as well?
<img width="763" alt="Screenshot 2024-07-03 at 6 04 47 PM" src="https://github.com/glific/glific-frontend/assets/90472056/abd763eb-6782-4773-af30-89425f645344">
cc- @AkhileshNegi

**Comment by mahajantejas** [comment]
@AmishaBisht we want to show only the category the template is approved under on the front end.
