### ISSUE TITLE
Feature: Privacy policy page

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2896]
**Is your feature request related to a problem? Please describe.**
Glific doesn't have a privacy policy page that tells what information is stored on Glific end and how the data is processed.

**Describe the solution you'd like**
Add a privacy policy page. The content should be picked from https://tides.coloredcow.com/privacy-policy. 

**Note:** Check with the product team if the content is fine or do we need to update that.

**Comment by akanshaaa19** [comment]
This is closed #2898
