### ISSUE TITLE
UI bug: Contact details are misaligned

### ISSUE THREAD

**Issue by akanshaaa19** [glific/glific-frontend#2907]
**Describe the bug**
If a message is long then the right panel goes on scroll

<img width="402" alt="image" src="https://github.com/glific/glific-frontend/assets/76031685/22608f79-05e8-499f-bce7-94fcbe9667fa">

**Comment by kurund** [comment]
@hunxjunedo 

Sorry, @akanshaaa19  was working on this, do you want to pick some other issue?
