### ISSUE TITLE
Session Templates: Not able to send certain session templates

### ISSUE THREAD

**Issue by madclaws** [glific/glific-frontend#2925]
**Describe the bug**
When we try to send this specific hsm template `learningpathways` of org `Lahi`, we are getting session closed error, this is because we are not passing `is_hsm` and `template_id` in `create_and_send_message` api. We are able to send few other template messages though. 

**To Reproduce**
1. Login to [Lahi instance](https://lahilms.glific.com/)
2. In chats try to send a template named `learningpathways`
3. We will see session window is closed error and the message is not send

**Expected behavior**
Ideally we should be able to send this particular template message

**Screenshots**
<img width="1470" alt="Screenshot 2024-06-11 at 3 35 03 PM" src="https://github.com/glific/glific-frontend/assets/17821575/7a47aaca-b508-4df3-b47e-2d99995621f9">

<img width="1462" alt="Screenshot 2024-06-11 at 3 35 17 PM" src="https://github.com/glific/glific-frontend/assets/17821575/0f37319d-c78b-40ae-aeea-8196a671bb19">
For another template where we can see, we are passing template params too, and we are not getting session closed error
<img width="1257" alt="Screenshot 2024-06-11 at 3 40 29 PM" src="https://github.com/glific/glific-frontend/assets/17821575/6b096f38-ad97-4918-afcb-826676b4b7b8">

**Comment by akanshaaa19** [comment]
Steps to reproduce:
1. Go to chat screen
2. Pick a contact whose session window is closed 
3. send them a media hsm template 
4. you will see session window closed error even for a hsm template
