### ISSUE TITLE
Flows: Organization Flow 

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#3000]
**Describe the bug**
While setting organization flow, in the dropdown of list of flows it shows even template flows 

**To Reproduce**
![flows](https://github.com/user-attachments/assets/f14d11ec-3195-41b2-8542-e6902dcee1cf)

**Expected behavior**
Only organization flow should be shown

**Comment by AmishaBisht** [comment]
Remove the template flows from start a flow as well
<img width="829" alt="Screenshot 2024-08-06 at 11 23 45 AM" src="https://github.com/user-attachments/assets/6a01f542-8c65-4ea7-974b-968afada5743">
