### ISSUE TITLE
Implement add to group action for a contact from chat interface

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#302]
**Describe the task**
* We need an ability to add a contact to the group from the chat interface

**Expected behavior**
* We add a gear icon as per mockup
* Clicking on the gear icon we should give an option "Add to group"
* On selecting this option we should display a dialog where user can select the group and save.

**References**
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/VgA8Pq

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
