### ISSUE TITLE
Changes on Glific website's pricing page

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific-frontend#3032]
Can you make the below changes to the pricing page of Glific website?

<img width="382" alt="Screenshot 2024-08-19 at 12 13 49 PM" src="https://github.com/user-attachments/assets/3b09c56f-ef64-427c-815b-1cce396e03fb">

Please treat this as P1

**Comment by akanshaaa19** [comment]
Updated pricing here: https://glific.org/pricing/
