### ISSUE TITLE
Remove + symbol in nodes

### ISSUE THREAD

**Issue by KrishnaDwibhashi2** [glific/glific-frontend#3117]
Currently, there is a + symbol in nodes which NGOs sometimes use as a replacement to dragging arrow. As nodes gets stacked, it often creates confusion and doesn't also add any significant value.

We would like to encourage orgs to use arrows only. Hence, please remove + symbol altogether

<img width="556" alt="Screenshot 2024-10-09 at 10 27 27 AM" src="https://github.com/user-attachments/assets/bb7c58f1-b99c-4afa-bc1f-fe5fcf419dbc">

**Comment by kurund** [comment]
@KrishnaDwibhashi2 

This is something part of the upstream package and not specific to us. Many times such features exist based on wider user study etc. My preference would be to avoid altering such behaviour if it's not causing any issues.

**Comment by KrishnaDwibhashi2** [comment]
Got it. Akanksha said it can be removed- so we thought to remove it.
But your point on user study makes sense. We can keep it cc- @mahajantejas

**Comment by kurund** [comment]
Closing as per above comment.

**Comment by SangeetaMishr** [comment]
@KrishnaDwibhashi2  and @akanshaaa19  - I still observE  many NGOs not pulling the node and clicking on the + button to add nodes. How do we solve this. Can we have + functionality which will auto pull arrow rather than node.
