### ISSUE TITLE
A color coding option to differentiate the tags easily

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#313]
**Describe the task**
* A color coding option to differentiate the tags easily.

**Expected behavior**
* Tags should have the background that was selected across the system

**References**
* https://www.npmjs.com/package/material-ui-color-picker

**Comment by kurund** [comment]
@abhi1203 Do you think we should have a fixed palette or user can pick anything?

**Comment by abhi1203** [comment]
@kurund i think let's aim for Color picker and keep plan B for fixed palette? Maybe some library that provides a fixed swatch.

**Comment by abhi1203** [comment]
Support for colored tags
![image](https://user-images.githubusercontent.com/16714604/91417007-ca387b80-e86d-11ea-93f3-b950e5f2dc7d.png)
![image](https://user-images.githubusercontent.com/16714604/91417036-d3c1e380-e86d-11ea-9432-cb9cf6f1cb99.png)

Tags management
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/q3n5Ln
Tags in chat
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/VgA8Pq
