### ISSUE TITLE
An option to block a conversation if it is found inappropriate

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#315]
**Describe the task**
* An option to block a conversation if it is found inappropriate.

**Expected behavior**
* Check the design files

**References**
* Option to block contact - https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/4yv3dJ
* To view blocked contacts - https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/blocked-contacts

**Comment by abhi1203** [comment]
@kurund 
I've added the design inputs here:
Option to block contact - https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/4yv3dJ
To view blocked contacts - https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/blocked-contacts
