### ISSUE TITLE
Loading and Error layouts

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#33]
**Describe the task**
During a page load, if it contains a GQL query, we only show texts like `Loading...` or `Error :(`. These need to be updated to show a better layout using loading/error states with an error message if returned from the GQL API.
```jsx
if (loading) return <p>Loading...</p>;
if (error) return <p>Error :(</p>;
```

**Expected behavior**
1. New components for Loading and Error that can be used at multiple places. Something like:
```jsx
if (loading) return <Loading />;
if (error) return <Error message={error.message} />;
```
2. These components should also ensure cleaner UI and better user experience.

**Comment by kurund** [comment]
The loader is already implemented. I will file a separate issue for the error handling.
