### ISSUE TITLE
Add an ability to assign automation to group

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#348]
**Describe the task**
* Add an ability to assign automation to group

**Expected behavior**
* All the contacts on a particular group should be set for selected automation

**References**
* https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/start-an-automation

**Comment by abhi1203** [comment]
Covered it here
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/start-an-automation
