### ISSUE TITLE
Add an ability to assign automation to a contact

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#349]
**Describe the task**
* Add an ability to assign automation to group

**Expected behavior**
* Selected contact should be set on selected automation

**References**
* https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/start-an-automation

**Comment by abhi1203** [comment]
@kurund 
I've added design inputs here
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/start-an-automation
Let me know if you have questions/suggestions.
