### ISSUE TITLE
UI inputs to catch up with the interface

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#37]
**Edit labels screen**
![image](https://user-images.githubusercontent.com/16714604/84600928-8652ee80-ae9a-11ea-8289-db51a671681a.png)

![image](https://user-images.githubusercontent.com/16714604/85063508-e1048700-b1c7-11ea-9517-9b45b49818d8.png)

------------------------------------------------------------------- 

**Labels screen**
![image](https://user-images.githubusercontent.com/16714604/84600937-a2ef2680-ae9a-11ea-9fee-c34d66ed464f.png)

![image](https://user-images.githubusercontent.com/16714604/85066508-bb2db100-b1cc-11ea-8c3c-ccc37178790d.png)

[Used the material table here](https://material-ui.com/components/tables/#material-table)

------------------------------------------------------------------- 

**Chat screen**
![image](https://user-images.githubusercontent.com/16714604/84787097-32b3e280-b00b-11ea-9b58-165603813e20.png)

![image](https://user-images.githubusercontent.com/16714604/85066574-e2847e00-b1cc-11ea-9ffb-a502a74929b6.png)

[Buttons with icons and labels](https://material-ui.com/components/buttons/#buttons-with-icons-and-label)

**Comment by kurund** [comment]
@abhi1203 is working on new UI, so let's keep this on hold until then.

**Comment by kurund** [comment]
Now we have new UI and these changes are not needed. So closing this issue.
