### ISSUE TITLE
Active sidebar menu

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#385]
Chat should be highlighted in the sidebar, on the groups interface
![image](https://user-images.githubusercontent.com/16714604/91701030-54e1e900-eb94-11ea-8300-57c66362c867.png)

This is happening for all the screens selected from the bottom navigation - Groups, Staff, Settings

**Comment by kurund** [comment]
@abhi1203 I guess you mean Settings Icon should be highlighted and not the Chat?

**Comment by abhi1203** [comment]
@kurund yes. Settings or groups or user whichever one is active.
