### ISSUE TITLE
Staff groups

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#406]
Staff person is in two groups but only one shows on the chat screen
![image](https://user-images.githubusercontent.com/16714604/92000712-72ad7a80-ed5b-11ea-81cb-ae635cc4ad61.png)
Added in two groups:
![image](https://user-images.githubusercontent.com/16714604/92000806-91ac0c80-ed5b-11ea-9d0d-b20ddee19aaf.png)

**Comment by rathorevaibhav** [comment]
@abhi1203 @kurund I believe there is some confusion here. the first screenshot is for a contact, hence the system is showing the groups for that contact.

The second screenshot is for a user (staff person) and the groups he/she is assigned to.

I think we may not need to make functional changes here, maybe change representation a bit to avoid confusion. let me know.

**Comment by kurund** [comment]
@abhi1203 I think functionality is working as per design. Let me explain:

We can assign group(s) to staff from the staff edit screen. For eg:
![Screenshot 2020-09-05 at 10 35 23 AM](https://user-images.githubusercontent.com/151481/92298145-8dead680-ef63-11ea-8e20-f220ed20fcbd.jpg)
Note that this won't be shown in staff's beneficiary account view. ie.
![Screenshot 2020-09-05 at 10 38 13 AM](https://user-images.githubusercontent.com/151481/92298181-f0dc6d80-ef63-11ea-9807-c45db2b50649.jpg)
As the staff is assigned to the group it will be shown on the group management assigned to the staff section.
![Screenshot 2020-09-05 at 10 39 19 AM](https://user-images.githubusercontent.com/151481/92298213-21bca280-ef64-11ea-9b25-b9df0e3aeabb.jpg)

Hope this helps. If needed we can also jump on a quick call.

**Comment by kurund** [comment]
@abhi1203 closing as per our discussion
