### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#415]
<img width="430" alt="Screenshot 2020-09-03 at 12 46 46 PM" src="https://user-images.githubusercontent.com/16714604/92083554-d5e2ef80-ede3-11ea-997a-c7ce0c059c2b.png">

We can remove the line below Glific logo because the lines don't align
Also check the vertical spacing in the name area
<img width="497" alt="Screenshot 2020-09-03 at 12 52 26 PM" src="https://user-images.githubusercontent.com/16714604/92084084-80f3a900-ede4-11ea-908f-7c3ee8bff741.png">

Collections lower part of the modal is not accessible anymore.
![image](https://user-images.githubusercontent.com/16714604/92085408-65899d80-ede6-11ea-9838-ff4ba4bc8477.png)

**Comment by abhi1203** [comment]
Alignment of actions icons on template screen 
![image](https://user-images.githubusercontent.com/16714604/92118014-8ddbc100-ee13-11ea-8017-c2d9e62c15b3.png)

**Comment by kurund** [comment]
@abhi1203 we are not sure about the below comment. Looks fine to us. Let us know if we are missing anything.

> Also check the vertical spacing in the name area
