### ISSUE TITLE
Refresh for updates

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#421]
For certain new change, the updates only show on refreshing the screen. Is it possible to see things more real time?

Ex. 1
On whatsapp i received a response (that were setup on dialogflow)
![image](https://user-images.githubusercontent.com/16714604/92134187-da7cc780-ee26-11ea-9876-bff257312dd8.png)
But didn't show up before refreshing
![image](https://user-images.githubusercontent.com/16714604/92133952-97baef80-ee26-11ea-8302-c7473699be04.png)

Ex. 2
I sent a flow to a group but could only see it on refreshing

**Comment by kurund** [comment]
@abhi1203 I think this might have been fixed as a part of another issue. Can you please recheck.

**Comment by abhi1203** [comment]
@kurund the first one seems good but the second one for flow still needed reloading.

**Comment by kurund** [comment]
@abhi1203 second case looks like bug in the backend. I will follow up with them.

**Comment by kurund** [comment]
@abhi1203 Check with backend earlier today and is working as expected.  @pankaj-ag suspected it might be failing in some situations. He is working the same.

**Comment by kurund** [comment]
@abhi1203 I have tested again and seems to be working fine now. We can re-open or file new this if needed.
