### ISSUE TITLE
Assigned staff on chat screen

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#426]
Is it possible to pull of showing the assigned staff members on chat screen?
![image](https://user-images.githubusercontent.com/16714604/92165842-5130b980-ee55-11ea-84f9-723dae0dbdb8.png)

**Comment by rathorevaibhav** [comment]
@abhi1203 @kurund how many names are we targeting to show?

There are several conditions:
1. there can be more than 2 people assigned for in poetry group
2. there can be more than 2 people assigned for arts group
3. there can be more groups for a contact

**Comment by abhi1203** [comment]
I think we should show all the unique names, that should also help them understand how the assignment is happening and if they want to modify something about it. Going for the first names of all the assigned staff is fine.

**Comment by rathorevaibhav** [comment]
That sounds fine. Just an edge case that in case it's a long list, we might end up having too many names and the section too stretched vertically. But lets see for the use case.

**Comment by rathorevaibhav** [comment]
Based on discussion with @abhi1203 , moving ahead with two names and then +2/+3/+4, etc.
