### ISSUE TITLE
Messages disappear when session timer is zero

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#466]
**Describe the task**
* Currently, we are not able to send the messages to the contacts when the session timer is 0.
* Sent messages does not show and there is no error or message response shown to the user

**Expected behavior**
* We need to provide correct message/input to the user about message deliver status

**Comment by abhi1203** [comment]
@kurund this is how im thinking about it. let me know if this works

https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/qqQDxV
along with:
https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/92bmDW

**Comment by kurund** [comment]
@abhi1203 yes this works.
