### ISSUE TITLE
Timeout screen

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#489]
After timeout, the screen goes to the website landing page and looks broken
![image](https://user-images.githubusercontent.com/16714604/93072243-c34b9e80-f69e-11ea-85ee-e68674a5609e.png)

Can we send the users to login page like before?

**Comment by rathorevaibhav** [comment]
I believe this fix was needed as Tides level, not on Glific. @abhi1203 this should be fixed based on my discussion with Tides team. Please test again.

**Comment by rathorevaibhav** [comment]
Ignore my previous comment. This is happening right now. Glific frontend needs to update code to redirect to login on timeout.

**Comment by kurund** [comment]
@rathorevaibhav on timeout we do redirect to login. Let's discuss this.

**Comment by rathorevaibhav** [comment]
Not able to replicate this any further. It seems like this got fixed in a recent release as we are redirecting to `/logout` (which eventually takes to `/login`) when the user session/token is expired.
