### ISSUE TITLE
Implement admin interface for message templates

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#49]
**Describe the task**
Implement an admin interface to manage message templates (similar to tags)

**Expected behavior**
* This interface will include the following:
* Add a new menu link, Message Templates
* By default it will list the existing message templates
* Ability to add/edit/delete message templates
* Complete test coverage for the new functionality

**References**
https://docs.google.com/document/d/1Q7ozYAHl1wcVQlXcg3iZjQZPHaUQJzQCYHTLaajncrs/edit#heading=h.peaioojzckds

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
