### ISSUE TITLE
Speed send and template formatting shook up

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#500]
![image](https://user-images.githubusercontent.com/16714604/93715211-a70b9e00-fb85-11ea-806b-770dfb26800e.png)

The alignment of text and heading used to like nice earlier like this:
![image](https://user-images.githubusercontent.com/16714604/93715269-f6ea6500-fb85-11ea-954d-82cf4fb946bf.png)

**Comment by kurund** [comment]
@abhi1203 Earlier we were not displaying the formatting correctly. Hence, now the display is changed
