### ISSUE TITLE
Missing conversation in collections

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#501]
This conversation should show in the collection because of the matching tags and groups, but it's not showing up 

![image](https://user-images.githubusercontent.com/16714604/93716472-ad057d00-fb8d-11ea-8278-7d79e967c01c.png)

![image](https://user-images.githubusercontent.com/16714604/93716484-c0184d00-fb8d-11ea-9f2b-b25929f59b22.png)

**Comment by kurund** [comment]
If needed we can relook this in the future, closing this for now.
