### ISSUE TITLE
Saved active languages reverts 

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#504]
**Describe the bug**
After selecting and saving the active languages, it reverts to english

**To Reproduce**
![image](https://user-images.githubusercontent.com/16714604/93719727-0d9eb500-fba2-11ea-9085-09862dff1d53.png)
Save and come back to the settings screen

**Expected behavior**
the selections should continue to show as per the selection

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/93719750-2dce7400-fba2-11ea-9f6a-16c873f17a81.png)

**Comment by kurund** [comment]
@abhi1203 This is working as expected. 

![Screenshot 2020-09-21 at 9 22 54 AM](https://user-images.githubusercontent.com/151481/93734717-0d310900-fbf8-11ea-8f01-f8b3f5e43126.jpg)

**Comment by abhi1203** [comment]
Please see:
[Screen Recording 2020-09-21 at 10.50.53 AM.zip](https://github.com/glific/glific-frontend/files/5253553/Screen.Recording.2020-09-21.at.10.50.53.AM.zip)
