### ISSUE TITLE
All available lanugages

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#505]
@kurund there is where im supposed to see all the languages right to select the preferred ones for my ngo?
![image](https://user-images.githubusercontent.com/16714604/93731638-8aa24c80-fbeb-11ea-85c2-8c5f3985137a.png)

**Comment by pankaj-ag** [comment]
@abhi1203 @kurund  this is because we did not run the seeder. 
It's updated for the SOL. 

We are working on multi-tenancy and these confusions will be resolved soon.

**Comment by abhi1203** [comment]
Okay @pankaj-ag 
While you're at it, can you also order the dropdown alphabetically

**Comment by kurund** [comment]
@rathorevaibhav Can also fix the API request on the frontend to sort it correctly.
