### ISSUE TITLE
Icons for last media type message

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#506]
**Is your feature request related to a problem? Please describe.**
When we have the last message for a conversation a media file, we just show the media type (in caps!).
<img width="365" alt="Screenshot 2020-09-18 at 8 50 21 PM" src="https://user-images.githubusercontent.com/12053186/93731786-2d5acb00-fbec-11ea-846f-14bf1f1a7982.png">

**Describe the solution you'd like**
This can be easily replaced by an icon and the type like  `🎥  Video`. The same goes for audio and video files.

Designs here: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/Ogb9A2

**Comment by mdshamoon** [comment]
I would like to work on this issue.

**Comment by rathorevaibhav** [comment]
This is merged in https://github.com/glific/glific-frontend/pull/638
