### ISSUE TITLE
Fix the spacing in chat window

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#507]
**Describe the bug**
Spacing between tags and the chat editor is not right.
<img width="467" alt="Screenshot 2020-09-18 at 8 29 06 PM" src="https://user-images.githubusercontent.com/12053186/93731801-406d9b00-fbec-11ea-8392-de1f9adf5fef.png">

**To Reproduce**
This happens specifically for incoming messages as there is less space due to the "speed-send/template" options.

**Expected behavior**
There should be a bit larger spacing between message and the chat editor

**Comment by aditimaurya** [comment]
Hey, @rathorevaibhav! Can you please give me some more information, like on which file I have to make changes? Please do let me know so that I'll start working on this asap.

**Comment by rathorevaibhav** [comment]
hey 👋 @aditimaurya, welcome to Glific!

You may want to look into the following files for this and add spacing:
1. ChatMessages.tsx
2. ChatMessage.tsx
3. ChatInput.tsx

**Comment by aditimaurya** [comment]
@rathorevaibhav thanks for your insights. By the way, are you going to label this as an hacktoberfest issue? If you are planning then do let me know I'll make a PR in October then, and in mean time I'll read and try to understand codes and documentation better.

**Comment by rathorevaibhav** [comment]
hi @aditimaurya, we haven't planned issues for the hacktoberfest yet. We'll definitely mark any/all issues for the Hacktoberfest in the first few days of October.

**Comment by aditimaurya** [comment]
@rathorevaibhav  sure! do let me know. I'll try my best to fix this issue.

**Comment by rathorevaibhav** [comment]
This seems to be fixed in some recent release. Not able to replicate it anymore.
