### ISSUE TITLE
Add a loading state to the login button

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#523]
**Describe the task**
Right now, when clicked on login button, it takes some time to make the API call and take the next action. The next action is either the error message or user getting redirected to chat window.
Due to the time gap in button click and API response, user gets confused whether he/she clicked on the button or not and clicks again (and again) to confirm.

**Expected behavior**
Add a loading state to the login button. We can take any the following steps here:
1. Show a rotating loader or change the button text so that user knows button is clicked
2. Disable any further clicks on the button
3. In case of invalid login, enable the button again so that the user can click on it after updating credentials.

**Comment by abhi1203** [comment]
Can we also please activate login action by hitting `Enter` instead of pressing the login button only
