### ISSUE TITLE
Settings icon disappears on page reload

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#534]
**Describe the bug**
After a page reloads, the settings icon disappears. It comes back when any link or button is clicked.

After page reload:
![image](https://user-images.githubusercontent.com/12053186/94177772-bd806500-feb7-11ea-88cf-c4360adec773.png)

After any button/link is clicked:
![image](https://user-images.githubusercontent.com/12053186/94178087-3e3f6100-feb8-11ea-8d65-f50673883955.png)

**To Reproduce**
1. Login to Glific. You will be on chat screen and can see the settings icon.
2. Do a page reload. The settings icon will disappear.
3. Click anywhere (on a button or link or page). The settings icon will reappear.
4. Go to any page and do a reload. The settings icon will disappear again.

**Expected behavior**
The settings icon should be there at all times.

**Bonus**
This might be the cause for CI failing inconsistently.

**Comment by mattrafalko** [comment]
Interested in taking a look at this issue. 
Can't seem to log in - getting a 404 error when trying to create an account. 
Do you have a tester login I could use?

**Comment by kurund** [comment]
@mattrafalko Have you setup backend? Please check: https://github.com/glific/glific/blob/master/README.md

**Comment by rathorevaibhav** [comment]
This seems to be working normally now. Nothing more needed.
