### ISSUE TITLE
Templates tab should be there?

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#540]
@kurund @pankaj-ag 
Any ideas why we can't see the template tab here, even though the session timer shows 0 - which means that the person is opted in?
![image](https://user-images.githubusercontent.com/16714604/94430491-a2606e80-01b1-11eb-90b6-366d7e36fc84.png)

**Comment by kurund** [comment]
@abhi1203 This might be a case where the beneficiary has not opted in.

**Comment by abhi1203** [comment]
Okay and in that case the session timer should also show the block sign instaed of 0. that's where i was confused

**Comment by rathorevaibhav** [comment]
@kurund @pankaj-ag I was able to re-create this case by modifying the database directly. Here's what I have in place for this contact:
1. status: valid
2. provider_status: none

I'm not sure how without modifying DB, these settings can be possible. But thought to post in case it can help to debug.

**Comment by kurund** [comment]
@rathorevaibhav added an additional condition to display blocked icon if provider_status == NONE
