### ISSUE TITLE
Error while sending the message to the beneficiary

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#546]
It's not always so not sure how you can replicate but sometimes I see this inconsistency. 

![image](https://user-images.githubusercontent.com/10670690/94528163-9ded9180-0255-11eb-836f-423d9b795a54.png)

**Comment by pankaj-ag** [comment]
It may be a timezone issue as well. But I am not very sure.

**Comment by kurund** [comment]
@pankaj-ag We are displaying the above message when we receive "unable to send" error response from the backend.

**Comment by kurund** [comment]
@pankaj-ag Do re-open if you are able to replicate and provide steps for the above.
