### ISSUE TITLE
Tags in collection search not sorted

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#571]
**Describe the task**
In the conversation advanced search, the tags are not coming in sorted list. It's difficult to find a specific tag without searching.
![image](https://user-images.githubusercontent.com/12053186/95329627-ded44e80-08c4-11eb-9a1f-8a385ba12821.png)

**Expected behavior**
Tags in collection search should come in sorted order ascending.

**Comment by rathorevaibhav** [comment]
@abhi1203 @kurund let me know if this makes sense to implement.

**Comment by kurund** [comment]
@rathorevaibhav I think all the tag and group listing should be alphabetically sorted
