### ISSUE TITLE
Make api prefix for the backend configurable

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#586]
**Describe the task**
* Currently, we are using REACT_APP_API_PREFIX="api". This assumes backend is configured api.glific.test.

**Expected behavior**
* Frontend should work based on the prefix.

Note: This might need some work from the backed team

**Comment by rathorevaibhav** [comment]
@kurund  the API prefix seems to be working as expected
if we add PREFIX_URL in the env then we get - api.glific.test and if we remove PREFIX_URL then we get glific.test

**Comment by rathorevaibhav** [comment]
After discussion, replace the following in .env.example
```env
REACT_APP_API_PREFIX="api"
```

to
```env
REACT_APP_API_PREFIX=""
```

This is helpful to avoid exact copy/paste from .env.example to .env
