### ISSUE TITLE
Change error message on Edit contact page

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#588]
**Describe the bug**
The message is very technical

**To Reproduce**
1. Go to Profile, or go to View contact profile
2. Click on name field and leave it empty
3. See error

**Expected behavior**
The message can be "Please fill out this field."

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/95724693-49560780-0c94-11eb-8a83-060184af702f.png)

**Comment by kurund** [comment]
@abhi1203 Seems to be working fine for me. Are you on the latest master?

![Screenshot 2020-10-12 at 3 56 18 PM](https://user-images.githubusercontent.com/151481/95736246-98efff80-0ca3-11eb-9765-77495eb9c077.jpg)

**Comment by abhi1203** [comment]
It got updated for me now. thanks
