### ISSUE TITLE
Language selection for contact

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#590]
**Describe the bug**
Currently only English is available for selection for a contact's default language.

**To Reproduce**
1. Go to contact profile
2. Click on lanague
3. See error - only english is available.

**Expected behavior**
Complete list of languages should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/95727112-64764680-0c97-11eb-8f01-111be6232243.png)

One question: does this also change the default language for the contact while chatting?

**Comment by abhi1203** [comment]
Same happens on tags screen also
![image](https://user-images.githubusercontent.com/16714604/95731206-d4d39680-0c9c-11eb-9f42-e4d896a4840c.png)

**Comment by kurund** [comment]
@abhi1203 the language dropdown in the above screens display the languages enabled for the organization. In your case, it's only English.

Shows multiple languages:
![Screenshot 2020-10-12 at 4 57 27 PM](https://user-images.githubusercontent.com/151481/95741694-541c9680-0cac-11eb-8e4b-2de589ffc71f.jpg)

Organization settings:
![Screenshot 2020-10-12 at 4 57 43 PM](https://user-images.githubusercontent.com/151481/95741726-6991c080-0cac-11eb-881f-380a45c17f1e.jpg)

**Comment by abhi1203** [comment]
Got it! I didn't know that's how these were linked too. Do you think we should add a small textual line to let the users know?

'For more language options please select in settings'
Like that?

**Comment by kurund** [comment]
@abhi1203 We will have some users who don't have access to settings etc. So I think we should just avoid it.

**Comment by abhi1203** [comment]
Oh right, then I believe in that case it may be even more confusing for those users what to do. Like even i didn't know that they were linked and these users might have more challenge on who to reach out.
It may not be a lot to add text to bring clarity for that feature. 
Or we can also wait for a use case from an NGO to ask for some solution. What do you say?

**Comment by kurund** [comment]
We can add the help text if you strongly feel for it.  May be somthing like "Available languages for your orgnization". Settings may will not be visible to staff role and it will create unnecessary confusion.

**Comment by abhi1203** [comment]
oh, in that case we can have this:
'For more languages check settings or connect with your admin'
This makes it really clear that if it's admin s/he can check settings but if another person, they can contact the admin.

I think the idea is to convey that they are not limited to just these language, there can be more as they want.
