### ISSUE TITLE
Contact page detail

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#591]
**Describe the bug**
If no group has been assigned to a contact, then it says None, but the same doesn't happen for Groups

**To Reproduce**
1. Go to contact profile
2. See error in the right column as per the screenshot attached below

**Expected behavior**
Can we show 'None' text for Groups as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/95729029-e0718e00-0c99-11eb-898e-17283a31a6d6.png)

**Comment by abhi1203** [comment]
Sorry, there's a followup issue now:
Steps:
1. Add a contact to a group
2. Then remove. and you'll see the group still there

![image](https://user-images.githubusercontent.com/16714604/95758868-981c9500-0cc6-11eb-8396-e762a4b32630.png)
![image](https://user-images.githubusercontent.com/16714604/95758907-a4085700-0cc6-11eb-8c5a-0f95eb6fa028.png)


The same thing is happening for Assigned staff also. After i unassigned the staff in group settings. No staff, no group.
![image](https://user-images.githubusercontent.com/16714604/95759018-ce5a1480-0cc6-11eb-8e52-9c573fcf333e.png)
still shows up
![image](https://user-images.githubusercontent.com/16714604/95759053-d6b24f80-0cc6-11eb-816f-a0e908a7991a.png)

**Comment by kurund** [comment]
I have filed a separate issue as the above is not directly related to this: https://github.com/glific/glific-frontend/issues/608
