### ISSUE TITLE
Add integration tests to CI

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#596]
**Describe the task**
1. Cypress tests should also run in CI.
2. Will there be a separate GitHub action or in the same one? Will it report a different status on PRs?

**Comment by kurund** [comment]
@Satendra-SR let me know if you need anything from me.

**Comment by Satendra-SR** [comment]
Hey @kurund @rathorevaibhav Thanks. I'll come up with the available options, implementation plan, and estimated effort for this issue.

**Comment by DigneshGujarathi** [comment]
@kurund Created [cypress-testing](https://github.com/glific/cypress-testing) repo to integrate cypress into CI, therefore closing this issue.
