### ISSUE TITLE
Contact Group not displayed correctly

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#608]
Sorry, there's a followup issue now:
Steps:
1. Add a contact to a group
2. Then remove. and you'll see the group still there

![image](https://user-images.githubusercontent.com/16714604/95758868-981c9500-0cc6-11eb-8396-e762a4b32630.png)
![image](https://user-images.githubusercontent.com/16714604/95758907-a4085700-0cc6-11eb-8c5a-0f95eb6fa028.png)

The same thing is happening for Assigned staff also. After i unassigned the staff in group settings. No staff, no group.
![image](https://user-images.githubusercontent.com/16714604/95759018-ce5a1480-0cc6-11eb-8e52-9c573fcf333e.png)
still shows up
![image](https://user-images.githubusercontent.com/16714604/95759053-d6b24f80-0cc6-11eb-816f-a0e908a7991a.png)

If it works, you can assign the task back to me and i can test and close it.

_Originally posted by @abhi1203 in https://github.com/glific/glific-frontend/issue_comments/707161568_

**Comment by rathorevaibhav** [comment]
@kurund this seems to be working as expected. Please have a look
