### ISSUE TITLE
Arrange automation flows alphabetically

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#614]
**Describe the task**
Since the flows aren't arranged alphabetically, it gets difficult to look for the right flow.

**References**
![image](https://user-images.githubusercontent.com/16714604/96247045-2ba3dd80-0fc7-11eb-961d-4af49146b817.png)

**Comment by DigneshGujarathi** [comment]
@abhi1203 It's already been done (https://github.com/glific/glific-frontend/pull/578). You can see after updating the site with the latest code.

**Comment by abhi1203** [comment]
Okay. Thanks! Closing this one then
