### ISSUE TITLE
A way for users to pin or arrange flows

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#615]
**Is your feature request related to a problem? Please describe.**
Currently to quickly reach a flow that the user is working on, they need to either travel across pages or add a numerical value in front of the title to make it work. 

**Describe the solution you'd like**
Maybe there could be a way for users to pin or order the flow rows, so that they can arrange it according to their frequency of use.

**Describe alternatives you've considered**
Using numbers and symbols is an alternative but may not keep the application really neat for them.

**Additional context**
![image](https://user-images.githubusercontent.com/16714604/96247137-55f59b00-0fc7-11eb-9d10-6237609ece93.png)

**Comment by DigneshGujarathi** [comment]
@abhi1203 One of the options is that after creating/updating, we can use sort by date and time, so that we can render the newly created/updated as the first in the list.

**Comment by abhi1203** [comment]
@DigneshGujarathi yes that is also a great idea. 
and just to make it flexible we can probably give sort by option.

**Comment by DigneshGujarathi** [comment]
> @abhi1203 One of the options is that after creating/updating, we can use sort by date and time, so that we can render the newly created/updated as the first in the list.

@pankaj-ag @anshulrr Does the backend have support for this?

**Comment by kurund** [comment]
@pankaj-ag @anshulrr any thoughts on this?

**Comment by kurund** [comment]
It was decided to do the following for this usecase:
* Set default pager to 50
* Add sortable modified by column
