### ISSUE TITLE
Change 'Done' button to 'Update'

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#616]
**Describe the bug**
Since the functionality has changed that the flows only get published when the button is clicked. it would be better to make the button text more in-line with the action.

**Expected behavior**
The button title to be called 'Update'

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/96248059-9bff2e80-0fc8-11eb-9fc6-35298e27dae5.png)

**Comment by mdshamoon** [comment]
I'd like to work on this issue.
