### ISSUE TITLE
Password reset functionality doesn't seem to be working

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#639]
**Describe the bug**
There's nothing beyond the error message.

**Expected behavior**
User should receive an otp at the number.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/97149530-e0da5080-1792-11eb-8351-f776e0884e4b.png)

**Comment by kurund** [comment]
@abhi1203 This might be related to how the backend is sending the OTP messages. I think once the 24-hour window is expired no messages are being sent.

**Comment by abhi1203** [comment]
Oh no, it's funny how our solution became the challenge. 😅

What could be the solution? using HSM?

**Comment by kurund** [comment]
We do have a template message for OTP. So if the configuration is correct at Gupshup end you should receive a message as HSM automatically.

**Comment by kurund** [comment]
@abhi1203 Let us know if you need anything on this issue. (should we close this?)

**Comment by kurund** [comment]
Closing this for now.
