### ISSUE TITLE
Better accessiblity to login button on registration page

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#676]
**Describe the task**
On registration page, there are chances that the login button can go hidden due to scroll. and large height of the registration form

**Expected behavior**
the login button should be visible as much as possible within the viewport

this is what we can do to correct. maybe even reduce some height of the page in other places on this page?
![image](https://user-images.githubusercontent.com/16714604/98101264-f7ca2280-1eb7-11eb-9053-5dd3199244cf.png)

**Comment by kurund** [comment]
@abhi1203 Just a thought, should we move login on right? Kind of 3 column layout?
