### ISSUE TITLE
Clearing a chat

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#681]
**Describe the bug**
Whenever chat is cleared, there should be a stamp demarcate that so that users always have a record of the action.

**To Reproduce**
1. Clear chat for a contact
2. It shows 'No messages'

**Expected behavior**
The message should say conversation cleared.

**Screenshots**
From this,
![image](https://user-images.githubusercontent.com/16714604/98230292-00d2f680-1f81-11eb-9afd-564e0a52ee8a.png)
to,
![image](https://user-images.githubusercontent.com/16714604/98230359-0cbeb880-1f81-11eb-87fb-d72fd6f0f190.png)

**Comment by kurund** [comment]
@abhi1203 I have mixed thoughts on this. You might also want to know who cleared it etc. So this more leading today kind of audit trail.

@anshulrr Do we keep track of these events in the backend?

**Comment by anshulrr** [comment]
@kurund Right now, we don't keep track of these events.

**Comment by abhi1203** [comment]
@kurund I understand. This is more like when we delete a message on whatsapp, it leaves an imprint behind. I thought about showing name also, but probably won't need it now. Only a marker that the conversation was deleted will help them know in future what happened in the system. I do understand that if it happens too many times like in simulator, these will get stacked and maybe we'll have to give a way to remove these also. Or maybe just capture the last removed. 

We can thinking about tracking more events if NGOs really need it in future.

Or if you'd like to defer it altogether. That's fine too.

**Comment by kurund** [comment]
As discussed deferring this one for the future and we can relook at this based on the feedback etc.
