### ISSUE TITLE
Automation flows issues

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#690]
**Describe the bug**
1. I was consuming the messages in hindi but for the activity, message appeared in english.
2. Also, in simulator the attachment doesn't show.
3. Also, the attachment keeps loading, and doesn't show up.

**To Reproduce**
1. Start new contact flow in simulator
2. Choose poetry option during the activity flow

**Expected behavior**
The message in glific window should show in hindi
Message in simulator should also show the attachment.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/98502893-3de90280-2279-11eb-9bbb-b906466fd05d.png)
![image](https://user-images.githubusercontent.com/16714604/98503097-c1a2ef00-2279-11eb-8bd7-8db3025e9132.png)

**Comment by abhi1203** [comment]
This is working now.

**Comment by abhi1203** [comment]
I'm sorry, this was working wwith youtube video url but not with a google image url

**Comment by mdshamoon** [comment]
@abhi1203 we have added URL validation in the floweditor. Only valid URL's can be saved now.

**Comment by mdshamoon** [comment]
This has been fixed. Closing.
