### ISSUE TITLE
Duplicate labels in flows

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#691]
**Describe the bug**
Somehow for SOL, duplicate labels are showing up on automations screen.
Though there doesn't seem to be a possibility to duplicate the label.

**Expected behavior**
The labels should show up once so that it can be utilized efficiently for reports. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/98503793-6d007380-227b-11eb-9910-a2f88eeeef37.png)

**Comment by kurund** [comment]
@pankaj-ag this looks like a flow editor related issue.

**Comment by kurund** [comment]
Rechecked and looks like this is fixed now.
![Screenshot 2020-11-26 at 12 19 32 AM](https://user-images.githubusercontent.com/151481/100269800-20a47b80-2f7d-11eb-84b3-3c1da6de5fde.jpg)
