### ISSUE TITLE
Google cloud storage title

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#694]
**Describe the bug**
The title appears with an underscore on the edit page

**Expected behavior**
The underscore shouldn't be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/98530676-435c4200-22a5-11eb-89f9-7674aa76c340.png)
![image](https://user-images.githubusercontent.com/16714604/98530706-4e16d700-22a5-11eb-8786-3e17210876a2.png)

**Comment by DigneshGujarathi** [comment]
@anshulrr @pankaj-ag 
Currently, we are displaying a shortcode as a title here.
Can we update the shortcode respectively? else will need a name/title in credentials API

**Comment by anshulrr** [comment]
@DigneshGujarathi 
We can get the name in the provider object in the credentials API.
