### ISSUE TITLE
Default provider in settings shows as Shortcode

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#695]
On settings page
![image](https://user-images.githubusercontent.com/16714604/98530858-7dc5df00-22a5-11eb-9bc6-eb7976d1d31f.png)
On editing
![image](https://user-images.githubusercontent.com/16714604/98530878-828a9300-22a5-11eb-839a-fcdaa34f12af.png)

**Comment by DigneshGujarathi** [comment]
As I know, the default provider should not be in the list.
@anshulrr @pankaj-ag Can you please verify this?

**Comment by anshulrr** [comment]
@DigneshGujarathi @abhi1203 
Default Provider is seeded for development only. 
In staging and production, it won't be there in the list.
