### ISSUE TITLE
Copy automation

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#698]
**Describe the bug**
1. While copying the flow the name doesn't change on configure screen
2. The flow isn't triggering while starting an automation for a contact or when adding in between the flow.

**To Reproduce**
1. Click on make a copy
2. Click on configure
3. The flow gets created but the name doesn’t change at the top of the page.
4. Go to chats screen and start an automation flow for a contact

**Expected behavior**
A. The name should change here also
B. The flow should start

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/98569671-94395e00-22d8-11eb-9bc4-265d62a37288.png)
![image](https://user-images.githubusercontent.com/16714604/98569817-ba5efe00-22d8-11eb-84d6-669a409bd695.png)

The start button doesn't do anything
![image](https://user-images.githubusercontent.com/16714604/98570911-f47ccf80-22d9-11eb-87c9-521d33b386a8.png)

**Comment by kurund** [comment]
@abhi1203 Ideally draft should not be available to be assigned. @anshulrr is working to fix this and then we can implement the same in frontend.

**Comment by abhi1203** [comment]
Just noticed. Let's please use SVG icons. PNGs pixelate

![image](https://user-images.githubusercontent.com/16714604/98672580-06af4a00-237c-11eb-9ee5-c6badda5094f.png)

**Comment by kurund** [comment]
@abhi1203 Automation image is fixed. Removing of draft automation is fixed in #701
