### ISSUE TITLE
Simulator timeout

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#704]
**Describe the bug**
If the simulator times out, sending a message from the simulator phone doesn't open the chat window in Glific chat panel immediately. Users need to refresh.

**To Reproduce**
1. Wait for the simulator to timeout
2. Initiate conversation from the simulator
3. See that the chat box doesn't show till the user refreshes.

**Expected behavior**
The chat input box should show up and get triggered. It seems for a while that nothing happened and the users can lose their flow. We observed it in the call with ILP.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/98808125-aedb1680-2441-11eb-8337-fed62092325f.png)

**Comment by abhi1203** [comment]
Message came through but the chat input box didn't get activated
![image](https://user-images.githubusercontent.com/16714604/101737008-43d93a00-3aea-11eb-9704-dce4cf72a370.png)

**Comment by rathorevaibhav** [comment]
@abhi1203 we are now making the simulator contact never opt-out. Which means this case will never be there.

I'm not sure if we've pushed this change to the production environments. Will check with the backend team.

**Comment by rathorevaibhav** [comment]
This needs inputs from @glific/glific-backend team.

**Comment by kurund** [comment]
@rathorevaibhav there have been a lot of changes to the simulator. I am closing this and if needed we can reopen or file new one.
