### ISSUE TITLE
In registration page when I click on continue it calls the send-otp API twice.

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#716]
**Describe the bug**
* In registration page when I click on continue it calls the send-otp API twice.

**Expected behavior**
* Should send single otp.

**Comment by DigneshGujarathi** [comment]
@anshulrr 
If I have not opted for WhatsApp and trying to register, it's falling (expected behavior).
Then I have opted (without refreshing the page) & clicked on the "Continue" button then it's sending OTP twice. otherwise, it's working fine.

**Comment by anshulrr** [comment]
@DigneshGujarathi 
Most probably, it is not related to opting in.
I'm able to reproduce the issue with the below steps 
1. I provide an incorrect number for the first time and click on "Continue". The API is called once and fails.
2. I provide an incorrect number once again and click on "Continue". The API is called twice and fails both times.
3. I provide a correct opted-in number and click on "Continue". The API is called twice and OTP is sent twice.
