### ISSUE TITLE
Clicking on 'new flow' is taking to chat screen instead of edit flow

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#744]
Ex. Click on help flow. 
![image](https://user-images.githubusercontent.com/16714604/100210180-b534bc80-2f30-11eb-9491-c817485ca018.png)

User goes to chat screen instead of edit help flow

**Comment by DigneshGujarathi** [comment]
@abhi1203  It was resolved by https://github.com/glific/glific-frontend/pull/739. By the next deployment, we would have this on the server.
