### ISSUE TITLE
Session timer

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#754]
**Describe the bug**
The session timer extends even when message from glific goes to the user

**To Reproduce**
1. Wait for the timer to go low
2. Go to a particular contact and send a message from glific 
3. The timer extends, but it should not.

**Expected behavior**
The timer should not extend in case the message is going from glific.

**Screenshots**
Window got over at around 2pm Nov 26, 
![image](https://user-images.githubusercontent.com/16714604/100410684-70766600-3095-11eb-86b2-33e13c6fea89.png)

**Comment by kurund** [comment]
@abhi1203 Pankaj has fixed this in the backend.
