### ISSUE TITLE
Add to group from floweditor

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#757]
**Describe the bug**
Add to group from floweditor doesn't seem to be working.

**To Reproduce**
1. Create an add to group node in floweditor
2. Run the flow with any contact number
3. Check group contacts in view details
4. See error, that the contact is not there in the group

**Screenshots**
Add to poetry group was added in activity flow
![image](https://user-images.githubusercontent.com/16714604/100411523-08754f00-3098-11eb-8413-fcbd1d605ae1.png)
but the contact didn't get assigned even when the flow was triggered.
![image](https://user-images.githubusercontent.com/16714604/100411645-5b4f0680-3098-11eb-9669-5f3e82ff4407.png)

**Comment by kurund** [comment]
This is fixed as confirmed by @pankaj-ag
