### ISSUE TITLE
All the chats are not showing in the chats sidebar and message isn't triggering

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#765]
![image](https://user-images.githubusercontent.com/16714604/100580761-8b9edb00-330c-11eb-91f5-cb6f70c989f5.png)
There's a chat here that shows on searching, but in the list, on scrolling, it's not showing.

![image](https://user-images.githubusercontent.com/16714604/100580841-ae30f400-330c-11eb-9284-8b54801bc846.png)

Also, sending the message from this number isn't showing in glific.
![IMG_69363BD03578-1](https://user-images.githubusercontent.com/16714604/100580935-d4ef2a80-330c-11eb-8aa1-d01f5c495629.jpeg)

**Comment by kurund** [comment]
@pankaj-ag Let us know your finding on this based on our morning call.

**Comment by kurund** [comment]
This is fixed as confirmed by @pankaj-ag
