### ISSUE TITLE
Add an option to clear attachments

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#782]
**Describe the task**
* Current there is no option to clear or remove the attachments once selected. We have to reload the page.

**Expected behavior**
* We need an option in the attachment selection popup to clear attachments.

**Comment by abhi1203** [comment]
@kurund does this work:
![image](https://user-images.githubusercontent.com/16714604/100966940-16254b80-3554-11eb-8b6a-095d814960f7.png)
leaving it empty should be fine?

**Comment by kurund** [comment]
Yes, that works. If type is selected then URL is required.

**Comment by abhi1203** [comment]
oh in that case we don't have a remove type option, so can we not remove the mandatory check for url?
If it's empty we don't input any url

**Comment by kurund** [comment]
I feel it might be good to clear both. Basically reverting back to the way the form was opened.

**Comment by abhi1203** [comment]
@kurund as per our discussion share the changes to interaction here:
on clicking the attachment icon, this modal will open
![image](https://user-images.githubusercontent.com/16714604/101019181-979bce80-3592-11eb-98bd-02c012d8c41a.png)
on selecting a url type,
![image](https://user-images.githubusercontent.com/16714604/101019214-a5e9ea80-3592-11eb-97cd-1e32478a7aca.png)
these fields will open
![image](https://user-images.githubusercontent.com/16714604/101019274-bc904180-3592-11eb-8c36-1d51bf37caaa.png)
on clicking cross icon, user will go back to first modal in the snapshot.
