### ISSUE TITLE
Issue when simulator contact is blocked.

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#797]
**Describe the task**
* Currently we can block the simulator and it results in unwanted behavior

**Expected behavior**
* We should not allow blocking of the simulator contact

**Comment by kurund** [comment]
@abhi1203 I have updated the issue. I think this is a good short-term solution. Any thoughts?

**Comment by kurund** [comment]
@abhi1203 Looks like we have already implemented this. Do we need anything else on this?

**Comment by DigneshGujarathi** [comment]
This issue has been solved by https://github.com/glific/glific-frontend/pull/806.

**Comment by abhi1203** [comment]
@kurund no, this is alright for now
