### ISSUE TITLE
Minor UI updates

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#804]
Please align the timestamp with the flow name
![image](https://user-images.githubusercontent.com/16714604/101737517-fe693c80-3aea-11eb-8356-275b96639f1d.png)

and the color of Last modified text should be same as text color of Name heading.

Also, can there be an arrow with Last modified by default too like with name.

On speed sends page, the last modified title should be in one line
![image](https://user-images.githubusercontent.com/16714604/102013434-30da9a00-3d76-11eb-9773-a47a151129dc.png)

**Comment by DigneshGujarathi** [comment]
This issue has been resolved by https://github.com/glific/glific-frontend/pull/826
