### ISSUE TITLE
Advanced search button is not accessible for smaller windows

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#811]
**Describe the bug**
For smaller viewport height, the search button in advanced search is inaccessible.

**Expected behavior**
Users should be able to scroll to reach the search button.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/102048290-e2281100-3e04-11eb-86ae-7792578eee05.png)

**Comment by DigneshGujarathi** [comment]
The issue has been resolved by https://github.com/glific/glific-frontend/pull/826
