### ISSUE TITLE
Simulator Preview doesn't work in floweditor screen

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#813]
**Describe the bug**
Sending a message from the simulator preview isn't working in the floweditor. 

**To Reproduce**
1. Go to a configure a flow
2. Click on preview button
3. Send a message from the mobile
4. See error - that no message goes and nothing gets triggered 

**Expected behavior**
I think clicking on preview button should open the simulator and trigger the first message in that flow. So that further conversation can be tested.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/102054193-01c43700-3e0f-11eb-8597-9a1f0b276991.png)

**Comment by kurund** [comment]
@abhi1203 This seems to be working as expected. Can you please recheck?

**Comment by abhi1203** [comment]
Yes @kurund this works well now.
