### ISSUE TITLE
Ability to create groups from floweditor

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#814]
**Describe the task**
Right now, clicking on create group (if that group didn;t exist) doesn't create a new group in the Glific groups screen.

**Expected behavior**
Clicking on create group should also create a group on glific interface, which users can then edit.

**References**
![image](https://user-images.githubusercontent.com/16714604/102054561-9d55a780-3e0f-11eb-9fd8-1e6153d113a9.png)

**Comment by mdshamoon** [comment]
Closing this as it's not needed. It can lead to confusion and unnecessary creation of groups. There is already an interface provided to create groups in glific which should be used.
