### ISSUE TITLE
Prettier Delete 'cr' error in windows

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#817]
**Describe the bug**
Getting delete 'cr' error in windows

**To Reproduce**
1. on running yarn start, error is poping in the homepage.

**Screenshots**
![image](https://user-images.githubusercontent.com/40158831/102183756-5a113c80-3ed4-11eb-9ec5-4c1cd199fa04.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Comment by DigneshGujarathi** [comment]
This issue has been solved by https://github.com/glific/glific-frontend/pull/818
