### ISSUE TITLE
Show which flows are in draft

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#823]
**Is your feature request related to a problem? Please describe.**
On the features listing screen, the user doesn't get to know which flows are in draft.

**Describe the solution you'd like**
An indication on the flows list screen to show which ones are in draft.
This draft tag/indication will be added when a flow is 'saved as draft'. 
Once published, the draft indicator will be removed.

**Describe alternatives you've considered**
There seems to be no alternative right now.

**Comment by kurund** [comment]
@abhi1203 We could also have a published flow which can also have a draft. How do you suggest indicating that? 

It might be good to make a mockup before implementing this feature.

**Comment by abhi1203** [comment]
@kurund i agree, we'll mock it up. However, if a flow has been published before - it shows by the timestamp when. and if it is currently in draft then the draft indicator will show that. sounds okay?

**Comment by Ankitkukreti** [comment]
Here's the solution for the case, you can have a look with here https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=1846%3A275

**Comment by mdshamoon** [comment]
Updated design link https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific
