### ISSUE TITLE
Sending message to a group

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#824]
**Describe the task**
Right now in our designs, for sending message to a group, users need to go to the groups screen and click on the message icon to select whether they want to send a single message or a flow. and then it opens the chat input in a modal to either type a message, select speed send or template. This design causes one challenge when selecting hsm template - selecting variables and attachments will require another modal to open and it may not be the best flow UX wise and front-end dev wise. 

**Task**
We need to prototype in designs two things:
1. Create a complete flow of sending HSM template / speed send in the current design
2. We need to explore alternate flow. Clicking on the message icon on the groups interface will take the user to the main chat interface. On the chat screen there can be two tabs for Chats and Groups. On the groups tab, all the out going messages / flows can be shown.

**Comment by mdshamoon** [comment]
This is completed. Refer to the designs here- https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/collections
