### ISSUE TITLE
HSM template management 

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#827]
**Describe the task**
Requirements for HSM template management:

- NGOs will be able to submit a template from Glific itself
- Once submitted, they will not be able to edit the message other than the attachments
- Each message will be submitted separately for each language
- there will also be a pending approval, approved and rejected status for each hsm
- while sending the hsm in the chat, only the variables and attachment can be changed while other part of the message cannot be edited (we also need to show this blocked state visually)
- Only the approved hsms will show in the list when sending it in the chat

**References**
Design reference: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/WJ2YP2/play

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
