### ISSUE TITLE
HSM template enhancement

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#830]
**Description**
Update the HSM template, a separate template for each language. In the future, the translation will be evaluated. 
- [ ] Revert the translation changes.
- [ ] Add shortcode, category, example, IsActive, etc fields (Need to be finalized from the backend) 
- [ ] Label & Body should be non-editable fields for edit template. (Need to be finalized from the backend)
- [ ]  Add support for all the languages, currently, only active language is available.

Ref: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/09aaZEG

**Comment by abhi1203** [comment]
@DigneshGujarathi designs for this have been added here https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/p/hsm-templates
i don't think we need 'is active' field here. 
and what would shortcode do?
For label and body uneditable - we can show the cursor with blocked icon and input field color like it shows without any text added (light green).

**Comment by DigneshGujarathi** [comment]
> i don't think we need 'is active' field here.
> and what would shortcode do?
@abhi1203 
IsActive field is for, In order to give a user an option to activate or deactivate the template, the deactivated template does not display on the chat screen. 
Shortcode required for approval of the template.
