### ISSUE TITLE
Horizontal scroll on templates screen

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#838]
**Describe the bug**
The columns are getting too wide and there's a horizontal scroll on the screen because of that. Can we adjust these as per the design. For now let's also remove the Category column from the listing screen.

This is 1440px wide viewport
![image](https://user-images.githubusercontent.com/16714604/102864753-ae7b6580-445a-11eb-8f7e-89dd0bf6a025.png)

**Comment by kurund** [comment]
@abhi1203 This is fixed as a part of https://github.com/glific/glific-frontend/issues/832

**Comment by DigneshGujarathi** [comment]
This is fixed as part of https://github.com/glific/glific-frontend/issues/832, so closing now.
