### ISSUE TITLE
Once sorting is selected, it should stay till the users changes it

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#839]
**Describe the bug**
Right now the sorting changes to defualt whenever the screen refreshes.

**Expected behavior**
The sorting should stay fixed till the user changes it and should not change with refreshes.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/102880921-12f5ef00-4472-11eb-8d2d-0903d674161b.png)

**Comment by kurund** [comment]
@abhi1203 We will implement this at the user session-level. It will retain the sorting criteria throughout the logged-in session and once the user logs out sorting etc get's reset.
