### ISSUE TITLE
SoL - Flow stopped all of a sudden for a new contact

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#848]
**Describe the bug**
The flow gets stopped here and I cant start a flow because it says person hasn't opted in. Can you check?

![image](https://user-images.githubusercontent.com/16714604/103077368-a86dbc00-45f5-11eb-8446-0d1d3c8b91da.png)

**Comment by pankaj-ag** [comment]
@abhi1203 I think this is done. It was a bug from the customer side. Can we close this?
