### ISSUE TITLE
Create media speed send throwing an error 

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#855]
![image](https://user-images.githubusercontent.com/10670690/103214139-aed1a000-4935-11eb-9b66-d2790b33babf.png)

It hangs the system also
![image](https://user-images.githubusercontent.com/10670690/103214278-05d77500-4936-11eb-95fe-56e9295c950a.png)

**Comment by DigneshGujarathi** [comment]
@pankaj-ag In the above scenario, the Attachment type is selected but the URL is empty that causing the issue.
Now adding the validation for the dependable field - Attachment Type & URL. If attachment type is selected URL field is required & vice-versa.
