### ISSUE TITLE
Groups showing no contacts available on the system.

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#857]
1. Click on add contact to group icon
2. Select all the members and click outside of the modal
3. Then try to select the contacts again and it will show this option.

![image](https://user-images.githubusercontent.com/10670690/103216133-4a194400-493b-11eb-98c7-9f8edb3991a4.png)

Either we need to click on cancel button or there should be another way to fix this.

**Comment by rathorevaibhav** [comment]
@pankaj-ag tried replicating it but wasn't able to. Can you re-check?

**Comment by pankaj-ag** [comment]
@rathorevaibhav the above issue has been fixed. I saw a new issue while testing this creating a new issue for that.
