### ISSUE TITLE
Chat messages missing and incorrect time of messages

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#859]
Saurabh from TAP has reported an issue.
1.  Chat messages are missing from the chat window.
2. Incorrect time of messages are shown on the chat window.

![WhatsApp Image 2020-12-28 at 15 23 30](https://user-images.githubusercontent.com/16541548/103216600-75506300-493c-11eb-81ea-55fe143c0b23.jpeg)

![WhatsApp Image 2020-12-28 at 18 26 13](https://user-images.githubusercontent.com/16541548/103216606-784b5380-493c-11eb-8fde-6d237e4e9552.jpeg)

**Comment by kurund** [comment]
@DigneshGujarathi Can you please check if this issue still persists?

**Comment by DigneshGujarathi** [comment]
None of the users reported this issue, in this case, it may be due to some network problem. Closing it now. If an issue comes, we can open it again.
