### ISSUE TITLE
Not able to remove all members from the group.

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#862]
1. Go to a staging server
2. Click on groups
3. Try to remove all members from the group

![image](https://user-images.githubusercontent.com/10670690/103266538-d2e4be00-49d5-11eb-8723-d94c42e0462f.png)

**Comment by abhi1203** [comment]
Also, in case it is not captured, that last remaining contact cannot be removed from the group. the cross button becomes inactive for the last contact.
![image](https://user-images.githubusercontent.com/16714604/103269990-0aa33400-49dd-11eb-9d3d-bf875778035f.png)
