### ISSUE TITLE
HSM template management

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#864]
**Describe the task**
1. let's bring Alert_update, Issue_resolution and Auto_reply as the top 3 options in the dropdown since these will probably be the most used ones for NGOs usecase.

![image](https://user-images.githubusercontent.com/16714604/103275502-57413c00-49ea-11eb-894b-ad6fefaa970e.png)

2. please change these labels UI to as in the design
![image](https://user-images.githubusercontent.com/16714604/103275670-b1420180-49ea-11eb-9e21-a7cbf83131cf.png)

**Comment by mdshamoon** [comment]
@anshulrr for the first point can we move the most used options to the top from the backend since we are displaying in the same order that we are getting from the backend.

**Comment by anshulrr** [comment]
@mdshamoon yes we can easily change the order in the backend.

**Comment by abhi1203** [comment]
Can you please look into this overlap also 
![image](https://user-images.githubusercontent.com/16714604/103502570-a28a9d00-4e77-11eb-9a9b-f3ecd2776317.png)

and the horizontal scroll hasn't fully gone
![image](https://user-images.githubusercontent.com/16714604/103502590-b209e600-4e77-11eb-8b50-6bf96898f381.png)

**Comment by abhi1203** [comment]
Please check the line height of the smaller supporting text
![image](https://user-images.githubusercontent.com/16714604/103502684-044b0700-4e78-11eb-849a-a324b8f0ac2a.png)
check the font color for the text below category
