### ISSUE TITLE
Adding app name in Simulator's payload

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#878]
**Describe the task**
As we are adding validation for incoming messages from the backend, the validation is on basis of the app name in the message payload. Currently, the app name is not passed in the payload of the simulator messages, therefore we will be needing to add the same.

**Expected behavior**
App name must be in the payload of simulator messages.

**References**
This should be the format of the payload
```
{
    "app" => "GupshupStar",
    "payload" => %{
      "payload" => %{"text" => "2"},
      "sender" => %{
        "name" => "Simulator",
        "phone" => "9876543210"
      },
      "source" => "919876543210",
      "type" => "text"
    }
  }
```

**Comment by DigneshGujarathi** [comment]
@AkhileshNegi Can you check whether it can be handled internally by the backend? If we can prevent an additional front-end call, it would be good.

**Comment by AkhileshNegi** [comment]
@DigneshGujarathi As this is not on priority. We can come back to it later. Closing it for now
