### ISSUE TITLE
Should we show the organization number or Organization Option link in the frontend.

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#886]
In a couple of calls, I found that NGOs staff needs what number is associated with Glific. 
Should we show that on the frontend?

**Comment by Ankitkukreti** [comment]
Here's the solution for the following issue. You can see the prototype solution here https://www.figma.com/proto/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=516%3A2146&viewport=1805%2C585%2C0.49063098430633545&scaling=min-zoom
Let me know if there's any feedback.

**Comment by kurund** [comment]
@Ankitkukreti Looks like the above link is not accessible without login. If possible can you also please add a screenshot here.

**Comment by DigneshGujarathi** [comment]
We've added a phone number and recommended that the company use opt-in flow rather than an opt-in link, so there's no need to display the opt-in link for now.
