### ISSUE TITLE
Show appropriate message when there is no wallet balance.  

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#890]
Currently, we are showing blank red bar. 

![image](https://user-images.githubusercontent.com/10670690/103766234-7a03ce00-5044-11eb-8219-402d735e3559.png)
![image](https://user-images.githubusercontent.com/10670690/103766357-b8998880-5044-11eb-8baf-71d2077be3ad.png)

**Comment by rathorevaibhav** [comment]
@abhi1203 in addition to correcting the message when the balance is zero, should we do something else too? Like disabling chat input or other things?

**Comment by Ankitkukreti** [comment]
Here's the solution we came up with for the issue. You can see the prototype with this link https://www.figma.com/proto/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=482%3A8135&viewport=1259%2C-1064%2C0.2880047559738159&scaling=min-zoom
Do let me your thoughts/feedbacks on this.

**Comment by DigneshGujarathi** [comment]
This has been resolved by https://github.com/glific/glific-frontend/pull/924
