### ISSUE TITLE
Best practices to capture the app signal errors

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#893]
I recently observed that there some app signal calls on the collate route and those are having an API key in them. 

Can we please make sure that the API KEY is not public?

**Comment by rathorevaibhav** [comment]
@pankaj-ag would be great if you can provide some steps to replicate and see where the API key is visible.

**Comment by rathorevaibhav** [comment]
We're receiving app signal errors now. Closing this issue.
