### ISSUE TITLE
Wallet balance does not show up when Gupshup key is not configured

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#910]
**Describe the task**
Wallet balance keeps loading on the staging environment.
![image](https://user-images.githubusercontent.com/12053186/104409889-3f8eb980-558d-11eb-931e-537c18146837.png)

**Expected behavior**
The wallet balance should be loaded properly with the correct amount

**Comment by rathorevaibhav** [comment]
@abhi1203 @Ankitkukreti this happens when the Gupshup key is not configured from the settings page. Do you think we should show a different message in that case?

**Comment by abhi1203** [comment]
@rathorevaibhav okay, in that case should we say `API key not found` with the red background itself? or is there more to the issue?

**Comment by DigneshGujarathi** [comment]
> @rathorevaibhav okay, in that case should we say `API key not found` with the red background itself? or is there more to the issue?

Can we make some generic message like - "Check the configuration of Gupshup" having a tooltip something like "Please contact the Glific team if you have configured"

**Comment by abhi1203** [comment]
@DigneshGujarathi yeah that could be possible. We could say `Check gupshup settings` to cave some character space.
i believe this is because the error can show up even when app name is not present? any other factors?

**Comment by DigneshGujarathi** [comment]
> @DigneshGujarathi yeah that could be possible. We could say `Check gupshup settings` to cave some character space.
> i believe this is because the error can show up even when app name is not present? any other factors?

Yeah, Not aware of all the other factors.
