### ISSUE TITLE
Add tool tips for session timer states

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#935]
**Describe the task**
Right now it is not clear to the staff members who are new to the platform, what the session timer is all about. And they get confused why the messages are not being sent. 

**Probable solution**
We could add tooltips on the time when there's the session timer is between 24 and 0, when it is 0 and when the block icon shows up. We could possibly add link to documentation that explains the session window - maybe some whatsapp resource.

**Comment by Ankitkukreti** [comment]
We have created UI as per the solution is described. This could be one of the possible solution for this. Dev team let us know your thoughts. https://www.figma.com/file/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=777%3A1078

**Comment by DigneshGujarathi** [comment]
@Ankitkukreti Should we also add this to the session timer of the conversation list?
