### ISSUE TITLE
401 error message

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#948]
**Describe the bug**
Users get an error message "**A network error has occurred, Response not successful - Received status code 401**" when they come back to Glific after keep it idle for some time.

**To Reproduce**

lobo Today at 10:00
hey @Glific Frontend
steps to reproduce
get system yp and running
log in to frontend
do a few things
kill backend
rm -rf Mnesia*
mix phx.server
try doing stuff from frontend now
get 401 error
and if u r in simulator, it just eats the messages and nothing happens

**Expected behavior**
It should redirect to the login page.

**Screenshots**
![401 error messgae](https://user-images.githubusercontent.com/16541548/105459650-9c3a5480-5cb0-11eb-9426-8a234890368c.jpeg)

**Comment by abhi1203** [comment]
@DigneshGujarathi should there be a message on the login screen, why they were logged out?

**Comment by DigneshGujarathi** [comment]
> @DigneshGujarathi should there be a message on the login screen, why they were logged out?

If NGOs face any problems with this, may we think about it? To do this, we need to identify the cause for logouts, such as the User action or the Network Problem.
