### ISSUE TITLE
Videos doesn't play in chat window in safari

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#949]
**Describe the bug**
Videos don't play in the chat window in safari, sent while communication in the flow

**To Reproduce**
1. sent any .mp4 video file from what's App to Glific chat.
2. Open chat window in Glific in Safari.
3. Click on the play icon in the video in the chat window.
4. Play icon will have a strike-off line on it and it will not play.
5. Works fine in Chrome.

**Expected behavior**
It should play in the safari browser also

**Screenshots**
<img width="458" alt="Video in caht" src="https://user-images.githubusercontent.com/16541548/105461724-9db94c00-5cb3-11eb-9aed-7f17e188d32a.png">

<img width="1253" alt="video in chat 2" src="https://user-images.githubusercontent.com/16541548/105461795-b45fa300-5cb3-11eb-96c3-5df8810819df.png">

**Desktop (please complete the following information):**
 - OS: [Windows, iOS]
 - Browser [ SAFARI]
 - Version [ALL]

**Comment by mdshamoon** [comment]
We need byte-range headers to play videos in safari. Checked with the gupshup team and they are working on this.

![image](https://user-images.githubusercontent.com/32592458/108960250-9f53a680-769b-11eb-9f8f-fcca470a9e18.png)
![image](https://user-images.githubusercontent.com/32592458/108960275-aa0e3b80-769b-11eb-836b-d577e14051f0.png)

**Comment by rathorevaibhav** [comment]
Okay. Let's target it in the first week of March then.

**Comment by mdshamoon** [comment]
We are now getting byte range headers but also need range request header support to play videos in Safari. Gupshup does not provide this support since whatsapp does not support this.
We need to host videos on our platform to play these videos on Safari.

![image](https://user-images.githubusercontent.com/32592458/114142120-1ed9c400-9930-11eb-931c-f5933a3fda30.png)

**Comment by mdshamoon** [comment]
Closing this since its not needed for now.
