### ISSUE TITLE
Feature:Display group information

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#958]
**Is your feature request related to a problem? Please describe.**

Display group information
- Count of total contacts 
- Count of  Active/opt-in contact
- Count of Deactivate/non opted/session expired contact
- Status of contact in group/individual

**Comment by Ankitkukreti** [comment]
@DigneshGujarathi what's the use case for this?

**Comment by Ankitkukreti** [comment]
We have created the solution for the case you can check it out with this link. https://www.figma.com/proto/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=1176%3A3554&viewport=1360%2C329%2C0.24605369567871094&scaling=min-zoom

**Comment by Ankitkukreti** [comment]
I have updated the design for this, you can have a look here
 https://www.figma.com/proto/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=1176%3A3554&scaling=min-zoom&page-id=1176%3A3548
