### ISSUE TITLE
element name validation for hsm templates

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#966]
**Describe the solution you'd like**
When submitting template for approval, There has to validation on element name as per gupshup guidelines for templates

**Additional context**
Element is a name you choose for your template. An element name can only be in
lowercase alphanumeric characters and underscores. Special characters and
white-space are not allowed.

![template](https://user-images.githubusercontent.com/40158831/106453041-b7764280-64ae-11eb-8351-62bb26b77c53.png)

**Comment by DigneshGujarathi** [comment]
The issue has been fixed by https://github.com/glific/glific-frontend/pull/967
