### ISSUE TITLE
Displaying error response when sending hsm template

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#978]
**Describe the bug**
When sending HSM template to user and error occurs. It display a generic message that 24 hrs window closed.

**Expected behavior**
We should be displaying different error messages in different scenerios rather than a 
generic message like 24 hrs window has closed 

![template](https://user-images.githubusercontent.com/40158831/106704134-8d896100-6611-11eb-9210-ba1bd76f0a14.png)

**Comment by Ankitkukreti** [comment]
@AkhileshNegi can you share some cases for the same? I mean the type of error occurs, it would help.

**Comment by kurund** [comment]
@AkhileshNegi It would be great if you can explain various error scenarios here.

**Comment by AkhileshNegi** [comment]
@Ankitkukreti @kurund We are already sending error message in the message subscription, similar to text messages error which we are already showing

**Comment by mdshamoon** [comment]
After discussing with @AkhileshNegi we are getting the error response in the message and on the frontend we are already displaying that error along with the message. 

Closing this since it's already completed.
