### ISSUE TITLE
Sending Collection messages through flow

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#979]
**Describe the bug**
While sending hsm template to a collection the variable should be more dynamic like @contact.field.name, like replacing the variable with contact name for each contact of group.
As the group messages are not used that frequently, we can tackle same by sending group message from flow to use flow components like variable.

**Expected behavior**
Sending group message should only have option to start a flow and the flow should have the ability to replace variable of template with flow component like @contact.field.name

**Comment by rathorevaibhav** [comment]
This doesn't seem to be an immediate priority after discussing with Akhilesh. Deferring this to later milestone.

**Comment by Ankitkukreti** [comment]
We have made the UI enhancements and created a prototype solution for the case. you can access it with this link. let us know if there's any feedbacks. https://www.figma.com/proto/hHnouY0vLcmLnAoNzYkeqW/Glific?node-id=2024%3A260&scaling=min-zoom

**Comment by dlobo** [comment]
variable support is only thru flows. we wont fix this
