### ISSUE TITLE
Caching issue on chat screen

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#997]
**Describe the bug**
Caching issue has increased nowadays. It is very frequent.
I just login and try to send some messages on chat, but it didn't show up on the bot, whereas it shows in my What's App.
I refreshed the page and it is showing now.

**Expected behavior**
It should show the messages on the bot. If the session is expired, it should redirect the user to login page.

**Screenshots**
<img width="1427" alt="Screenshot 2021-02-12 at 4 21 13 PM" src="https://user-images.githubusercontent.com/16541548/107760244-718f6900-6d4f-11eb-81b4-287f486b7191.png">

<img width="1429" alt="Screenshot 2021-02-12 at 4 21 27 PM" src="https://user-images.githubusercontent.com/16541548/107760257-7522f000-6d4f-11eb-85ea-dfb67a0a99a7.png">

<img width="801" alt="Screenshot 2021-02-12 at 4 30 15 PM" src="https://user-images.githubusercontent.com/16541548/107760475-cf23b580-6d4f-11eb-92dc-88040ffd7399.png">

**After I refresh the page**
<img width="1428" alt="Screenshot 2021-02-12 at 4 26 37 PM" src="https://user-images.githubusercontent.com/16541548/107760281-7c49fe00-6d4f-11eb-85c3-ac3dac35cafa.png">

**Comment by rathorevaibhav** [comment]
This is a bit difficult to debug and get to the root cause. An ideal time to target this is after logging #1010 is implemented.

@mohitsharma-22 does that work for you or you see it is needed earlier?

**Comment by mohitsharma-22** [comment]
@rathorevaibhav Thanks for checking and follow up. We are not getting the cache issue reported very frequently now. You can plan to do it later. If we come across any such issue before the fix, we can change the priority.

**Comment by kurund** [comment]
This might be related to https://github.com/glific/glific-frontend/issues/1004
