### ISSUE TITLE
User logged out abruptly while working on chat screen.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#998]
**Describe the bug**
NGO user was demoing the use case while screen sharing. We were looking at the screen to see the output on the chatbot and the user was redirected to the login screen abruptly.

Below are the details I captured to investigate.
User - Naman
NGO - Medha
Time - 11 Feb 2021 - 2:46 PM IST

**Comment by dlobo** [comment]
Most likely this was because we the server crashed or we did a deploy
